### ISSUE TITLE
Create a template for personal information wiki pages

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#1]
We decided to have personal wiki pages which summarize team members.
A template to define the structure of these pages is needed.

**Comment by mbatuhancelik** [comment]
Template is created and is waiting for approval of the team.

**Comment by bahricanyesil** [comment]
I created an issue for personal wiki page checklist and also mentioned the template you've created there. Everyone can update and follow the checklist in that issue, #5.

**Comment by bahricanyesil** [comment]
I've created my own personal wiki page. Everyone can look at it and may benefit from it. You can reach it out [here](https://github.com/bounswe/bounswe2022group2/wiki/Bahrican-Yesil).

@mbatuhancelik As enhancements to the template you've created, I've added the following to my personal wiki page:
- Used some badges for skills and contact sections
- Edited skills and interests section as a heading
- Changed the default visibility status of the skills section as "open" 

You can also add them and update the template if you wish.

**Comment by mbatuhancelik** [comment]
With @bahricanyesil 's contributions, the template is completed.
