### ISSUE TITLE
Documenting the Research of Git Commands

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#10]
Complying with the division of labour between the team members, I undertook the responsibility to document the information about git commands into tables under their respective categories.

The required information mentioned above will be a result of some collaborative research efforts from all the team members.

* This issue has to wait for the researches made by team members.

**Comment by surmelienes1** [comment]
I have completed the preperation of the git command tables thanks to the information gathered by the team members.

**Comment by bahricanyesil** [comment]
Can you add the results of my research about the "less known but useful git commands" to the table? I guess some of them are missing, I'm appending them here:

Some Helpful - Less Known Git Commands

1- We all have pressed the miss key while trying to run a command instantly at least one time before. To save our life, we can enable git autocorrection to directly fix the typos with the help of following command:
$ git config --global help.autocorrect 1

2- We can count the number of commits in our branch-project with the command:
$ git rev-list --count

3- We can clear unreachable or orphaned git objects from the repository to optimize the use of git repositories, the following command does the job:
$ git gc --prune=now --aggressive

4- We may want to view a file of another branch while working on the current branch. Git has a super easy and practical command for this purpose. Example usage:
$ git show main:README.md

5- We can quickly search anything we want to find in a repo with the following example command:
$ git rev-list --all | xargs git grep -F 'Write the search keys here'

6- If you want to test “commit” command without really committing something (for example to test the flow), you can use empty committing:
$ git commit --allow empty -m 'it works!'

7- You can compare commits with a simple command:
$ git diff
Example:
$ git diff $start_commit..$end_commit -- path/to/file


Sources:
*https://opensource.com/article/20/10/advanced-git-tips 
*https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_help_autocorrect_code 
*https://www.honeybadger.io/blog/git-tricks/
*https://about.gitlab.com/blog/2020/04/07/15-git-tips-improve-workflow/

**Comment by surmelienes1** [comment]
Added the table from the Bahrican's research and credit information for the contributors to the Git Commands page.

**Comment by surmelienes1** [comment]
With collaborative efforts from the team, I have finalized the Git Command table. If you have further questions or suggestions, please reopen this issue.
