### ISSUE TITLE
Software Design: Class Diagram - Enrolled Actions

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#100]
### Issue Description

As the next part of the software design process, we will provide a class diagram for our project moving from the use case diagram phase. Class diagram will be completed with a collective effort and I will be preparing the **user** sub-section of the diagram.
* This issue is a sub-issue of #86 .
* **Enrolled** class will be formed, using related sections of our use case diagram as basis.

* The class diagram will be generated using the Lucichart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram
- [x] Define the attributes of the enrolled class with name, type and description columns.
- [x] Define the methods of the enrolled class withe name, parameters, return type and requires auth columns.
- [x] Check the possible inheritance, association, aggregation, composition relationships.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After each part of the User class is determined and combined into a diagram, it will be merged into the main class diagram provided in this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

04.04.2022 - Monday - 23.59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

05.04.2022 - Tuesday - 10.00

**Comment by surmelienes1** [comment]
I completed the enrolled part of the class diagram for now. You can access it via our [class diagram project link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/edit?invitationId=inv_26b91b21-bb1b-47cd-96e4-a1a28fc9b0ce). After we hold our meeting to review the class diagram as a whole, we can make an additional integrity check, and some updates to the enrolled class according to the rest of the work from other team members. Here's the screenshot of the corresponding part: 
<img width="519" alt="Screen Shot 2022-04-05 at 07 12 07" src="https://user-images.githubusercontent.com/74325266/161677376-870482e8-b29d-4c61-916b-f6ec166f3005.png">

**Comment by mbatuhancelik** [comment]
I think Enrollment should have has multiple relationship with User instead of instance of.

 We may think this like relationships in sql, we have users and courses, then a relationship binds them together and we can sewer this bond whenever we want.
If enrollment is an instance of user, for each enrollment we need to create a separate user class inside of enrollment, this leads to data multiplication.

**Comment by surmelienes1** [comment]
Thank you for your comments and suggestions @mbatuhancelik. Considering the aspects you mentioned above, I made some improvements on the enrolled class.
* I followed the conventional writing style and created a list to store banned users.

* You can see the current version of the enrolled class in the screenshot below.
<img width="643" alt="Screen Shot 2022-04-05 at 14 58 00" src="https://user-images.githubusercontent.com/74325266/161749070-630ecdaf-c911-4281-8d92-94c2be2e28ca.png">
