### ISSUE TITLE
Documenting Meeting Notes - Week #5

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#101]
### Issue Description

- Notes taken during the fifth meeting on 31/03/2022 should be documented on the wiki page.
- These notes should follow the criteria on the [Meeting Notes template](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-Notes-Template). The template contains the details about the sections that should be in the meeting notes.
- Meetings notes should be linked in the required places.

Sections which should have a link to the 5th week meeting notes:

- [x] [Home wiki page](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes)
- [x] [Sidebar](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes)

### Deadline of the Issue

05.04.2022 - Tuesday - 23.59

**Comment by surmelienes1** [comment]
Since @ahmet633 has not fulfilled his given task of documenting the notes of our 5th meeting to the [wiki page](https://github.com/bounswe/bounswe2022group2/wiki) and has shown no sign of fulfilling it, I am removing him from the assignee list.

I will assign myself to this issue and will complete the task of documenting the notes.

**Comment by surmelienes1** [comment]
## Information

As the first step, I created the necessary wiki page for our [5th meeting notes](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%235-(31.03.2022)) and added it to the wiki home page and side bar.

The content of the page will be filled today.

**Comment by surmelienes1** [comment]
I have finalized the documentation of our 5th meeting notes.

All of the details related to this meeting can be seen in [Meeting Notes - Week #5 Wiki Page](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%235-(31.03.2022)). If you have further questions or suggestions, you can reopen this issue and add your suggestions as a comment.
