### ISSUE TITLE
Software Design: Class Diagram - Search

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#103]
### Issue Description

As the next part of the software design process, we will provide a class diagram for our project moving from the use case diagram phase. Class diagram will be completed with a collective effort and as part I will be preparing the parts of the diagram related to search operation.
* This issue is a sub-issue of #86 .
* There will be two classes related to search operation
   1. SearchEngine
   2. SearchHandler
* These classes will be formed, using this section of the use case diagram as basis:
<img width="588" alt="Ekran Resmi 2022-04-05 17 05 43" src="https://user-images.githubusercontent.com/68481602/161772249-527ab2a3-b720-4efa-af30-563b996b0273.png">

### Step Details

Steps that will be performed:
- [x] Review relevant parts of the Use-Case Diagram
- [x] Review relevant requirements
- [x] Define the attributes for each class
- [x] Define the methods for each class
- [x] Define the relations of these classes with each other and the remaining classes
- [x] Add those to the Class Diagram

### Final Actions

* After each class is determined and combined into a diagram, it will be merged into the main class diagram provided in this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

05.04.2022 - Tuesday - 22.00

### Reviewer

Ecenur Sezer - @codingAku 

### Deadline for the Review

05.04.2022 - Tuesday - 23.59

**Comment by xltvy** [comment]
## SearchEngine

I defined the SearchEngine class attributes as follows:

|Attribute Name|Type|Description|
|:-----|:--------:|:------|
|search_type|string|type of the searched element (course or user)|
|searched_element|string|searched element|
|searcher_id|UID|ID of the user that performs search operation|
***
I defined the SearchEngine class methods as follows:

|Method Name|Parameters|Return Type|
|:-----|:--------:|:------|
|query|search_type: string, searched_element: string|void|
|setSearchType|search_type: string|void|
|getSearchType|-|string|
|getSearcherID|-|UID|
|getSearchedElement|-|string|

**Comment by xltvy** [comment]
## SearchHandler

I defined the SearchHandler class attributes as follows:

|Attribute Name|Type|Description|
|:-----|:--------:|:------|
|search_type|string|type of the searched element (course or user)|
|searched_element|string|searched element|
***
I defined the SearchHandler class methods as follows:

|Method Name|Parameters|Return Type|
|:-----|:--------:|:------|
|searchUser|_key: string|List<User>|
|searchCourse|_key: string|List<Course>|

**Comment by xltvy** [comment]
## Info:
I have created the initial form of the **SearchEngine** and **SearchHandler** classes as part of the class diagram of our project.

Here is a screenshot taken directly from our class diagram, which can be viewed from this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#):

<img width="377" alt="Ekran Resmi 2022-04-05 21 33 01" src="https://user-images.githubusercontent.com/68481602/161825829-589df274-650a-42aa-be7a-07b277a843bd.png">

This issue will be reviewed and if necessary edited/updated further.

**Comment by codingAku** [comment]
Class diagrams have been reviewed in our meetings and in PS session. Everything is compatible with our discussions.
