### ISSUE TITLE
Software Design: Class Diagram - Chat

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#105]
### Issue Description

This is a sub issue from #71.

Contrary to our task division at [Meeting #5.1 Class Diagram Meeting (02.04.2022)](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%235.1---Class-Diagram-Meeting-(02.04.2022)) I was assigned to creating class diagrams for chat feature.

Designed classes should implement following use cases from our [use case diagram](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c) with help of message class implemented under #93 : 

![image](https://user-images.githubusercontent.com/63948452/161820666-968464ea-e49a-414e-93e4-728412d4ddf2.png)

### Step Details

Feature that will be implemented
- [x] Send messages
- [x] Send Notes

### Final Actions

- [ ] Merge classes created here to #86 

### Deadline of the Issue

06.04.2022 - Wednesday -10.00

### Reviewer

@surmelienes1 

### Deadline for the Review

06.04.2022 - Wednesday -11.00

**Comment by mbatuhancelik** [comment]
After a quick chat at our discord channel, we decided that creating events in chats would be resolved easily by using the creating event class in class diagram, and should be separated from chat instance. They will be implemented side by side in chat screen in our frontend.

**Comment by mbatuhancelik** [comment]
I believe the current version I created on [lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/edit?invitationId=inv_26b91b21-bb1b-47cd-96e4-a1a28fc9b0ce) satisfies the requirements, a review is requested from @xltvy

**Comment by surmelienes1** [comment]
There are two aspects for which I have a question in mind: 
1) I could not quite understand what you meant by "User-messages:List<Messages> sorted by timestamp" in the last attribute of the chat class. Right-hand side of the ":" sign is okay to me, but I could not get the convention you used to write the left-hand side as "User-messages".

2) I am not sure about whether or not there should be a composition relation going from User class to ChatBox class.

Other than these it looks very good, thank you @mbatuhancelik for your contributions.

**Comment by mbatuhancelik** [comment]
> 2. I am not sure about whether or not there should be a composition relation going from User class to ChatBox class.

Since I used web sockets for establishing real time communication and they are costly in terms of network, ChatBox acts like a wrapper that contains the web socket connected to every user. Composition is required to ensure that each user has only one chatbox, thus one socket.



> 1. I could not quite understand what you meant by "User-messages:List sorted by timestamp" in the last attribute of the chat class. Right-hand side of the ":" sign is okay to me, but I could not get the convention you used to write the left-hand side as "User-messages".

I was trying to show that this list is sorted but I guess we cant show sorted property in uml. I will remove that.
