### ISSUE TITLE
Software Design: Use Case Diagram - Course Enrollment

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#106]
### Issue Description

Before finalizing our Use Case Diagram, we have noticed course enrollment action is missing in the Use Case Diagram. So, I will be adding this operation to the appropriate section of our diagram, which can be viewed from this [link](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_acc885f2-fa4a-491c-888a-b14b05e8aa09).

### Step Details

Steps that will be performed:
- [x] Determine the appropriate section of the diagram for course enrollment
- [x] Check if there are more elements to be added alongside the course enrollment, related to the topic
- [x] Finalize it for review

### Final Actions

* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

05.04.2022 - Tuesday - 22.30

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

05.04.2022 - Tuesday - 22.45

**Comment by xltvy** [comment]
## Info
I have completed this enhancement of adding the course enrollment action to the use case diagram. Since, reviewing courses is an action that can be performed only after enrolling a course, I have binded its arrow to **enroll to course** cell. It was before binded to **view course page** cell.

Here is a screenshot of the final version:

<img width="368" alt="Ekran Resmi 2022-04-05 22 14 06" src="https://user-images.githubusercontent.com/68481602/161832471-dba6e55d-7273-4b0a-b16c-156f1f3dc658.png">

Now, it is ready for a review! @surmelienes1

**Comment by surmelienes1** [comment]
I think there should be an arrow carrying **includes** on it from enroll to course to review course, but this is just a small detail.

Other than that it seems very good, thank you @xltvy for your contributions.

I will now close this issue since I don't have anything to further add, if you have any questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
