### ISSUE TITLE
Software Design: Sequence Diagram - Registration

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#108]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. Sequence diagram will be completed with a collective effort and I will be preparing the **registration** sub-section of the diagram.
* This issue is a sub-issue of #107.
* **Registration** part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as basis.

Use-Case Diagram
![Screen Shot 2022-04-04 at 12 07 07](https://user-images.githubusercontent.com/60237280/161511575-3a149e79-c847-45b5-b01f-18ac13a42be5.png)

Class Diagram
![Screen Shot 2022-04-04 at 13 03 15](https://user-images.githubusercontent.com/60237280/161545718-9051f582-cbfd-408d-8a0d-4c3c2830402a.png)

* The sequence diagram will be generated using the Lucidchart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After registration part of the sequence diagram is implemented, it will be merged into the main sequence diagram project provided in this [link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
* After completion, this issue will be reviewed and evaluated by the reviewed and other team members upon closing the issue.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Hasan Can Erol

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by bahricanyesil** [comment]
## Info

Here are the information about the registration part of the sequence diagram
**Actor**: Guest

**Preconditions**: 
* S/he downloaded the app.
* S/he has not registered to the app yet.

**Actions**:
* Enters his/her username, email, and password.
* Reads and accepts the privacy policy and terms&conditions.
* Verifies his/her email address by entering the received verification code.

**Comment by bahricanyesil** [comment]
I completed the registration part of the sequence diagram. You can access the diagram via [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

I am also attaching the screenshot of the diagram here:
![Screen Shot 2022-04-06 at 13 51 31](https://user-images.githubusercontent.com/60237280/161959120-e9c38e8e-175c-4682-8cbd-e93c624a7940.png)

**Comment by bahricanyesil** [comment]
I realized that I forgot to add activation boxes. I will add them right now.

**Comment by bahricanyesil** [comment]
I added the activation boxes to the objects. You can access to the updated diagram [here](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

You can see the updated screenshot:
![Screen Shot 2022-04-06 at 14 07 31](https://user-images.githubusercontent.com/60237280/161961757-23199e8c-042a-4426-9d06-980d3c64be96.png)

**Comment by bahricanyesil** [comment]
I finished the diagram creation process for registration. It is now ready to be reviewed by @hasancan-code. It is accessible from lucidchart link given above.

**Comment by bahricanyesil** [comment]
We received some feedbacks from Egemen in the PS. I will update the diagram accordingly. Here are the feedbacks:

1. Remove server and manage all things with classes and DB
2. Use methods defined in the class diagram for all messages (except error messages and some DB actions)
3. Simplify the diagram

**Comment by bahricanyesil** [comment]
## Update

I updated the diagram according to the feedbacks received. You can access the updated diagram with [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).

I am also attaching a screenshot of the updated diagram.
![Screen Shot 2022-04-07 at 10 44 02](https://user-images.githubusercontent.com/60237280/162146995-41e48c4f-928c-40ad-a7a4-e3ff69ea5349.png)

**Comment by bahricanyesil** [comment]
Now, the diagram is ready for a final review from @xltvy if there is additional things.

**Comment by xltvy** [comment]
Thank you for your detailed work! I have reviewed the final version of the sequence diagram of registration. I think it is pretty close to be done. I just have a little point:
* We may name guest actor as non-registered user, since we have named it like that in everywhere else.

Else, it is done I guess. Thank you for your effort.

**Comment by bahricanyesil** [comment]
> Thank you for your detailed work! I have reviewed the final version of the sequence diagram of registration. I think it is pretty close to be done. I just have a little point:
> 
> * We may name guest actor as non-registered user, since we have named it like that in everywhere else.
> 
> Else, it is done I guess. Thank you for your effort.

Thank you for the review @xltvy. I will update that part and will be sharing final version as a comment.

**Comment by bahricanyesil** [comment]
## Update

I updated the diagram according to the review received from @xltvy. You can access the updated diagram with [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).

I am also attaching a screenshot of the updated diagram.
![Screen Shot 2022-04-07 at 12 39 57](https://user-images.githubusercontent.com/60237280/162170182-b07dd2d3-1bab-41a9-9d2c-c956feaa9e17.png)

**Comment by bahricanyesil** [comment]
Since we finalized the diagram, received feedback from our TA (Egemen), the diagram is reviewed by the reviewer (@xltvy) and I made the necessary updates, I am closing the issue.

**Comment by bahricanyesil** [comment]
I just added names to the alternative frames:

![Screen Shot 2022-04-07 at 12 47 25](https://user-images.githubusercontent.com/60237280/162171760-42eebf79-5fe1-417c-924f-d689662c8a15.png)
