### ISSUE TITLE
Software Design: Sequence Diagram - Login

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#109]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. Sequence diagram will be completed with a collective effort and I will be preparing the **login** sub-section of the diagram.
* This issue is a sub-issue of #107.
* **Login** part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as basis.

Use-Case Diagram
![Screen Shot 2022-04-04 at 12 07 07](https://user-images.githubusercontent.com/60237280/161521721-dde5d707-1a57-436c-899c-25f376c63ff1.png)

Class Diagram
![Screen Shot 2022-04-04 at 13 03 15](https://user-images.githubusercontent.com/60237280/161545718-9051f582-cbfd-408d-8a0d-4c3c2830402a.png)

* The sequence diagram will be generated using the Lucidchart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After login part of the sequence diagram is implemented, it will be merged into the main sequence diagram project provided in this [link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
* After completion, this issue will be reviewed and evaluated by the reviewed and other team members upon closing the issue.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Hasan Can Erol

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by bahricanyesil** [comment]
## Info

Here are the information about the registration part of the sequence diagram
**Actor**: Registered User

**Preconditions**:
* S/he has already registered to the app and has an account.
* S/he logged out or has been kicked out due to long inactivity.

**Actions**:
* Enters his/her username and password.

**Comment by bahricanyesil** [comment]
I completed the login part of the sequence diagram. You can access the diagram via [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

I am also attaching the screenshot of the diagram here:
![Screen Shot 2022-04-06 at 14 26 20](https://user-images.githubusercontent.com/60237280/161964528-45d96fd1-b3e5-4df1-b14d-30e64c753a19.png)

**Comment by bahricanyesil** [comment]
I finished the diagram creation process for login. It is now ready to be reviewed by @hasancan-code. It is accessible from lucidchart link given above.

**Comment by bahricanyesil** [comment]
## Feedbacks

We received some feedbacks from Egemen in the PS. I will update the diagram accordingly. Here are the feedbacks:

1. Remove server and manage all things with classes and DB
2. Use methods defined in the class diagram for all messages (except error messages and some DB actions)
3. Simplify the diagram

**Comment by bahricanyesil** [comment]
## Update

I updated the diagram according to the feedbacks received. You can access the updated diagram with [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).

I am also attaching a screenshot of the updated diagram.
![Screen Shot 2022-04-07 at 10 46 52](https://user-images.githubusercontent.com/60237280/162147615-f047bf36-ba70-4651-b7a2-a42acc77fa98.png)

**Comment by bahricanyesil** [comment]
Now, the diagram is ready for a final review from @xltvy if there are additional things.

**Comment by xltvy** [comment]
Thank you for your detailed work! I have reviewed the final version of the sequence diagram of login. I think it is pretty close to be done. I just have a little point:
* We may name guest actor as non-registered user, since we have named it like that in everywhere else.

Else, it is done I guess. Thank you for your effort.

**Comment by bahricanyesil** [comment]
> Thank you for your detailed work! I have reviewed the final version of the sequence diagram of login. I think it is pretty close to be done. I just have a little point:
> 
> * We may name guest actor as non-registered user, since we have named it like that in everywhere else.
> 
> Else, it is done I guess. Thank you for your effort.


Thank you for the review @xltvy. I will update that part and will be sharing final version as a comment.

**Comment by bahricanyesil** [comment]
## Update

I updated the diagram according to the review received from @xltvy. You can access the updated diagram with [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).

I am also attaching a screenshot of the updated diagram.
![Screen Shot 2022-04-07 at 12 40 08](https://user-images.githubusercontent.com/60237280/162170227-8e76ee73-87a5-43c2-81ea-4595b26811f9.png)

**Comment by bahricanyesil** [comment]
I just added a name to the alternative frame:
![Screen Shot 2022-04-07 at 12 48 37](https://user-images.githubusercontent.com/60237280/162171944-ce5105b4-7349-43a4-bc64-3142639316ab.png)
