### ISSUE TITLE
New labels

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#11]
New labels for the issues are added. Labels about priority of the issue, type of the issue, and the status of the issue are the newly added labels. Is there any further label suggestions at this point of time about the project?

**Comment by ezgy** [comment]
Having both default tags like "documentation" and newly created "type-documentation" may cause confusion. Perhaps with duplicate ones we can only keep the label with "type-" prefix for better classification.

**Comment by xltvy** [comment]
> We can add "waiting for response" label for the issues that has some feedback/suggestion/edit requests and waiting for the action of the issue creator.

status-needreview label is for this purpose, if it needs more clarification we can edit the description of this label

**Comment by xltvy** [comment]
> Having both default tags like "documentation" and newly created "type-documentation" may cause confusion. Perhaps with duplicate ones we can only keep the label with "type-" prefix for better classification.

Good suggestion, I am getting rid of the duplicate ones even though they were defaultly added.

**Comment by xltvy** [comment]
> We may add a color code to the labels. For example all labels regarding priority may be the same color. Thus, it would be easier to find the labels we are looking for in an issue.

I think making every priority type label in the same color will contradict with the idea of separating the issues according to their priorities. But except priority based labels we can discuss a color code if necessary.

**Comment by bahricanyesil** [comment]
> > We can add "waiting for response" label for the issues that has some feedback/suggestion/edit requests and waiting for the action of the issue creator.
> 
> status-needreview label is for this purpose, if it needs more clarification we can edit the description of this label

As far as I understood:

"status-needreview" means that the creator of the issue waits something from the other ones.

What I wanted to indicate with "waiting for response" is the fact that other ones suggested something or asked something and they are waiting for the answer of the issue creator.

Did you understand what I mean? Do you still think the same?

**Comment by xltvy** [comment]
> > > We can add "waiting for response" label for the issues that has some feedback/suggestion/edit requests and waiting for the action of the issue creator.
> > 
> > 
> > status-needreview label is for this purpose, if it needs more clarification we can edit the description of this label
> 
> As far as I understood:
> 
> "status-needreview" means that the creator of the issue waits something from the other ones.
> 
> What I wanted to indicate with "waiting for response" is the fact that other ones suggested something or asked something and they are waiting for the answer of the issue creator.
> 
> Did you understand what I mean? Do you still think the same?

Okay, understood. We can use this newly created label <status-waitingresponse> when any edit for the author is suggested after <status-needreview> status is through.

**Comment by bahricanyesil** [comment]
It may be good to change the name I suggested with something else to
clarify better if you want. I just wrote the name of the label like that
because I saw it from some other example repositories. Thank you.

8 Mar 2022 Sal 00:45 tarihinde Altay Acar ***@***.***> şunu
yazdı:

**Comment by bahricanyesil** [comment]
> > > > We can add "waiting for response" label for the issues that has some feedback/suggestion/edit requests and waiting for the action of the issue creator.
> > > 
> > > 
> > > status-needreview label is for this purpose, if it needs more clarification we can edit the description of this label
> > 
> > As far as I understood:
> > 
> > "status-needreview" means that the creator of the issue waits something from the other ones.
> > 
> > What I wanted to indicate with "waiting for response" is the fact that other ones suggested something or asked something and they are waiting for the answer of the issue creator.
> > 
> > Did you understand what I mean? Do you still think the same?
> 
> Okay, understood. We can use this newly created label <status-waitingresponse> when any edit for the author is suggested after <status-needreview> status is through.

It may be good to change the name I suggested with something else to
clarify better if you want. I just wrote the name of the label like that
because I saw it from some other example repositories. Thank you.

**Comment by bahricanyesil** [comment]
> > > > We can add "waiting for response" label for the issues that has some feedback/suggestion/edit requests and waiting for the action of the issue creator.
> > > 
> > > 
> > > status-needreview label is for this purpose, if it needs more clarification we can edit the description of this label
> > 
> > 
> > As far as I understood:
> > "status-needreview" means that the creator of the issue waits something from the other ones.
> > What I wanted to indicate with "waiting for response" is the fact that other ones suggested something or asked something and they are waiting for the answer of the issue creator.
> > Did you understand what I mean? Do you still think the same?
> 
> Okay, understood. We can use this newly created label when any edit for the author is suggested after status is through.

I just saw it from some advanced repositories like [flutter](https://github.com/flutter/flutter) and advised it here too since it may be helpful for us too.
