### ISSUE TITLE
Software Design: Sequence Diagram - Search User

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#112]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. Sequence diagram will be completed with a collective effort and I will be preparing the **search user** sub-section of the diagram.
* This issue is a sub-issue of #107.
* **Search user** part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as basis:

Use-Case Diagram:
<img width="636" alt="Ekran Resmi 2022-04-06 00 09 49" src="https://user-images.githubusercontent.com/68481602/161850277-d806b7b8-1e7f-4b37-ae0e-cda6337d0f0c.png">

Class Diagram:
<img width="518" alt="Ekran Resmi 2022-04-06 00 10 56" src="https://user-images.githubusercontent.com/68481602/161850287-14ce10cc-48eb-4331-83f5-722ab0abe160.png">

* The sequence diagram will be generated using the Lucidchart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After search user part of the sequence diagram is implemented, it will be merged into the main sequence diagram project provided in this [link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
* After completion, this issue will be reviewed and evaluated by the reviewed and other team members upon closing the issue.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Ezgi Aysel Batı - @ezgy 

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by xltvy** [comment]
## Info

* I have prepared the sequence diagram for the action of **Registered user searches a user**. It can be viewed through the link given in the issue description. Here is a screenshot of this initial version below:

<img width="548" alt="Ekran Resmi 2022-04-06 17 31 29" src="https://user-images.githubusercontent.com/68481602/162001545-cb27b74e-bdd7-4667-a93b-96cd9ecda663.png">

* It is now ready to be reviewed by @ezgy

**Comment by ezgy** [comment]
This diagram has been reviewed by the TA and by the team. It satisfies all the steps required and shows the process clearly. There are no changes to be made so this task is completed. Thank you for your work 🚀
