### ISSUE TITLE
Software Design: Sequence Diagram - Chat : sending a message

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#114]
### Issue Description

This is a subissue from #107 

As decided in our class diagram meeting, we need to create a sequence diagram for chat functionality which will contain sending a message between 2 users.
As the development of course class continues under #105, I will begin sequence diagram for chat feature in parallel.

You can view the created sequence diagram from [lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8)

### Deadline of the Issue

06.04.2022 - Wednesday - 11.00

### Reviewer

Bahrican Yesil

### Deadline for the Review

06.04.2022 - Wednesday - 16.00

**Comment by mbatuhancelik** [comment]
I created a prototype to be reviewed from @bahricanyesil. It is accessible from lucidchart link given above.

**Comment by bahricanyesil** [comment]
Thank you for your work @mbatuhancelik. I reviewed the work you did. Here are my comments:

1. Can you use alternative frames for success and error returns?
2. "Failed" seems an unclear return message, can you specify the fail reason too? For example for login case: "wrong password".
3. Can you use methods that we determinede in the class diagram design directly with their parameters defined there?
For example: login(username: string, password: string)
4. Activation box of the Chat is longer but I couldn't see any message or return message at the end of the activation box. Can you explain the reason why it's so?

**Comment by mbatuhancelik** [comment]
> 2. "Failed" seems an unclear return message, can you specify the fail reason too? For example for login case: "wrong password".

Sadly I have no idea what fail reason could be. I think we will find out what exceptions could be as development continues. For example, first one coming to mind is blocking users but we have no requirements regarding the subject. On the other hand, without fail messages, we cant see lifeline user and chatbox class, so I added those to fill in in later stages of the requirement.

I agree with other points, will make necessary changes.

**Comment by bahricanyesil** [comment]
> > 3\. "Failed" seems an unclear return message, can you specify the fail reason too? For example for login case: "wrong password".
> 
> Sadly I have no idea what fail reason could be. I think we will find out what exceptions could be as development continues. For example, first one coming to mind is blocking users but we have no requirements regarding the subject. On the other hand, without fail messages, we cant see lifeline user and chatbox class, so I added those to fill in in later stages of the requirement.
> 
> I agree with other points, will make necessary changes.

Thank you for the explanation. Then, we "may" write sth. like "request is failed, return/show an error message".

**Comment by mbatuhancelik** [comment]
I tried to change the diagram according to your instructions. Guess its ready for the second review @bahricanyesil

![image](https://user-images.githubusercontent.com/63948452/161962202-baded6bf-24d9-40b8-a022-c1ddfc140d27.png)

**Comment by bahricanyesil** [comment]
Thanks for the update @mbatuhancelik. It seems nice, thank you for the changes. The only thing I am not sure is whether the below frames are a valid representation or not.

**Comment by mbatuhancelik** [comment]
How is this?
![image](https://user-images.githubusercontent.com/63948452/161970615-ba88b092-7184-42b7-9929-8df0f350a87d.png)

**Comment by bahricanyesil** [comment]
Can you make the necessary changes according to the feedbacks we received in the PS hours @mbatuhancelik?

**Comment by mbatuhancelik** [comment]
I made the necessary changes both in the class and sequence diagrams, merged the final version of the diagram to the main lucidchart page and updated the link in the issue description accordingly.

Here is the final version of the seq. diagram:

![image](https://user-images.githubusercontent.com/63948452/162410692-270da73a-d9be-49aa-a27d-a0a69d1008dd.png)

**Comment by bahricanyesil** [comment]
@mbatuhancelik, I reviewed the work you did. Thank you for the changes.

I have a final note, it will be better if you can give a distinct name for each function. There are two different functions with two different parameters with the same name, for example: "forwardMessage". Even though they are in different classes, I guess it would be better to name them distinctly to avoid any unclear documentation problems.

**Comment by mbatuhancelik** [comment]
Usually you are right but in this case, both functions are used only for the same functionality, forwarding message from one chat engine to other, so I believe having dual meaning on forwardMessage term is helpful.

I guess this is the end of discussion, diagram is also reviewed in the meeting 6.1 and requested updates have been made.
