### ISSUE TITLE
Software Design: Sequence Diagram - Create Course

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#115]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. The sequence diagram will be completed with a collective effort and I will be preparing the create course sub-section of the diagram.

* This issue is a sub-issue of #107 .
* Create course part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as the basis.

### Use-Case Diagram
<img width="628" alt="image" src="https://user-images.githubusercontent.com/74256913/161875535-79caac14-0144-4ab8-a713-42d45fc795bd.png">

### Class Diagram
<img width="446" alt="image" src="https://user-images.githubusercontent.com/74256913/161875969-ebb0d325-19c9-4007-bfc1-b671a3b03918.png">

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram on our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Altay Acar

### Deadline for the Review

06.04.2022 - Wednesday - 16.00

**Comment by xltvy** [comment]
## Info

Thank you for your work! I have reviewed your sequence diagram related to course creation. There are few points I would like to mention:
* I think we may add a Course object between the Database and our Actor, Registered User.
* We may rename the course database to just database.
* Actor's Course() constructor call may connect to the Course object and if it is successfully created it may be saved to the database, if not a fail message can be sent to the actor by Course object.
* We may also change return arrows from solid lines to dashed lines as the convention suggests.
* Also the lifecycle of the objects starts from the first arrow and ends the last arrow, we may change those lifecycles in that way.

**Comment by hasancan-code** [comment]
Thanks for the review @xltvy. After we also discussed this sequence diagram in our meeting 6.1, we made some changes, and the last shape of the diagram can be shown below;
![image](https://user-images.githubusercontent.com/74256913/163163825-005fd159-22a0-443d-b549-dbcc6910d034.png)
