### ISSUE TITLE
Software Design: Sequence Diagram - Take Course

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#116]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. Sequence diagram will be completed with a collective effort and I will be preparing the **take course** sub-section of the diagram.
* This issue is a sub-issue of #107.
* **Take Course** part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as basis.

Use-Case Diagram
<img width="971" alt="Screen Shot 2022-04-06 at 07 57 17" src="https://user-images.githubusercontent.com/74325266/161898983-dabd5ed8-b4b9-4d16-9f74-1f7239d7d23e.png">

Class Diagram
<img width="532" alt="Screen Shot 2022-04-06 at 07 58 05" src="https://user-images.githubusercontent.com/74325266/161899007-a054d7f6-5e97-4418-a5c5-f6c693867734.png">

* The sequence diagram will be generated using the Lucidchart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After take course part of the sequence diagram is implemented, it will be merged into the main sequence diagram project provided in this [link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
* After completion, this issue will be reviewed and evaluated by the reviewed and other team members upon closing the issue.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by surmelienes1** [comment]
## Information 1

The details for the take course part of our sequence diagram can be seen below.

**Actor**: Registered User

**Preconditions**:
* S/he has already registered to the web app and has an account.
* S/he has logged in to the our web app.

**Actions**:
* S/he enrolls in a course.

***

## Information 2

I completed the take course part of the sequence diagram. You can access the diagram via [this link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8). It is now ready to be reviewed by @onurkomurcu.

You can see below the screenshot of the take course part of our sequence diagram:

<img width="1342" alt="Screen Shot 2022-04-07 at 07 45 23" src="https://user-images.githubusercontent.com/74325266/162122225-3b7d81d8-6533-4dce-9ddd-73dddca18c50.png">

**Comment by surmelienes1** [comment]
Taking into account the feedback given by all team members at the meeting we held on Tuesday, April 12, 2022. I updated the take course sequence diagram as in the comment above.

If you @onurkomurcu can see any part that needs to be changed or updated, can you add your thoughts as a comment?

**Comment by onurkomurcu** [comment]
As we discussed in meeting 6.1, can you provide first version of the diagram to record the progress? Addition to this, can you shorten the lifecycles? If you provide these requirements, you can close this issue. Thank you for your work.

**Comment by surmelienes1** [comment]
As @onurkomurcu mentioned, I added the first version of the take course sequence diagram back to my comment above. In addition, you can see the final version I created by shortening lifecycle bars and adding the course lecturer actor in the screenshot below: 

<img width="1215" alt="Screen Shot 2022-04-13 at 22 18 49" src="https://user-images.githubusercontent.com/74325266/163254130-f73bf63b-df25-4aab-919f-92d822b34747.png">



I will now close this issue since I don't have anything to further add, if you have any questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
