### ISSUE TITLE
Software Design: Sequence Diagram - Take Note

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#117]
### Issue Description

Since the use case and class diagrams have been prepared, the design process will continue with the sequence diagrams. In order to contribute to the sequence diagram collaboratively, the team has decided to distribute actions between all members. The distribution of diagrams can be viewed under main issue #107.
 

This issue corresponds to note-taking actions in the diagram.

### Step Details

Steps that will be performed:
- [x] Review relevant parts in the use-case diagram
- [x] Review relevant parts in the class diagram
- [x] define the objects and interactions in timeline order
- [x] Create the diagram on our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

### Final Actions

The sequence diagram will be generated using the Lucidchart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).

### Deadline of the Issue

06.04.2022 - 10.00

### Reviewer

Egemen Atik

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by ezgy** [comment]
The related part in the use case diagram can be seen below:
![image](https://user-images.githubusercontent.com/56553280/161902475-9601e0b1-4836-4d77-b40a-86b4d88772d0.png)

The related part in the class diagram is as follows:
![image](https://user-images.githubusercontent.com/56553280/161902541-e441850f-d333-493a-9f02-175540d348b6.png)

I will be creating the sequence diagram in accordance to actions defined in the above diagrams.

**Comment by ezgy** [comment]
initial design for this sequence diagram is as follows: 
![image](https://user-images.githubusercontent.com/56553280/163033618-d2057c9e-c465-4b5e-b81a-94b85e65ac1c.png)

ready for review @egemenatikk

**Comment by egemenatikk** [comment]
Thank you for your work, @ezgy. I think overall look of this sequence diagram is good enough, I can suggest a few things, though.

As our T.A. told us in the last PS session, I think we should avoid UI-related return values, so maybe we can remove return Note page and return error page.

Another thing I can suggest is that we can use our Enrollment class here. Every course is connected to a user via Enrollment class, so we can connect Course and Note by using Enrollment class.

**Comment by ezgy** [comment]
Thank you for your feedback. I've added Enrollment class as an intermediate and also edited the return messages as you've suggested @egemenatikk . Here is the final verison of this diagram: 
![image](https://user-images.githubusercontent.com/56553280/163472917-0ec277e7-8c14-4021-8d2d-ccd6a45129d9.png)

If you approve the changes I can close this issue and also #107

**Comment by onurkomurcu** [comment]
I'm closing this issue. Thank you for your work @ezgy .
