### ISSUE TITLE
Software Design: Sequence Diagram - Annotate

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#118]
### Issue Description

We were started to make sequence diagrams. I will make a sequence diagram which is related to **annotation**. 

* This issue is a **sub-issue** of https://github.com/bounswe/bounswe2022group2/issues/107.
* Sequence diagram is a collective work. This is only one portion of it.
* Following diagrams will be considered during work.
* Progress can be observed through [**Lucidchart**](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).

Use Case Diagram:
![Ekran Resmi 2022-04-06 09 10 58](https://user-images.githubusercontent.com/92719802/161907205-d0b67a46-e1a9-4a1d-8324-ec79b261d33a.png)

Class Diagram:
![Ekran Resmi 2022-04-06 09 11 18](https://user-images.githubusercontent.com/92719802/161907247-3ea1251c-f130-49c9-90f9-754889914cf8.png)

### Step Details

Steps that will be performed:
- [x] **Analyze** annotation related diagrams which are provided above.
- [x] **Research** about how to implement sequence diagram.
- [x] **Create** the diagram in [**Lucidchart**](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).
- [x] **Provide** screenshot of the work.

### Final Actions

After the work is done, it will be merged with our teammates' works.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by onurkomurcu** [comment]
I select the create action for the annotation sequence diagram. It is ready to be reviewed now.

![Ekran Resmi 2022-04-12 19 39 19](https://user-images.githubusercontent.com/92719802/163012104-86d1a052-23c6-433a-b359-7110d5ad65cf.png)

**Comment by ezgy** [comment]
Thank you for your work, @onurkomurcu.  I have a few suggestions to improve this diagram:
- instead of directly adding the created object to the DB, the diagram can include the Annotation class and the connection through the Enrollment class. 
- once there are multiple classes communicating, you should also consider that return/reply messages are generally represented with dashed lines.

**Comment by xltvy** [comment]
Closed #118
