### ISSUE TITLE
Software Design : Sequence Diagram - Edit Course

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#119]
### Issue Description

We were started to make sequence diagrams. I will make a sequence diagram which is related to **edit course**. 

* This issue is a **sub-issue** of https://github.com/bounswe/bounswe2022group2/issues/107.
* Sequence diagram is a collective work. This is only one portion of it.
* Following diagrams will be considered during work.
* Progress can be observed through [**Lucidchart**](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).

Use Case Diagram:
There is no specification about editing course in the use case diagram.

Class Diagram:
![Ekran Resmi 2022-04-06 09 27 53](https://user-images.githubusercontent.com/92719802/161909531-a9fcf5cb-92bd-43fd-a1c7-53ad29c512ba.png)

### Step Details

Steps that will be performed:
- [x] **Analyze** annotation related diagrams which are provided above.
- [x] **Research** about how to implement sequence diagram.
- [x] **Create** the diagram in [**Lucidchart**](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#).
- [x] **Provide** screenshot of the work.

### Final Actions

After the work is done, it will be merged with our teammates' works.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by ezgy** [comment]
I have a few structural improvement suggestions @onurkomurcu 
- reply messages should be represented with dashed lines
- lifecycle of objects should start just before the first interaction and end with the last return
- you can also consider including the Course class to better represent the parts included in this sequence.

Thank you for your work 🥳

**Comment by onurkomurcu** [comment]
I have changed the diagram with respect to your suggestions. If you think there is no need to change anything, you can close this issue. Thank you for your review.

<img width="1143" alt="Ekran Resmi 2022-04-13 17 33 40" src="https://user-images.githubusercontent.com/92719802/163204335-2d90c11a-484a-4f81-bd7f-da80809ca616.png">
