### ISSUE TITLE
Software Design: Sequence Diagram - Create Event

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#121]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. The sequence diagram will be completed with a collective effort and I will be preparing the Create Event sub-section of the diagram.

* This issue is a sub-issue of #107  .
* Create Event part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as the basis.

### Use-Case Diagram
<img width=auto alt="image" alt="event_use_case" src="https://user-images.githubusercontent.com/100771925/161973576-a1c9b03f-c25f-4321-a8b8-d3550ec1e2b6.png">

### Class Diagram
<img width=auto alt="image" alt="event_class" src="https://user-images.githubusercontent.com/100771925/161973738-d6c4bce1-4623-4d70-9594-97b749a2fece.png">

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram on our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After Create Event part of the sequence diagram is implemented, it will be merged into the main sequence diagram project provided in this [link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
* After completion, this issue will be reviewed and evaluated by the reviewer and other team members upon closing the issue.

### Deadline of the Issue

06.04.2022 - Wednesday - 10.00

### Reviewer

Ecenur Sezer

### Deadline for the Review

06.04.2022 - Wednesday - 11.00

**Comment by egemenatikk** [comment]
I have created a sequence diagram for Create Event action. You can find it in our [Lucidchart page](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#). I am also adding a screenshot of it: 

![create_event_sequence](https://user-images.githubusercontent.com/100771925/162137991-b14e84b8-5cbb-470a-ab5f-8e36a4ba1850.png)

It is ready to be reviewed, if you think anything is missing or wrong, please let me know.

**Comment by egemenatikk** [comment]
I made some changes in Create Event part of sequence diagram according to feedbacks from my teammates in our last meeting. Here is the final form of it:

![createEvent](https://user-images.githubusercontent.com/100771925/163147962-54fa14e1-3d0b-466b-97e4-a974b7d5b692.png)

**Comment by bahricanyesil** [comment]
@egemenatikk I reviewed the work you did. Can you check the timelines of the arrows in the "If event creator is eligible..." part? I see that some right arrows are on top of the left arrows and some of them are in the same horizontal line. Can you review the timelines and make necessary updates if any according to the sequence flow.

**Comment by egemenatikk** [comment]
@bahricanyesil I tried to correct the diagram according to what you suggested. Here is the updated version screenshot:
Is it better now or should I change it further?

![createEvent](https://user-images.githubusercontent.com/100771925/163165917-b099d6f6-a957-43c0-9225-02307a8e1b9d.png)

**Comment by codingAku** [comment]
Hello Egemen. As I see according to our meetings, your lifecycle blocks are long. They should end in the last arrow in the horizontal lines. After that, we can close the issue.

**Comment by bahricanyesil** [comment]
> @bahricanyesil I tried to correct the diagram according to what you suggested. Here is the updated version screenshot: Is it better now or should I change it further?
> 
> ![createEvent](https://user-images.githubusercontent.com/100771925/163165917-b099d6f6-a957-43c0-9225-02307a8e1b9d.png)

For the timeline related things, I couldn't see a problem. Thank you for the changes.

**Comment by xltvy** [comment]
Closed #121

**Comment by egemenatikk** [comment]
According to reviews by group members and our T.A. Egemen İşgüder, all diagrams are good enough, so we can close this issue.
