### ISSUE TITLE
Software Design: Sequence Diagram - Join Event

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#122]
### Issue Description

As the next part of the software design process, we will provide a sequence diagram for our project moving from the class and use-case diagram phases. The sequence diagram will be completed with a collective effort and I will be preparing the Join Event sub-section of the diagram.

* This issue is a sub-issue of #107  .
* Join Event part of the sequence diagram will be formed, using the following sections of the use-case and class diagram as the basis.

### Use-Case Diagram
<img width=auto alt="image" alt="event_use_case" src="https://user-images.githubusercontent.com/100771925/161973576-a1c9b03f-c25f-4321-a8b8-d3550ec1e2b6.png">

### Class Diagram
<img width=auto alt="image" alt="event_class" src="https://user-images.githubusercontent.com/100771925/161973738-d6c4bce1-4623-4d70-9594-97b749a2fece.png">

### Class Diagram
<img width=auto alt="image" alt="participant_class" src="https://user-images.githubusercontent.com/100771925/161974696-cad2f595-5521-49df-9fa0-f96a549c39c9.png">

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram.
- [x] Check the corresponding parts of the class diagram.
- [x] Create the diagram on our project page in [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After Join Event part of the sequence diagram is implemented, it will be merged into the main sequence diagram project provided in this [link](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8).
* After completion, this issue will be reviewed and evaluated by the reviewer and other team members upon closing the issue.

### Deadline of the Issue

06.04.2022 - Wednesday - 10:00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

06.04.2022 - Wednesday - 11:00

**Comment by egemenatikk** [comment]
I have created a sequence diagram for Join Event action. You can find it in our [Lucidchart page](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8&page=0_0#). I am also adding a screenshot of it: 

![join_event_sequence](https://user-images.githubusercontent.com/100771925/162138475-3bb63ffa-f832-43ea-b9cb-b3bf04d50134.png)

It is ready to be reviewed, if you think anything is missing or wrong, please let me know.

**Comment by surmelienes1** [comment]
There are two aspects for which I have a question in mind:

1) When the participant capacity is full, if a new user wants to join the event, should s/he be prevented from participating in the event or can s/he be included in the event by the lecturer or the course admin upon request? I think we should discuss this case in our upcoming meeting with other team members to ensure the consistency across diagram parts.

2) I am not entirely sure if it is necessary to do this, but for an outsider to better understand the context of your conditionals, you could appropriately rename the alternative framework, i.e., "Capacity Check".

Other than these it looks very good, thank you @egemenatikk for your valuable contributions.

**Comment by egemenatikk** [comment]
I made some changes according to decisions we took in our 6th meeting. Here is the updated version of Join Event part of sequence diagram:


![joinevent](https://user-images.githubusercontent.com/100771925/163043023-03cb031a-6d2a-4eb0-8b62-542f27dd5a3b.png)

**Comment by surmelienes1** [comment]
It seems very good and complete, thank you @egemenatikk for your contributions.

Since we discussed the aspects I mentioned in my comment above with all the team members at the meeting we held on April 12 and reached a consensus, it seems that there is nothing left to be done.

I will now close this issue since I don't have anything to further add, if you have any questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
