### ISSUE TITLE
Editing Use-Case Diagram According to the Feedback

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#124]
### Issue Description

In the third customer meeting at 06.04.2022, we have gone over our UML diagrams. For the use-case diagram there were some minor issues. I categorized those in two categories: general and specific issues.

General Issues:
- [x] As nodes of the diagram we should use actions, not class names. - @xltvy 
- [x] Instead of using \<includes>opt. we should use \<extends> for the optional cases. @bahricanyesil 
- [x] When using <extends> link between the nodes the direction of arrow is from child to parent. - @xltvy 

Specific Issues:
- [x] For browsing we should use includes, not extends. - @xltvy 
- [x] Enroll-review course should be extends, not includes. @bahricanyesil 
- [x] We should remove check completion percentage. @bahricanyesil 
- [x] When creating a course setting privacy options should be includes. - @xltvy 
- [x] For admins, giving a reason for their actions should be includes. - @xltvy 

These issues are subject to change. There may be more issues to be added or removed from those above lists.

### Step Details

Steps that will be performed:
- [x] Specific issues will be resolved.
- [x] General issues will be resolved.
- [x] Use-case diagram will be finalized.

### Final Actions

After each issue related to the use-case diagrams is resolved, use-case diagram will be finalized and added to the according page in our wiki.

### Deadline of the Issue

12.04.2022 - Tuesday - 22.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

12.04.2022 - Tuesday - 23.59

**Comment by xltvy** [comment]
## Info
I have edited course creation part of the use-case diagram according to the feedback given and also corrected some wrong directed extends arrows throughout the whole diagram

**Comment by bahricanyesil** [comment]
## Info

- I changed the relation between enrolling a course and reviewing it to "extends" instead of "includes" since it is optional.
- I removed the "Check completion percentage" node from the reviewing a course part as we discussed in the PS.
- I checked the "<includes>opt." relations over the whole graph and changed the encountered ones with "<extends>" keyword.

**Comment by xltvy** [comment]
## Info
I have revised the remaining parts of the use-case diagram and resolved remaining specific and general issues. Now, use-case diagram is finalized and is ready to be added to the relevant wiki page.
