### ISSUE TITLE
8.6. Filling RAM (Responsibility Assignment Matrix)

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#129]
RAM is created under #123 and its ready for people to fill their responsibilities. This issue is created to track this process. 
You can edit the RAM from [here](https://docs.google.com/spreadsheets/d/1snznWp1hqTykJNHQT01oZ3V-j5Ejx8W2CwYlnXXIs-k/edit?usp=sharing).

Please fill your columns, if you think some responsibility is missing, you shall add it to the matrix but please leave a comment under #123 so that we can track the process.

Please tick your name here after your column is done:
- [x] @xltvy 
- [x] @egemenatikk 
- [x] @ezgy 
- [x] @mbatuhancelik 
- [x] @hasancan-code 
- [x] @onurkomurcu 
- [ ] @ahmet633 
- [x] @codingAku 
- [x] @surmelienes1 
- [x] @bahricanyesil 

Deadline:
13.03.2022 17:00

**Comment by xltvy** [comment]
## Info
I have filled my part of the RAM. It can be seen from the link given in the issue description.

**Comment by egemenatikk** [comment]
## Info
I have filled my part of the RAM. It can be seen from the link given in the issue description.

**Comment by codingAku** [comment]
I have filled my part of RAM. It can be seen from our link of RAM in the issue description.

**Comment by surmelienes1** [comment]
## Info
I have completed my part of the RAM table. The details are available via the link provided in the issue description above.

**Comment by ezgy** [comment]
I have filled my sections of the RAM, as can be seen in the link in the issue description above.

**Comment by onurkomurcu** [comment]
I have filled my sections of the RAM. It can be seen from the provided link in the issue description. If you have any question about any part of the fillings, let me know.

**Comment by mbatuhancelik** [comment]
Everyone filled their columns in ram, adding the table to the milestone report now.
