### ISSUE TITLE
Practice App: Research on Useful APIs

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#147]
### Issue Description

As we have determined in issue #146 as a task, we should research APIs that we can benefit from while we're developing our own API. I took the responsibility for this task and I will be finding some public/free APIs that we can integrate into our app.

### Step Details

Find free and public APIs under the topics that we can relate to our app.

Related topics:
- [x] Weather Forecast --> To estimate the weather while creating/attending an event
- [x] Motivational and Inspirational Quotes --> To motivate the learners in their progress of a lesson
- [x] Class-Online Meeting Management --> While creating online meetings outside of the app, to make organized them

Actions:
- [x] Find free and public helpful APIs about the topics mentioned above
- [x] Share their documentation and related links

### Final Actions

We will talk about my research results and the APIs I found in our regular weekly meeting. We will most probably choose 1 or 2 of them to integrate into the API we will develop.

### Deadline of the Issue

26.04.2022 - 23:59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

27.04.2022 - 23:59

**Comment by bahricanyesil** [comment]
## Info

I found a GitHub repository that contains a collective list of free APIs. We can read them and choose the ones that may be useful for us. All team members can state the ones that s/he like under this issue as comments. Here's the corresponding repository:

https://github.com/public-apis/public-apis

**Comment by bahricanyesil** [comment]
## Info

I researched some free APIs to get the weather forecast info. Giving weather information to the users can be useful, especially while organizing/attending events.

Here are the ones I analyzed and selected:
1. AccuWeather --> [API Reference](https://developer.accuweather.com/apis)
2. OpenWeather --> [Documentation](https://openweathermap.org/api)
3. WeatherAPI --> [Documentation](https://www.weatherapi.com/docs/)

**Comment by bahricanyesil** [comment]
## Info

I researched some free APIs to get motivational quotes. Showing motivational quotes to the users can be useful, especially to encourage their progress in lessons.

Here are the ones I analyzed and selected:
1. FavQs --> [API Documentation](https://favqs.com/api)
2. Inspiration --> [Documentation](https://api.goprogram.ai/inspiration/docs/)
3. Quotable --> [GitHub Repo](https://github.com/lukePeavey/quotable)

**Comment by bahricanyesil** [comment]
## Info

I researched some free APIs to organize online meetings.

I analyzed some APIs but only chose the API of Zoom for now:
1. Zoom API --> [API Reference](https://marketplace.zoom.us/docs/api-reference/introduction)

**Comment by bahricanyesil** [comment]
## Info

I researched a list of collective APIs, scanned them, and choose the appropriate topics that can be useful in our app. After that, I chose my favorites and stated them as comments.

Now, the results of the issue are ready to be reviewed specificially by @mbatuhancelik and all other team members.

**Comment by mbatuhancelik** [comment]
Seems reasonable to me. 
I believe going over selection process in the meeting will be beneficial for all to be on the same page. So, leaving issue open for now.

**Comment by bahricanyesil** [comment]
We went over all of the results mentioned in this issue in our [weekly meeting 9](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)). We reviewed them, we extracted the APIs that we will use in our project after a discussion within the team.

Therefore, I am closing the issue. You can see the discussion details and action items in the weekly meeting I gave the link above.
