### ISSUE TITLE
Documenting Meeting Notes - Meeting 9

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#148]
### Issue Description

- Notes taken during the second meeting on 01/05/2022 should be documented on the wiki page.
- These notes should follow the criteria on the [Meeting Notes template](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-Notes-Template). The template contains the details about the sections that should be in the meeting notes.
- Meetings notes should be linked in the required places.

### Step Details

Meeting notes should contain the following sections:

- [x] Details
- [x] Agenda
- [x] Discussion
- [x] Action Items

### Final Actions

Sections that should have a link to the week 9 meeting notes:

- [x] [Home wiki page](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes)
- [x] [Sidebar](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes)

### Deadline of the Issue

04.05.2022 - Wednesday - 23:59

### Reviewer

Egemen Atik

### Deadline for the Review

06.05.2022 - Friday - 23:59

**Comment by bahricanyesil** [comment]
## INFO

I created a separate wiki page for the week 9 meeting notes. You can view it [here](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)).

I also linked it in the [home wiki page and sidebar](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes). If you have anything further, you can reopen the issue and add your comment.

**Comment by bahricanyesil** [comment]
All to-dos are completed and the issue is now ready to be reviewed by @egemenatikk.

**Comment by egemenatikk** [comment]
All necessary notes are available in the [Meeting Notes 9](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)). Thank you for your work @bahricanyesil. I am closing this issue since there are no more work needed left.
