### ISSUE TITLE
Practice App: Implementing the POST method for dropping lesson, lesson drop endpoint

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#174]
### Issue Description

We determined the endpoints to be included in the practice app project in our [weekly meeting-9](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)).

After the determination of the complete list, we divided the tasks within the team. I took the responsibility for the implementation of a POST method for dropping lesson. To be able to implement the signup endpoint, we need User and Lesson models.

### Step Details

Steps that will be performed:
- [x] Check whether the incoming data is valid
- [x] Check whether the user and lesson exists
- [x] Check whether the user takes the lesson
- [x] Remove the lesson from user's enrollment list and return the user and lesson with a success message
- [x] Return an error message if an error occurs in any of the previous steps
- [x] Test the endpoint with Postman
- [x] Save requests as a collection in Postman
- [x] Document the endpoint

### Final Actions

After I created the drop lesson endpoint, I will test it by using Postman. While testing, I will save my successful and failed requests and I will create a collection in Postman. I will also give the link to the collection under this as a comment to enable anyone to test the endpoint. Finally, I will document the endpoint and will share the documentation as a comment under this issue to add it to the corresponding wiki page in the future.

### Deadline of the Issue

15.05.2022 - Sunday - 23:59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

16.05.2022 - Monday - 23:59

**Comment by egemenatikk** [comment]
I added an additional field to User model created in issue #151: enrolledLessons. It is an array consists of ObjectIds, these ObjectIds also references Lesson Collection.

**Comment by egemenatikk** [comment]
## Info
* I checked the all required fields in the incoming data (user_id, lesson_id).
* I checked whether given ids are valid or not.
* I controlled whether a user with the given user_id and a lesson with the given lesson_id exists or not.
* I controlled whether a user with the given user_id takes the lesson with the given id or not.
* I tested the endpoint with Postman, saved the requests, and created a collection.
[Here's the link to the documentation](https://documenter.getpostman.com/view/17951279/UyxjFRYY).

**Comment by egemenatikk** [comment]
## Handwritten Documentation

- **Endpoint:** /user/enrolled/drop
- **Definition:** Users will drop lessons they want with their user ids and lesson ids. 
- **Query Parameters:** None
- **Body Data:** user_id: ObjectId, lesson_id: ObjectId and all of them are required
- **Example request body:** {
      "user_id": "6280e289fed5174e18c40848",
      "lesson_id": "62800034ba1d9c19fee948e3"
  }
- **Example response body:** {
      "resultMessage": "Lesson is successfully dropped.",
           "user": {
                 "email": "email1",
                 "name": "name1",
                 "enrolledLessons": [
                      "627fc0d6ba1d9c19fee948c3",
                      "627fc0f4ba1d9c19fee948c4"
                 ],
                 "updatedAt": "2022-05-15T11:26:10.274Z",
                 "id": "6280e289fed5174e18c40848"
           },
           "lesson": {
                 "name": "lesson4",
                 "category_id": "62800034ba1d9c19fee948e3",
                 "id": "62800034ba1d9c19fee948e3"
           }
  }

[Postman Documentation](https://documenter.getpostman.com/view/17951279/UyxjFRYY)

**Comment by egemenatikk** [comment]
I completed all of the steps mentioned in the issue description. I opened a pull request and requested reviews of @mbatuhancelik

**Comment by mbatuhancelik** [comment]
Reviewed the implementation under #178
