### ISSUE TITLE
Practice App: Implementing POST Login Endpoint

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#176]
### Issue Description

The endpoints are determined on our [Weekly Meeting #9 ](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)). I will be implementing the login endpoint. 

### Step Details

Steps that will be performed:
- [x]  Check whether the incoming data is valid
- [x] Check whether the user is already exists.
- [x] If user doesn't exist, return an error message.
- [x] If user exists, check whether the password is correct.
- [x] If the password is wrong, return an error message.
- [x] If the password is true, redirect the user to home page.
- [x] Test the endpoint with Postman
- [x] Save requests as a collection in Postman.
- [x] Document the endpoint.
- [x] Provide corresponding results here.

### Final Actions

When the login endpoint is done, it will be tested by using Postman. The results will be added here.

### Deadline of the Issue

16.05.2022 - 23.59

### Reviewer

Bahrican Yesil

### Deadline for the Review

17.05.2022 - 23.59

**Comment by onurkomurcu** [comment]
I have implemented the relevant sections. I have tested most test cases using with Postman. One success and one failure test cases can be observed [here](https://documenter.getpostman.com/view/21002333/UyxkkRek). Also, code itself can be seen from the [PR](https://github.com/bounswe/bounswe2022group2/pull/208). If you have any suggestion and question, please let me know.

**Comment by onurkomurcu** [comment]
## Handwritten Documentation

- **Endpoint:** /user/login
- **Definition:** Users will login into the system with their email and password.
- **Query Parameters:** None
- **Body Data:** email: string, password: string. All of them are required
- **Example request body:** 
{
    "email": "example@example.com",
    "password": "12345678"
}
- **Example response body:**
{
    "resultMessage": "Successfully logged in.",
    "user": {
        "email": "example@example.com",
        "name": "example",
        "createdAt": "2022-05-17T18:47:14.458Z",
        "updatedAt": "2022-05-17T18:47:14.458Z",
        "id": "6283edb24da593a8186f5960"
    }
}

[Postman Documentation](will be added...)

**Comment by bahricanyesil** [comment]
I reviewed the work you did and commented the necessary points in the PR #208.
