### ISSUE TITLE
Identifying Profile Page Requirements under User Requirements

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#19]
## Description

- Profile page requirements for both types of users (students and teachers) will be identified under the title of User Requirements as a part of the Functional Requirements for this project.
- It will include the details for but not limited to
   * Profile page creation for students
   * Profile page creation for teachers
   * Profile page edit for students
   * Profile page edit for teachers
   * Experience tracking
   * Achievements and badges
- This issue is a sub-issue of #16 . It will be linked there to easily access but specific details will be under this issue.
- After the initial phase for the profile page requirements is finished, this issue will be closed and reviewing process will continue under the main issue mentioned above.

**Deadline:** 13.03.2022 - Sunday - 20:00
**Reviewer:** Will be reviewed under the main issue after all user requirements are specified.

**Comment by xltvy** [comment]
## Update

- Profile page section of the user requirements as part of the functional requirements are added to the [Requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) of the Wiki.
- It includes the following sub-sections:
   * Student Profile Page
      * Interests and Knowledge
      * Progress Tracking
      * Achievements
   * Educator Profile Page
      * Interests and Knowledge
      * Reputation
      * Recommendations
   * Guest Users

**Comment by xltvy** [comment]
## Info:
Issue is reopened to update profile page requirements for users. There is a structural change in the profile system of the application comparing to the first draft.

This update will include:
* Merging the profile types of the lecturer and learner profiles. There will be one type of user and lecturer and learner profiles will be sub-sections of the profile page.
* The passive voice used to describe requirements will be updated as more like a user interaction description.
* For simplicity some requirement clauses will be merged into one.

After this first update for the profile page requirements is finished, this issue will be closed again and reviewed under the main issue mentioned above.

**Comment by xltvy** [comment]
## Info:
Profile page requirements from the user requirements under the section of functional requirements have been updated.

**Comment by ezgy** [comment]
I have reviewed the changes you made. The new structure provided is good and easily understandable. 

Here are some small suggestions:
* 1.1.2.5. is a system requirement. It should either be reworded as a user requirement or moved under system requirements.
* 1.1.2.11.1.3. can be confusing without viewing [this mockup](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng) since enrolling to courses is a "learner" action.  As far as I understand this requirement specifies that other users can enroll to courses provided by lecturer user on the lecturer user's profile page, so maybe it can be more detailed to avoid confusion.

Overall the changes made reflect what was discussed and provide a better structure. Thank you for your work.  You can close this issue 🎉

**Comment by xltvy** [comment]
> I have reviewed the changes you made. The new structure provided is good and easily understandable.
> 
> Here are some small suggestions:
> 
> * 1.1.2.5. is a system requirement. It should either be reworded as a user requirement or moved under system requirements.
> * 1.1.2.11.1.3. can be confusing without viewing [this mockup](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng) since enrolling to courses is a "learner" action.  As far as I understand this requirement specifies that other users can enroll to courses provided by lecturer user on the lecturer user's profile page, so maybe it can be more detailed to avoid confusion.
> 
> Overall the changes made reflect what was discussed and provide a better structure. Thank you for your work. You can close this issue 🎉

Thank you for your review, I have removed "1.1.2.5. A default avatar shall be assigned to the profile pages to be displayed." according to your suggestion and we can further add it to a relevant system requirements section.

For the 1.1.2.11.1.3. case, yes it was made to provide accountability with the mockup we have prepared for [this scenario](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng). After your point I reviewed it and understood why it is confusing. So, I added a bit clarification to the requirement description. If it is still not clear we can discuss it further.
