### ISSUE TITLE
Research on W3 Web Annotation Data Model

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#20]
## Description

Annotations are commonly used to provide information about a resource or to link resources together. A remark or tag on a single web page or image, or a blog entry on a news piece can be considered as examples about this topic. Annotations will be a pivoting part of this project and they will comply with the W3C Web Annotation Data Model and follow W3C standards. Thus, an initial research on this very topic will be done. Everyone in the group will do research on the topic and the findings will be gathered and summarized by me @xltvy .

Results of each individual research are collected on our Discord channel and the checklist for each member of the group according their tasks is given below:
- [x] [Ahmet Yiğit Özdoğan](@ahmet633)
- [x] [Altay Acar](@xltvy)
- [x] [Bahrican Yeşil](@bahricanyesil)
- [x] [Egemen Atik](@egemenatikk)
- [x] [Ecenur Sezer](@codingAku)
- [x] [Ezgi Aysel Batı](@ezgy)
- [ ] [Hasan Can Erol](@hasancan-code)
- [x] [Mehmet Batuhan Çelik](@mbatuhancelik)
- [x] [Muhammed Enes Sürmeli](@surmelienes1)
- [x] [Onur Kömürcü](@onurkomurcu)

After each initial research is done and the findings are gathered on our Discord channel, I (@xltvy ) will summarize them and create a separate wiki page for the research on W3C Web Annotation Data Model.

**Deadline for research: 13.03.2022 - Sunday - 20:00**
**Deadline for documentation: 14.03.2022 - Monday - 23:59**

**Comment by xltvy** [comment]
INFO:
I have made research on W3 Web Annotation Model and W3C standards on web annotations.

I focused on the following aspects of W3 Web Annotation Model and shared the findings of my research on our Discord channel:
1 - What is annotation?
2 - What is W3 Web Annotation Model?
3 - What are the most used terminology to define the industry standard for web annotations?

**Comment by bahricanyesil** [comment]
INFO:
I have completed my research on W3 Web Annotation Model and its standards.

I mainly tried to focus on some different aspects of it instead of the model itself or the terminology of it since other friends have already completed researches about those parts. I shared my research results in detail on our Discord channel. Altay will document them on a wiki page.

Here's the titles I focused on:
1- What's before the W3 Web Annotation Model?
2- What exactly does W3 Web Annotation Model mean for us (normal users)?
3- What are its differences from the others? (like Adobe PDF reader, kinder, etc.)
4- Real-life example, interactive web-site, and a quote from the co-chairs.

**Comment by codingAku** [comment]
INFO:

My research on W3 Web Annotation Model is completed and it gives answers to the following topics:
1-For what purposes W3 Web Annotation model can be used?
2What are the basic data structures of W3 Web Annotation?

Related research notes can be found on our Discord meeting-notes channel.

**Comment by mbatuhancelik** [comment]
INFO:
I completed my research consisting of following topics:

- What is W3C?
- What is annotating?
- Purpose of the annotation model?
- Method of the annotation model?

Research report can be found in discord channel.

**Comment by onurkomurcu** [comment]
INFO:
I completed my research on W3 Web Annotation Model. General aim of the model can be found in our discord channel.

**Comment by ezgy** [comment]
INFO: I contributed to research on W3 Web annotation, particularly focusing on the main aim of the model, Selectors and common use ways of the model and how it can relate to our purposes.

**Comment by surmelienes1** [comment]
INFO:
I have completed my research on W3 Web Annotation Model and its standards.

I shared my research results in detail on our Discord channel

You can see below the titles I focused on:
1- W3C Web Annotation Data Model
2- W3C Standards
3- What are the tools available to implement Web Annotation?
4- What are the challenges ahead for Web Annotation?

**Comment by egemenatikk** [comment]
INFO:
I have completed my research on W3 Web Annotation Model and its standards.

I shared my research results in detail on our Discord channel.

You can see below the titles I focused on:
1- W3C Web Annotation Data Model
2- W3C Principles
3- A number of examples

**Comment by ahmet633** [comment]
INFO:
I have completed my research on W3 Web Annotation Model. The result is a short introduction to Web Annotation Model.

I shared the result on our Discord server.

**Comment by xltvy** [comment]
* With the help of the research results obtained through collaborative efforts from all the team members, I have finalized the page for W3C Web Annotation Data Model.
The W3C Web Annotation Data Model page can be found in [here](https://github.com/bounswe/bounswe2022group2/wiki/W3-Web-Annotation-Data-Model).
