### ISSUE TITLE
Adding glossary to requirements page

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#24]
## Description

We should be on the same page with people who check our requirements page. In order to accomplish that, we need to define the terms we used, briefly.

List of terms may be enhanced/enlarged and new terms can be added in the future. If you can find, you can write them as a  comment to this issue.

According to our decision in meeting-2, responsible people for the **glossary** are:
- [x] @ahmet633 
- [x] @egemenatikk - [Glossary](https://github.com/bounswe/bounswe2022group2/wiki/Requirements#glossary)

These people will create separate issue for the sublist they work and will link those issues under this main issue with a summary comment. We will manage all glossary related things here with the help of hyperlinks, comments and so on.

There is a one reviewer for this issue and she will review what the assignees found, what others are commented at the end and will make the last sentences before closing the issue to be sure that everything works well.

**Deadline: 13.03.2022 - Sunday - 20:00**
**Reviewer: @codingAku** - Deadline: 14.03.2022 - Monday - 23:59

**Comment by egemenatikk** [comment]
INFO:
I will be adding a list of words including words which starts with letters between (including) A and M.
A separate issue is created for this purpose. You can view it in issue #35 .
Now, this issue depends on that sub-issue to be reviewed and closed.

**Comment by ahmet633** [comment]
I have added some words to the glossary. Related sub-issue can be found at #36 . This issue needs to be reviewed by @codingAku now.

**Comment by codingAku** [comment]
The words on the glossary seem to support our discussions. Thank you to those who contributed. Issue closed.
