### ISSUE TITLE
Practice App: Writing the Unit Tests of the Filtering Categories by Name

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#249]
### Issue Description

We determined the endpoints to be included in the practice app project in our [weekly meeting-9](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)).

After the determination of the complete list, we divided the tasks within the team. I took responsibility for filtering categories by name. After the implementation with the issue https://github.com/bounswe/bounswe2022group2/issues/227, I will write the unit tests of this endpoint.

### Step Details

Steps that will be performed:
- [x] Determine the steps to test
- [x] Create the base test files
- [x] Write unit tests for the determined steps

### Deadline of the Issue

19.05.2022 - Thursday - 15.00

### Reviewer

Batuhan Çelik

### Deadline for the Review

19.05.2022 - Thursday - 23:59

**Comment by onurkomurcu** [comment]
Closed.
