### ISSUE TITLE
Research on Semantic Search 

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#25]
## Description

When developing a project that includes a lot of data within, how concepts such as browsing and searching are handled become more important. As the amount of data in a project increases, how this data is displayed and accessed should be planned accordingly.  
This project, Online Learning Platform, will include a lot of data - courses, teachers, notes...-  that needs to be easily findable and accessible. Thus it is crucial that we understand the details of Semantic Search and all it requires. Because of this, some research regarding the topic needs to be done. 

All members should contribute to research about semantic search. Research findings and sources are to be submitted on the Discord channel under the Semantic Search thread. 

The deadline for contributing research is **13.03.2022 - Sunday - 20:00** Please add a tick in the checklist once you have contributed to the research:
- [x] [Ahmet Yiğit Özdoğan](@ahmet633)
- [x] [Altay Acar](@xltvy)
- [x] [Bahrican Yeşil](@bahricanyesil)
- [x] [Egemen Atik](@egemenatikk)
- [x] [Ecenur Sezer](@codingAku)
- [ ] [Ezgi Aysel Batı](@ezgy)
- [ ] [Hasan Can Erol](@hasancan-code)
- [x] [Mehmet Batuhan Çelik](@mbatuhancelik)
- [x] [Muhammed Enes Sürmeli](@surmelienes1)
- [x] [Onur Kömürcü](@onurkomurcu)

Once the initial research period is done and the findings are gathered on our Discord channel, this issue will be closed and the findings will be summarized on the wiki as a separate page under the research on Semantic Search. Documentation of the research on the wiki is my (@ezgy) responsibility. the relevant issue can be found here:  #26 

**Deadline for documentation: 14.03.2022 - Monday - 23:59**

**Comment by bahricanyesil** [comment]
INFO:
I have completed my research on semantic search.

I shared my research results in detail on our Discord channel. Ezgi will document them on a wiki page.

Here's the titles I focused on:
1- What's semantic search?
2- A good real-life example (The Lord of the Rings movie)
3- How did semantic search change SEO (Search engine optimization)?
4- What should we prioritize for SEO?

**Comment by egemenatikk** [comment]
INFO:
I have completed my research on semantic search.

I shared my research resılt in detail on our Discord channel. Ezgi will document them on a wiki page.

Here's the titles I focused on:
1- What's semantic search?
2- How does the Search work?
3- A few examples
4- Useful video link about Semantic Search

**Comment by mbatuhancelik** [comment]
I have completed my research.
I mainly focused on Semantic Search's definition and its mechanics under the hood.

**Comment by xltvy** [comment]
INFO:
I have completed my research on semantic search.

I shared the result of my research on our Discord channel. [Ezgi](@ezgy ) will document them on a wiki page.

I have focused on the usage of HTML and HTML tags for semantic search and how those tags provide a contextual meaning for the HTML code, which makes it easier for machines to understand the web content's contextual meaning.

**Comment by codingAku** [comment]
INFO:

My research on semantic search is completed. It focuses on factors related to the structure of semantic search. I have sent the findings to our discord channel.

**Comment by surmelienes1** [comment]
INFO:
I have completed my research on semantic search.

I shared my research results in detail on our Discord channel. Ezgi will document them on a wiki page.

Here's the titles I focused on:
1- What is semantic search?
2- How Does Semantic Search Work?
3- Importance of Semantic Search for SEO

**Comment by onurkomurcu** [comment]
INFO:
I have completed my research on semantic search. I post following questions on our discord channel.
1- What is semantic search?
2- How long has semantic search been around?

**Comment by ahmet633** [comment]
INFO:
I have completed my research on semantic search. I shared the findings on our discord channel. I tried to find some relevant repos for understanding and/or implementing semantic search in our project.

**Comment by ezgy** [comment]
The research period has ended and this issue will be closed. Results of the research will be documented [here](https://github.com/bounswe/bounswe2022group2/wiki/Semantic-Search). The issue regarding documentation is #26.
