### ISSUE TITLE
Milestone-2: Requirements for Event Creation and Viewing Attended Events

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#259]
### Issue Description

* As part of the Milestone Report 2 we need to provide a requirements specification of the practice app.
* I took the responsibility of specifying the requirements for **Event Creation and Viewing Attended Events**, since I have been responsible for the implementation of those respective functionalities, which can be tracked from #195 and #217.

### Step Details

Steps that will be performed:
- [x] Examine our application's backend and frontend.
- [x] Write down a specification of the requirements related to this issue
- [x] Add the requirements to appropriate parts of the online document
- [x] Add the requirements to appropriate page of our wiki

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday - 17.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

20.05.2022 - Friday - 18.00

**Comment by xltvy** [comment]
I have examined our practice application's backend and frontend and I have specified the requirements about event creation and viewing attended events. Specification is provided below:

1. Functional Requirements
1.1. User Requirements
1.1.2. User Interaction
1.1.2.1. User - Event Interaction
1.1.2.1.1. Creating Events
1.1.2.1.1.1. Users shall be able to create events by providing a title, description, a valid date, a valid location, and a valid lesson ID.
1.1.2.1.2. Viewing Events
1.1.2.1.2.1. Users shall be able to view events they are attended.

**Comment by xltvy** [comment]
I have updated the relevant part of the [online document](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit) and the wiki [page](https://github.com/bounswe/bounswe2022group2/wiki/Practice-App-Requirements). They all can be viewed from their respective links provided. After a review by @surmelienes1, this issue will be closed.

**Comment by surmelienes1** [comment]
It seems very good and complete now, thank you @xltvy for your contributions.

I will now close this issue since I don't have anything to further add, if you have any questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
