### ISSUE TITLE
Conducting Research on Software from Rival Companies

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#27]
### Description
- Every team member should conduct some research about software from rival companies to detect similarities and differences in respective features.
- Please edit this issue and put "x" inside the brackets left of your name once you've completed your research. 
- You can read more about task lists [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists).

### Deadline
- Please complete your research and post the findings on our Discord channel under the Competitor Analyses thread **until 13/03/2022 Sunday 20:00**.

### Checklist

- [x] [Ahmet Yiğit Özdoğan](@ahmet633)
- [x] [Altay Acar](@xltvy)
- [x] [Bahrican Yeşil](@bahricanyesil)
- [x] [Egemen Atik](@egemenatikk)
- [x] [Ecenur Sezer](@codingAku)
- [x] [Ezgi Aysel Batı](@ezgy)
- [x] [Hasan Can Erol](@hasancan-code)
- [x] [Mehmet Batuhan Çelik](@mbatuhancelik)
- [x] [Muhammed Enes Sürmeli](@surmelienes1)
- [x] [Onur Kömürcü](@onurkomurcu)

This issue will be closed and the results will be summarized on our Wiki as a separate page under the research on Rival Companies after the initial research from team members is completed and the results have been gathered on our Discord channel. It is my(@surmelienes1) duty to document the research results on the Wiki. Here is a link to the related issue:

**Deadline for documentation: 14.03.2022 - Monday - 23:59**

**Comment by bahricanyesil** [comment]
Can you provide a template/titles that each person should find information about? I am putting what came into my mind for now. You can expand it and it will be best if you can provide a template table (just as in the personal information or meeting notes templates) for everyone to follow for integrity purposes. We can use this template until the end of the project while doing competitor analyses.

Here's the list of titles/table columns that came into my mind. You can select the suitable ones according to your decisions. I just wrote the generally used ones, some of them may not be required for us:

1. Primary Purpose/Feature of the project
2. Complete list of features
3. Last update date
4. Download number
5. Account types (e.g. free, freemium, premium)
6. Pricing policies
7. Supported languages
8. Play/App Store ratings

**Comment by bahricanyesil** [comment]
INFO:
I chose [Socrative](https://www.socrative.com/) app in my competitor analysis. 

I analyzed it under the following titles:
1- Base feature
2- Features
3- Technological Advantage
4- Pricing
5- Mobile App Details
6- About
7- User number & Rating & Multi-Language support

I shared my analysis results via the Discord channel.

**Comment by xltvy** [comment]
INFO:
I chose [Genius](https://genius.com/) in my competitor analysis. 

Genius is an annotation driven knowledge community, which is mostly used for hip-hop and pop song lyrics. It is free to sign up, download, and use and based on a collaborative knowledge.

I analyzed it under the following titles:
1 - Base feature
2 - Annotation system
3 - Verification system
4 - User reliability
5 - What is missing about Genius' annotation system?

I shared my research results via our Discord channel.

**Comment by egemenatikk** [comment]
INFO: 
I chose [Kunduz](https://kunduz.com/tr_tr/) in my competitor analysis.

Their slogan is "It has never been this easier to prepare for the exam". It enables student to reach the answers they are looking for in a simple way.

I analyzed it under the following titles:
1-Base feature
2-Features
3-Pricing
4-Mobile App
5- About
6- User number & Rating & Multi-Language support

I shared my analysis results via the Discord channel.

**Comment by mbatuhancelik** [comment]
I choose [Coursera](https://www.coursera.org) for my research.
Results are TBA this night via Discord.

**Comment by codingAku** [comment]
I have chosen [Pluralsight](https://app.pluralsight.com/library/) for my competitor analysis.
It has been analyzed under the following:
1- About
2- Base features
3- Additional features
4- Pricing
5-Mobile app

The analysis can be found on Discord channel.

**Comment by hasancan-code** [comment]
I chose [Codeacademy](https://www.codecademy.com/) in my competitor analysis. 

I analyzed it under the following titles:
1- Purpose
2- Features
3- Programming Languages at Codeacademy
4- Supported Languages
5- Subjects
6- Pricing Policy

I shared my research via our Discord channel.

**Comment by ezgy** [comment]
I analysed [Khan Academy](https://www.khanacademy.org/) for competitor analysis. I focused on features provided, general structure and similarities/differences with the learning platform planned.

**Comment by onurkomurcu** [comment]
I choose [Udemy](https://www.udemy.com) for competitor analysis. I focused on general pros and cons about Udemy. This analysis is posted in our discord channel.

**Comment by surmelienes1** [comment]
INFO:
I chose [Kahoot!](https://kahoot.com/) app in my competitor analysis.

I analyzed it under the following titles:
1- Base feature
2- Features
3- Pricing
4- Mobile App Details
5- About
6- User number & Rating & Multi-Language support

I will share my analysis results via our Discord channel.

**Comment by ahmet633** [comment]
INFO:
I chose [Skillshare](https://www.skillshare.com/) in my competitor analysis.

The analysis consists of main pros and cons.

You can find the report in the CmPE 352 2022 Group 2 Discord Server under the channel Researches -> Competitor Analyses
