### ISSUE TITLE
Milestone-2: Evaluation of Tools - Discord, GitHub, Google Docs, Node.js & Express.js, Vue.js

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#270]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to provide the evaluation of tools we used.
* I took the responsibility of the first part of this evaluation section. The parts that I will evaluate are written in the step details section below.

### Step Details

Steps that will be performed:
- [x] General evaluation
- [x] Discord
- [x] Github
- [x] Google Docs
- [x] Node.js & Express.js
- [x] Vue.js

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.
* All final documents can be found in our [milestone report - 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing)

### Deadline of the Issue

20.05.2022 - Friday - 17.00

### Reviewer

Egemen Atik

### Deadline for the Review

20.05.2022 - Friday - 18.00

**Comment by bahricanyesil** [comment]
## INFO

I completed all of the steps mentioned in the issue. I wrote the content of the indicated sections. All of them can be viewed from our [Milestone Report - 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing).

**Comment by bahricanyesil** [comment]
### 3.1. Evaluation of Tools
Throughout developing our project we had to use many different tools in order to achieve different objectives. When choosing which tool to use for a task, there were several points to consider. One of the most important points was that the tool should enable us to work collaboratively and observe each other's work easily, since we always had to divide tasks among ourselves so that every member could contribute. Another criteria was ease of use since we didn’t have any experience and had to learn as we progressed. Following subsections will include a short summary on the tools we used, their purpose and our evaluation.

**Comment by bahricanyesil** [comment]
### 3.1.1. Discord
We used Discord as our main communication tool. All  team meetings were held in voice channel and we created different text channels for different needs such as meeting notes, research material, general and random chat. We found Discord to be useful as our main communication tool since it is easy to use and many of us were already familiar with it. Features such as having multiple voice channels in the same group and separate text channels were particularly useful. Besides these, using threads to separate messages within the same text channel (such as having a new thread for each meeting or research topic) made our channel easy to navigate and organized. Overall, Discord provided all the basic features we required from a team communication environment and we plan on keeping the same channel and structure for the development phase of this project as well.

**Comment by bahricanyesil** [comment]
### 3.1.3. Google Docs
Generally, for the documentation related tasks of our project we used the Wiki section of our Github Repository. This was useful enough as we could individually work on our parts and easily check change history if needed. Since most of our documentation deliverables were meant to be published on Wiki anyway this made our task easier and we didn’t have to include an additional step of migrating. However, when it came to a more detailed work of reporting, such as the Milestone report, Github wiki was not a good enough option. We needed a space where everyone could work simultaneously for longer times without conflicting versions. We found Google Docs to be the most useful tool for such a task. It is easily accessible, we are all familiar with using it, and it provides good collaboration with synced work and commenting features. One disadvantage of Google docs was that with tables and images we had the issue of position stability. As more content was added above the design changed. However, considering 9 people worked on the same document at once it is an understandable issue and did not pose a great problem to us.

**Comment by bahricanyesil** [comment]
### 3.1.4. Node.js & Express.js
Node.js is an open-source back-end JavaScript runtime environment and Express.js is a free and open source back-end web application framework for Node.js. We chose to use Node.js and Express.js while developing the back-end of the application. The reasons behind this decision are as follows: Node.js and its most popular and easy to use web application framework, Express.js, are so common in the industry. This leads to lots of resources about tutorials, questions, answers, code sections, example implementations and so on. Other than this reason, since we are new to the real-world server implementation area, we had to choose comparably easier technologies while developing the back-end. All team members firstly learned the Javascript syntax to be familiar with, then gained knowledge about Node.js runtime environment and finally had practice on Express.js framework, its routings, controllers and so on. With the help of the modularity of the project setup, we also separated models, controllers, validators, routers and so on. We also benefit from some external packages in required places such as Joi to validate models. All of these many different helpful packages and features are the result of the fact that Node.js & Express.js (so that Javascript) is widespread.

**Comment by bahricanyesil** [comment]
### 3.1.5. Vue.js
Vue.js is an open-source model–view–viewmodel front-end JavaScript framework for developing user interfaces for web applications. Initially, we decreased our options for the technology we will use while developing the front-end into 2: React.js and Vue.js. After the discussion among the team members, we eliminated React since it is a bit more complex than Vue.js for the ones who are not familiar with it before (even though there are some team members who used React previously among the team). Even though there is no-one in the team who has experience with Vue.js before, we chose to start a challenge for ourselves and wanted to learn it. Since it is a popular and getting more popular day by day, we thought that learning it will also be beneficial for our future career. We created a main app and routing file in the core of the project. Other than that, we basically created separate screens for each unique feature and created these screens under the ‘/components’ directory. Each component file includes mainly 3 separate parts inside: html, javascript, css (view, script, style). We mostly used html to draw the corresponding components and screens and javascript to communicate with our back-end, store network responses.

**Comment by egemenatikk** [comment]
I reviewed your work, thank you for your effort  @bahricanyesil. I have nothing to add to your evaluations, therefore this issue is completed and can be closed.
