### ISSUE TITLE
Milestone-2: Requirements for Signup and Viewing Lessons by Category

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#271]
### Issue Description

* As part of the Milestone Report 2 we need to provide a requirements specification of the practice app.
* I took the responsibility of specifying the requirements for **Signup and Viewing Lessons by Category**, since I have been responsible for the implementation of those respective functionalities, which can be tracked from #152 and #159.

### Step Details

Steps that will be performed:
- [x] Examine our application's backend and frontend.
- [x] Write down a specification of the requirements related to this issue
- [x] Add the requirements to appropriate parts of the online document
- [x] Add the requirements to appropriate page of our wiki

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday - 17.00

### Reviewer

Altay Acar

### Deadline for the Review

20.05.2022 - Friday - 18.00

**Comment by bahricanyesil** [comment]
## Signup Requirements

Signup requirements will be placed under the user/authentication requirements.

I determined the requirements for the signup functionality as follows:
- Guests shall enter their name, email address and passwords to be able to signup. These are the required information that users have to provide to enter the app.

**Comment by bahricanyesil** [comment]
## Lessons by Category Requirements

Lessons by Category requirements will be placed under the system/lessons requirements.

I determined the requirements for this functionality as follows:
- Users shall be able to filter the lessons according to their categories.

**Comment by bahricanyesil** [comment]
## INFO

I completed and wrote the requirements for the functionalities:
- Signup
- Get lessons by category

It is now ready to be reviewed by @xltvy.

**Comment by bahricanyesil** [comment]
## INFO

I added the written requirements into our [Milestone Report - 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing).

**Comment by bahricanyesil** [comment]
## INFO

I created a separate wiki page for practice app requirements and added the requirements I determined above to that wiki page. You can view the practice app requirements [here](https://github.com/bounswe/bounswe2022group2/wiki/Practice-App-Requirements).

**Comment by xltvy** [comment]
I have reviewed your work, I think it is all done and ready. Closing, #271
