### ISSUE TITLE
Milestone-2: Requirements for Enrolling Lesson and Search Categories

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#278]
### Issue Description

* As part of the Milestone Report 2 we need to provide a requirements specification of the practice app.
* I took the responsibility of specifying the requirements for **Enrolling Lessons and Search Categories by Name**, since I have been responsible for the implementation of those respective functionalities.

### Step Details

Steps that will be performed:
- [x] Examine our application's backend and frontend.
- [x] Write down a specification of the requirements related to this issue
- [x] Add the requirements to appropriate parts of the online document
- [x] Add the requirements to appropriate page of our wiki

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday - 17.00

### Reviewer

Ecenur Sezer

### Deadline for the Review

20.05.2022 - Friday - 18.00

**Comment by hasancan-code** [comment]
## Enroll Lesson requirements

- User should provide his/her user_id and lesson_id of the lesson wants to take.
- User has to have not taken this lesson before.

**Comment by hasancan-code** [comment]
## Search Categories by Name requirements

Search Categories by Name requirements will be placed under the Searching and Browsing requirements.

- User should provide keywords wanted to be searched.
- User shall be able to see any category if the category includes a keyword on its name.

**Comment by hasancan-code** [comment]
I added requirements to Practice_app requirements wiki page.

**Comment by onurkomurcu** [comment]
I have reviewed your work, @hasancan-code . Thank you for your contribution!
