### ISSUE TITLE
Milestone-2: 1.1. Introduction/Project Description & 1.2. Project Status

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#284]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to provide the executive summary.
* I took the responsibility of the first part of this summary section. The parts that I will evaluate are written in the step details section below.

### Step Details

Steps that will be performed:
- [x] 1.1 Introduction/Project Description
- [x] 1.2 Project Status

### Final Actions

After reviewing of my work, the issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday 17.00

### Reviewer

Egemen Atik

### Deadline for the Review

20.05.2022 - Friday 23.00

**Comment by codingAku** [comment]
I have completed the necessary parts of the  [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to provide the executive summary.

**Comment by codingAku** [comment]
Here you can find my work:


1.1 Introduction/Project Description
As group 2 of CMPE 352 course, our task is to design a learning platform where people can freely give courses and become a learner. For this purpose, we have lecturers and learners as users of our application. Additionaly, many other features such as organizing events, filtering, searching courses, rating lessons exist. We ought to implement a web application for this platform. 
Before actual implementation of our project, we have a task to design a practice app to test our frontend and backend skills. We designed this application to have similar features and requirements. Each team member have a task to create at least two, GET and POST endpoints based on our needs, and implement a UI. In our application, we can view lessons, create events where learners of a lesson can get together in real life, search and filter lessons based on categories and ratings, rate a lesson. Our last task is to deploy the application using Docker and AWS systems.
1.2 Project Status
Over the whole term, we have worked on designing our application as stated in Milestone 1. We first decided on requirements, what features are required for our application and we split them into sections. When questions related to deciding requirements arised, we attended customer meetings to clearify. After that, we created mockups and scenarios for basic actions users are capable to do in our app. For detailing the plan of implementation, we created class-user-sequence diagrams. To observe our work done so far, we created project plans and RAM.
One of the most important research topics for our implementation was becoming skilled in Git and Github since we have many pull requests, issues and merges. As a team we developed our skills on using Git. Next step was determining on technologies we will use in our app. We had meetings and researches about finding the most optimal tools for our app and we choose Vue.js and Node.js frameworks. Finally, after researching Docker and AWS to deploy our app, we started implementing practice app.

As stated in 1.1 we made a job share for implementing required features. Every team member created issues for implementing endpoints first since we started from backend. After a endpoint is completed, we created PR’s for corresponding issues. Next step of finalizing endpoints was coding unit tests for each. After tests and manual tests from Postman all passed, each team member implemented a UI for the endpoints they are responsible. During this process, reviewing of each others work was a integral part. We stated the errors and necessities of each other’s work during implementation. Finally, we documented API and Milestone.

**Comment by onurkomurcu** [comment]
I have reviewed your work, @codingAku. Thank you for your contribution!
