### ISSUE TITLE
Milestone-2: Filling the indiviual work table

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#288]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to fill the individual work table. In this issue, I will fill a section of the report with issues I have reviewed and opened.

### Final Actions

After reviewing, the issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday 17.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

20.05.2022 - Friday 23.00

**Comment by codingAku** [comment]
![image](https://user-images.githubusercontent.com/64018144/169581479-c33b36d9-2a52-41df-bee1-f6a97963b5e2.png)

**Comment by surmelienes1** [comment]
It seems very good and complete now, thank you @codingAku for your efforts.

I will now close this issue since I don't have anything to further add, if you have any questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
