### ISSUE TITLE
Milestone-2: Filling the individual work table 

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#291]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to fill the individual work table. In this issue, I will fill a section of the report with issues I have reviewed and opened.

### Final Actions

After reviewing, the issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday 17.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

20.05.2022 - Friday 23.00

**Comment by onurkomurcu** [comment]
I have reviewed your work, @hasancan-code . Thank you for your contribution!
