### ISSUE TITLE
Practice App API Documentation

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#292]
I took the responsibility for API documentation. It can be tracked from our wiki page or directly accessible from [here](https://github.com/bounswe/bounswe2022group2/wiki/Practice-App-API-Documentation)

### Final Actions

After reviewing, the issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday 17.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

20.05.2022 - Friday 23.00

**Comment by onurkomurcu** [comment]
I have reviewed your work, @hasancan-code. Thank you for your contribution!
