### ISSUE TITLE
Milestone-2: Filling the individual work table - Bahrican Yesil

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#293]
### Issue Description

As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to fill the individual work table. In this issue, I will fill a section of the report with issues I have reviewed and opened.

### Step Details

Steps that will be performed:
- [x] Fill the table

### Deadline of the Issue

20.05.2022 - Friday - 22:00

### Reviewer

Egemen Atik

### Deadline for the Review

20.05.2022 - Friday - 22:30

**Comment by bahricanyesil** [comment]
I filled the table and completed my section. It is ready to be reviewed by @egemenatikk.

**Comment by bahricanyesil** [comment]
## Screenshots from the table

<img width="505" alt="Screen Shot 2022-05-20 at 21 15 18" src="https://user-images.githubusercontent.com/60237280/169588621-24c79535-bd6d-4009-b756-3b3de86c514b.png">
<img width="513" alt="Screen Shot 2022-05-20 at 21 15 43" src="https://user-images.githubusercontent.com/60237280/169588670-59eb2602-f096-43d1-a659-572a560b3924.png">
<img width="505" alt="Screen Shot 2022-05-20 at 21 15 55" src="https://user-images.githubusercontent.com/60237280/169588691-89659c29-7268-422d-9b97-3efe334f2606.png">
<img width="496" alt="Screen Shot 2022-05-20 at 21 16 02" src="https://user-images.githubusercontent.com/60237280/169588717-c66b4c0d-8f85-4c2a-9fee-5c00c902d586.png">

**Comment by onurkomurcu** [comment]
I have reviewed your work, @bahricanyesil. Thank you for your contribution!
