### ISSUE TITLE
Milestone-2: Evaluation of Tools - Postman, MongoDB, Lucidchart

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#297]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to provide the evaluation of tools we used.
* I took the responsibility of the second part of this evaluation section. The parts that I will evaluate are written in the step details section below.

### Step Details

Steps that will be performed:
- [x] Postman
- [x] MongoDB
- [x] Lucidchart

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.
* All final documents can be found in our [milestone report - 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing)

### Deadline of the Issue

20.05.2022 - Friday - 21:00

### Reviewer

Bahrican Yesil

### Deadline for the Review

20.05.2022 - Friday - 22:00

**Comment by egemenatikk** [comment]
## INFO

I completed all of the steps mentioned in the issue. I wrote the content of the indicated sections. All of them can be viewed from our [Milestone Report - 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing).

Now, it is ready to be reviewed by @bahricanyesil .

**Comment by egemenatikk** [comment]
## 3.1.6. Postman
Postman is an API platform for developers to design, build, test and iterate their APIs. Today, the application has more than 20 million registered users and 75000 open APIs. It has many products like API repository and API builder. By unanimous vote, we chose to use Postman to test our APIs, because firstly it is free to use it individually. Another nice feature of it is that it provides users easy documentation. We all prepared our documentations by using that feature. Most obvious reason we chose Postman is that it is the most popular API testing application in today’s world. Some of our members already had experiences with Postman, some of us were not very familiar. At the end of our practice-app, we all improved ourselves in using Postman. As I mentioned, we tested our APIs using Postman and shared Postman documentation links in our issues. We also plan to create a wiki page and include those Postman documentation links there. They include examples of  failing requests, successful requests and corresponding bodies for those requests. Every request includes an example response and they are very easy to read and understand.

**Comment by egemenatikk** [comment]
## 3.1.7. MongoDB
For our practice app to be maintainable, usable we needed a database management system to keep or data in, get or change data when necessary. For that purpose, we had a few options like MySQL, MongoDB, PostgreSQL. Most of our members take CMPE321 course this semester, so we were familiar with MySQL and SQL and some of us were also experienced in MongoDB. We discussed about which system we should use, made a list of pros and cons and decided to go with MongoDB. We chose to go with it because it is one of the most popular, maybe the most popular, database management systems in the world right now, so we thought it could be nice to learn it as soon as possible. Other than that, it has more functionalities than other database management systems, for example we can keep lists as fields in MongoDB. It took a while for many of us to adapt ourselves to using MongoDB but in the end we managed to complete our practice app by using MongoDB as our DBMS. MongoDB is a document-oriented NoSQL database used for high volume data storage. Instead of tables and rows, we use documents and collections in MongoDB. Documents consists of key-value pairs and those pairs are basic unit of data in MongoDB. Database contains collections and collections contain documents inside of them. Also, each document can differ in terms of number of fields, even if they are in the same collection. Size and content of documents in same collection can differ. Documents do not have to have a schema beforehand. It also has more complex structures. As summary, it provides more freedom to users.

**Comment by egemenatikk** [comment]
## 3.1.10 Lucidchart
We used Lucidchart to create our system design diagrams: use-case diagram, sequence diagrams and class diagram. From our previous research we found Lucidchart to be the most useful tool for this task, since it was developed specifically for the goal of making the system design process easier. It included all the specific notation elements. Useful features of Lucidchart include many notation elements that are easy to add to your design, simple usage when it comes to making edits and a good collaborative page to work on together. In contrast to Figma, Lucidchart elements were much easier to learn and use and their tutorials were quite helpful so every member of the team was able to create in Lucidchart together. We were happy with the collaborative working system and the outcome of our efforts. Overall, Lucidchart provided all the features we required and we were satisfied.

**Comment by onurkomurcu** [comment]
I have reviewed your work, @egemenatikk . Thanks for your great effort!
