### ISSUE TITLE
Create a template for Meeting Notes

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#3]
Since the meeting notes will be documented on the wiki page each week by a different person, a standard structure should be determined. This structure should contain the following information:

- Location, Time and Attendance information
- Agenda
- Discussion 
- Action Items

**Comment by ezgy** [comment]
Initial design for the meeting notes template can be found [here](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-Notes-Template). Please review.

**Comment by bahricanyesil** [comment]
> Initial design for the meeting notes template can be found [here](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-Notes-Template). Please review.

It seems nice and enough good for now, great template 🚀

**Comment by ezgy** [comment]
the template is completed, reopen this issue for any fixes or suggestions.
