### ISSUE TITLE
Milestone-2: Filling the individual work table - Muhammed Enes Sürmeli

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#306]
### Issue Description

As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to fill the individual work table. In this issue, I will fill a section of the report with issues I have reviewed and opened.

### Step Details

Steps that will be performed:
- [x] Fill the table

### Final Actions

After reviewing, the issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday - 17:00

### Reviewer

Onur Kömürcü

### Deadline for the Review

20.05.2022 - Friday - 23:59

**Comment by onurkomurcu** [comment]
I have reviewed your work, @surmelienes1. Thank you for your contribution!
