### ISSUE TITLE
Milestone-2: Writing the Challenges and Filling the List and Status of Deliverables Table

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#307]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to provide the executive summary.
* I took the responsibility of the 1.4 Challenges and 1.5 List and Status of Deliverables part of this summary section. The parts that I will evaluate are written in the step details section below.

### Step Details

Steps that will be performed:
- [x] 1.4 Challenges
- [x] 1.5 List and Status of Deliverables

### Final Actions

After reviewing of my work, the issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday - 17:00

### Reviewer

Hasan Can Erol

### Deadline for the Review

20.05.2022 - Friday - 23:59

**Comment by onurkomurcu** [comment]
I have reviewed your work, @surmelienes1. Thank you for your contribution!
