### ISSUE TITLE
Updating Wiki Home Page 

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#310]
### Issue Description

 Since we work on 451 class now with our new teammates and new project plans, the home page of our repository needs to revised and changed accordingly. 

### Step Details

- [x] Change header

- [x] Update group photo

- [x] Add links for newcomers' wiki pages

- [x] Add link for project plan

- [x] Organize descriptions and paragraphs

### Final Actions

Links for project plan and newcomers' wiki pages needed to be active after they are complete.

### Deadline of the Issue

10.10.2022 - 23:59

### Reviewer

Altay Acar

### Deadline for the Review

11.10.2022 - 13:00

**Comment by codingAku** [comment]
[Home page](https://github.com/bounswe/bounswe2022group2/wiki) has been updated.

**Comment by xltvy** [comment]
Thank you for the updates @codingAku , I think it is good to go. Closing #310.
