### ISSUE TITLE
Personal Wiki Page

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#311]
### Issue Description

Creation of a personal wiki page as a new team member should be done as the first step for being a part of the team. Also, it helps to introduce the newcomer to the team members and to the followers of the project.

### Step Details

Steps that will be performed:
- [x] Provide the body of the personal wiki page

### Final Actions

Make sure the page is connected to the links at README and sidebar.

### Deadline of the Issue

10.10.2022 - Monday - 23.59

### Reviewer

Ecenur Sezer

### Deadline for the Review

11.10.2022 - Tuesday * 23.59

**Comment by shashi3000** [comment]
So do you want an html/css/js project or just a word doccument

**Comment by gokayyildiz** [comment]
@codingAku task completed need review https://github.com/bounswe/bounswe2022group2/wiki/Gokay-Yildiz

**Comment by codingAku** [comment]
Hello, although I believe the description for smart students like us a little bit short, I still thank you for completing it :)
