### ISSUE TITLE
Add Koray Tekin personal wiki

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#312]
### Issue Description

In the first meeting of class CmpE451 group2 has decided that newcomers need to create their personal wiki pages, in correlation with the enhancement of the home page. This issue is related to  #310.   

### Step Details

Steps that will be performed:
- [x] Provide photo and description
- [x] Provide skills
- [x] Provide the contact information
- [x] Provide interests 
- [x] Provide contributions

### Final Actions

The corresponding link should be provided for the home page enhancement when the wiki page is ready.

### Deadline of the Issue

10.10.2022 - 23.59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

11.10.2022 - 13:00

**Comment by Koraytkn** [comment]
@mbatuhancelik I have finished the initial creation of my personal wiki page, asking for your revision; thanks in advance.

**Comment by mbatuhancelik** [comment]
We are expected to have our github usernames on our profiles, sorry this was not in the template, it was just a requirement that appeared on the middle of the last semester, so the template is a lil bit out of date.

Also as a rule of thumb it would be amazing if you can link the wiki page or PR related to your work here, reviewing on our end and grading on TA's end will be easier.

**Comment by Koraytkn** [comment]
Thank you for your feedback Batuhan. I have added the username information, the current version is [here](https://github.com/bounswe/bounswe2022group2/wiki/Koray-Tekin).

**Comment by onurkomurcu** [comment]
Great work @Koraytkn!
