### ISSUE TITLE
Update Sidebar

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#313]
### Issue Description

We have started a new term with a new class which is CMPE 451 instead of CMPE352. This class change has also brought some changes in our project plan, communication plan, diagrams, requirements, and so on. Therefore, the sidebar of the project repository should also be revised and necessary changes should be implemented. This process will be managed with the help of this issue.

### Step Details

Steps that will be performed:
- [x] Check whether all links in the sidebar works and navigates to the correct screen
- [x] Add new teammates to the group members part and overline the old members who left the team
- [x] Edit the milestones part to be as separate for CMPE352 and CMPE451
- [x] Add project plan section and its corresponding link (Project Plan of CMPE451)
- [x] Create new sidebar parts that we need for CMPE451:
* Mobile/Front/Back meetings sections under the meeting section
* Templates section

### Final Actions

After the necessary steps mentioned above are performed, the changes will be available to be seen at the sidebar of our repository. 

### Deadline of the Issue

10.10.2022 - Monday - 23:59

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

11.10.2022 - Tuesday - 12:00

**Comment by bahricanyesil** [comment]
Added Koray Tekin (@Koraytkn) and Gökay Yıldız (@gokayyildiz) as our new team members to the sidebar and crossed out Ahmet Yiğit since he is not our teammate anymore.

**Comment by bahricanyesil** [comment]
Edited the milestones part as two separate parts (CMPE352 and CMPE451 Milestones).

**Comment by bahricanyesil** [comment]
Created a project plan section in the sidebar and linked an uncreated page of the project plan temporarily. After the people responsible to create the project plan page (@mbatuhancelik and @onurkomurcu) finalize their work, I will check and edit the link if necessary.

**Comment by bahricanyesil** [comment]
Created "Templates" section and added "Issue Templates", "Meeting Notes Template", and "Personal Information Page Template" parts with their links.

**Comment by bahricanyesil** [comment]
Checked all items and the links, and completed all steps mentioned in the issue. Ready to review by @ezgy.

**Comment by ezgy** [comment]
Everything seems good and the links are working properly. Once #316 is completed and the Project Plan is linked properly I will close this issue.

**Comment by gokayyildiz** [comment]
Maybe we can omit the old team member names from the sidebar, names only on the wiki home page would be enough.

**Comment by bahricanyesil** [comment]
I remember that we are told to overline them instead of removing them. Since it is not so important, let's leave it as it is.

**Comment by onurkomurcu** [comment]
> Maybe we can omit the old team member names from the sidebar, names only on the wiki home page would be enough.

- I think that it is not that important @gokayyildiz. Additionally, having them also in the sidebar is good for consistency through whole wiki page in my opinion.



> Everything seems good and the links are working properly. Once #316 is completed and the Project Plan is linked properly I will close this issue.

- Project plan was added. 

Whole sidebar is look adequate from now on. If necessary changes are needed in the sidebar during the semester, this issue can be reopened. For now, it can be closed. Thank you all!

**Comment by bahricanyesil** [comment]
> Everything seems good and the links are working properly. Once #316 is completed and the Project Plan is linked properly I will close this issue.

Now the linked issue is completed and the dependency is removed. The project plan is linked in both the sidebar and also the home screen. @onurkomurcu closed just seconds ago! :)
