### ISSUE TITLE
Report and Resource Research on Flutter (Mobile Team)

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#314]
### Issue Description

We determined the teams in our last meeting and assigned people to those groups. At the final stage, our mobile team consists of me (@bahricanyesil ), @ezgy, @egemenatikk, and @onurkomurcu. We as the mobile team discussed the possible technologies that we can use for mobile development. In the end, we agreed to develop the application with Flutter. I will itemize our justifications behind the decision of using Flutter and I will prepare a list of helpful resources, courses, and so on for those new to Flutter.

### Step Details

Steps that will be performed:
- [x] Itemize the reasons to choose Flutter
- [x] Find helpful resources (Youtube channels)
- [x] Find beginner-level courses

### Final Actions

After the justifications are listed under this issue, the points will be shared with our TA (@alper111) and we will report our preference to use Flutter with these justifications.

Other than that, helpful resources and courses will be shared with other team members and we will begin to prepare for coding by starting learning.

### Deadline of the Issue

10.10.2022 - Monday - 23:59

### Reviewer

Egemen Atik

### Deadline for the Review

11.10.2022 - Tuesday - 12:00

**Comment by bahricanyesil** [comment]
Reasons to Choose Flutter
1- Flutter is based on Dart language which is so similar to Java. Since we all took beginner-level courses in the department with Java and learned the programming basics with Java, using Dart will not be a problem for us, and the adaptation process will be easy for us.
2- In Flutter, the visual (UI) and logic parts of the code are included in the one-single code base. This fact eases and speeds up the coding. In the end, we can reach MVP and the aimed version of the app in a shorter time compared to other technologies.
3- Normally, it is expected to performance decrease in cross-platform technologies. Even though Flutter has also some downgrades, it serves near-to-native performance in most cases with the help of the Dart compiler since it converts the Flutter app to native code. In the end, we are able to use the native features.
4- We are building a huge app with lots of features and so with lots of screens, UI components, widgets, and so on. This brings up complexity and difficulty of implementation. However, Flutter gives various UI components as in-built support and you can use all of them as just widgets. Besides this, its package system ([pub.dev](https://pub.dev)) has lots of free open source packages that include various design/logic solutions for apps.
5- Flutter has hot-reload feature with very fast reloading time. This feature will be very useful in the development and debug process!
6- We have experienced people with Flutter, this will speed up our development and we will be able to implement almost all features with good design and code patterns in the given time (1 semester).
7- We have people who are very curious about Flutter and want to learn it. This curiosity and desire to learn will carry us forward when we start to code the project.

**Comment by bahricanyesil** [comment]
### Helpful Flutter Youtube Channels

1. [Flutter](https://www.youtube.com/c/flutterdev)
2. [Reso Coder](https://www.youtube.com/c/ResoCoder)
3. [Vandad Nahavandipoor](https://www.youtube.com/c/VandadNP)
4. [Flutter Explained](https://www.youtube.com/c/FlutterExplained)
5. [The Flutter Way](https://www.youtube.com/c/TheFlutterWay)
6. [Robby Rahmana](https://www.youtube.com/c/RobbyRahmana)
7. [HardwareAndro](https://www.youtube.com/c/HardwareAndro) - Turkish

**Comment by bahricanyesil** [comment]
### Flutter Courses
1. [Flutter & Dart - The Complete Guide [2022 Edition]](https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/) -- Most Recently Updated
2. [The Complete 2021 Flutter Development Bootcamp with Dart](https://www.udemy.com/course/flutter-bootcamp-with-dart/)

**Comment by bahricanyesil** [comment]
I finished the itemization of the reasons to choose Flutter, found helpful Youtube channels and courses, and listed them above. Now, all things are ready to be reviewed by @egemenatikk.

**Comment by ezgy** [comment]
thank you @bahricanyesil for the research and many learning sources. excited to start 🚀

**Comment by bahricanyesil** [comment]
Thanks for the review @ezgy.

**Comment by bahricanyesil** [comment]
I re-opened the issue to add the last section for the interested ones on "How does Flutter run the code on Android?"

From the FAQ section of the official website:

> The engine’s C and C++ code are compiled with Android’s NDK. The Dart code (both the SDK’s and yours) are ahead-of-time (AOT) compiled into native, ARM, and x86 libraries. Those libraries are included in a “runner” Android project, and the whole thing is built into an .apk. When launched, the app loads the Flutter library. Any rendering, input, or event handling, and so on, is delegated to the compiled Flutter and app code. This is similar to the way many game engines work.
> 
> During debug mode, Flutter uses a virtual machine (VM) to run its code in order to enable stateful hot reload, a feature that lets you make changes to your running code without recompilation. You’ll see a “debug” banner in the top right-hand corner of your app when running in this mode, to remind you that performance is not characteristic of the finished release app.

Link: https://docs.flutter.dev/resources/faq#run-android

**Comment by egemenatikk** [comment]
We shared our research with our TA, Alper Ahmetoğlu and he approved us using Flutter in our mobile development process. We are ready to start coding after completion of updating requirements and diagrams.
