### ISSUE TITLE
Updating Communication Plan

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#315]
### Issue Description

Our communication plan, including the time of our regular weekly meetings, has undergone some alterations as a result of the change in classes from CMPE352 to CMPE451. Therefore, it is vital to update the communication plan and make the appropriate adjustments. This issue will assist in managing this procedure.

### Step Details

Steps that will be performed:
- [x] See whether we made any changes to the communication channels in the [first meeting notes of this semester](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%231-of-451-(08.10.2022))
- [x] Determine which areas of the [communication plan](https://github.com/bounswe/bounswe2022group2/wiki/Communication-Plan) require changes
- [x] Modify the timing of our regular weekly meetings

### Final Actions

The modifications will be visible in the communication plan part of our repository after the actions specified above have been taken.

### Deadline of the Issue

10.10.2022 - Monday - 23:59

### Reviewer

Hasan Can Erol

### Deadline for the Review

11.10.2022 - Tuesday - 12:00

**Comment by surmelienes1** [comment]
## Information

* Checked the [first meeting notes of this semester](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%231-of-451-(08.10.2022)) to see whether we made any changes to the communication channels or not.

* Determined the areas of the [communication plan](https://github.com/bounswe/bounswe2022group2/wiki/Communication-Plan) which require changes as the meeting time.

* Modified the timing of our regular weekly meetings according to the consensus of all the team members.

***
## Note

I completed all of the steps mentioned in the issue description and finalized the [communication plan page](https://github.com/bounswe/bounswe2022group2/wiki/Communication-Plan). It is now ready to be reviewed by @hasancan-code.

**Comment by hasancan-code** [comment]
It seems done well. Nice work. Now, the issue can be closed.
