### ISSUE TITLE
Updating ReadMe

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#317]
### Issue Description

Since we are starting a new term for CMPE451 with new members and new goals, changes should be made to the ReadMe document. All links and information should be up to date and any new additions should be included.

### Step Details

Steps that will be performed:
- [x] update date/term information
- [x] add new members' personal wiki pages
- [x] change communication plan info 

### Final Actions

All links should be up to date and working, including new member changes and project plan.

### Deadline of the Issue

10.10.2022 - Monday - 23:59

### Reviewer

Koray Tekin

### Deadline for the Review

11.10.2022 - 13:00

**Comment by ezgy** [comment]
The changes required have been made to the README document. Since our main branch is protected, #319 should be approved. Ready to be reviewed @Koraytkn :)

**Comment by Koraytkn** [comment]
I have reviewed the changes and merged them to master, I am closing this issue.
