### ISSUE TITLE
Update Personal Wiki Pages

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#324]
### Issue Description

In this semester, we preserved our skeleton crew from last semester and transferred 2 fresh bloods to our team.

According to the decision we took in our [first meeting of CMPE451](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%231-of-451-(08.10.2022)), our new members created their personal wiki pages. You can view their issues in #311 and #312.
  
Then, we realized that our remaining members also need to revise their personal wiki pages. So, every group member from last semester should check their personal wiki page and make the necessary changes.

### Step Details

Steps that will be performed:
- Check the personal wiki page
- Decide what to change, what to add and what to remove
- Tick your name in the list below to indicate that you completed updating your personal wiki page

### Responsible People

- [x] Bahrican Yesil
- [x] Egemen Atik
- [x] Altay Acar
- [x] Ezgi Aysel Batı
- [x] Muhammed Enes Sürmeli
- [x] Onur Kömürcü
- [x] Mehmet Batuhan Çelik
- [x] Hasan Can Erol
- [x] Ecenur Sezer

### Deadline of the Issue

10.10.2022 - Monday - 23:59

### Reviewer

Bahrican Yesil

### Deadline for the Review

11.10.2022 - Tuesday - 10:00

**Comment by bahricanyesil** [comment]
I looked at my personal page, detected the necessary changes, and took the required actions for them.

- I updated my bio
- I updated the weekly work/contribution part to represent a close list of CMPE352 efforts and an open top list of CMPE451 efforts.

**Comment by egemenatikk** [comment]
I checked my personal wiki page, made necessary changes.

- I updated my bio
- I added new skills
- I added new weekly effort table for CMPE451
- I convert my weekly effort table for CMPE352 to a closed list

**Comment by surmelienes1** [comment]
I took the proper steps to apply necessary improvements after checking [my personal wiki page](https://github.com/bounswe/bounswe2022group2/wiki/Muhammed-Enes-S%C3%BCrmeli).

* I revised the information in my biography.
* For CMPE451, I created a new weekly effort chart to properly reflect my efforts this semester.
* I turned my CMPE352 weekly effort table into a closed list and saved in the page to store my past contributions.

**Comment by codingAku** [comment]
For the new course:

> I have updated my bio and my skills
> I have turned CMPE 352 work into closed list

> I have created CMPE 451 weekly work section

**Comment by xltvy** [comment]
I have updated my wiki page, which can be reached from [here](https://github.com/bounswe/bounswe2022group2/wiki/Altay-Acar). I have made changes about:
* Updated bio with new work experience.
* Updated skills with newly gained skills.
* Divided contributions part into two parts: Contributions for CMPE 451 and Contributions for CMPE 352
* Moved every weekly contribution for the CMPE 352 class in the regarding section.

**Comment by ezgy** [comment]
I have updated my personal wiki page by:
* updating bio
* collecting CMPE352 efforts  under a dropdown menu
* adding CMPE 451 section to efforts.

**Comment by onurkomurcu** [comment]
I am also updated followings in my personal wiki page:
- CMPE352 weekly efforts were collected under one section
- New skills and interests were added
- Github account was placed top of the wiki page
- First weekly effort was added

From now on, every team member have updated wiki page. I wish us a great semester!
