### ISSUE TITLE
Update Requirements Page

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#325]
### Issue Description

One of the main tasks for us to complete this week is revising and updating the requirements of our project. 

As we discussed in our [first meeting of CMPE451](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%231-of-451-(08.10.2022)), @xltvy created an issue for all of our members to discuss what to change in our project's requirements. You can view this issue in #323 . 

Then, we decided to assign all titles to our members, as equally as possible. Now, every member of our team will update the part of the requirements they are responsible.

### Step Details

Steps that will be performed:
- [x] Glossary Update -> @codingAku 
- [x] User-User Interaction -> @codingAku 
- [x] Chat-Forum Swap -> @Koraytkn 
- [x] Profile Page -> @hasancan-code & @gokayyildiz 
- [x] Authentication -> @bahricanyesil 
- [x] Achievements & Badges -> @onurkomurcu 
- [x] User-Lecture Interaction -> @ezgy 
- [x] Lecture Structure -> @egemenatikk 
- [x] Notifications -> @surmelienes1 & @xltvy 
- [x] Non-functional requirements -> @mbatuhancelik 

### Final Actions

After all the titles in the list above are marked and our [Requirements Page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) is fully updated, we will close this issue.

### Deadline of the Issue

17.10.2022 - Monday - 23:59

### Reviewer

Altay Acar

### Deadline for the Review

18.10.2022 - Tuesday - 23:59

**Comment by egemenatikk** [comment]
In the [second meeting](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)), we decided that it would be a bit difficult for one person to edit all the requirements. So, we split all requirements into pieces and assigned them to our members, equally. Now, every member will update the part they are responsible and when all requirements are updated we will close this issue.

**Comment by egemenatikk** [comment]
In order to keep track of the progress of work, I added a list that contains titles of our requirements. As these parts are updated, we will mark them as completed and when all of them are marked we will close this issue.

**Comment by bahricanyesil** [comment]
I was the responsible to update the authentication requirements according to the our discussion in the weekly meeting. I opened an issue, took the necessary actions and shared the updates as comments. You can see the details under [the issue](https://github.com/bounswe/bounswe2022group2/issues/331).

**Comment by ezgy** [comment]
I updated the User-Lecture Interaction requirements. For details about changes made see #330

**Comment by Koraytkn** [comment]
I updated the chat-discussion-related requirements sections and diagrams accordingly, detailed explanation of the changes can be reached at specific issue [#344] (https://github.com/bounswe/bounswe2022group2/issues/344)

**Comment by onurkomurcu** [comment]
I completed the revision of the achievements requirements. Further details can be found under the issue #333.

**Comment by codingAku** [comment]
Glossary has been updated - details can be found in #335.

**Comment by egemenatikk** [comment]
I revised and updated requirements under title "Lecture Structure". You can view details in issue numbered #341 .

**Comment by xltvy** [comment]
Me and @surmelienes1 have revised the notifications section of the requirements. Any further detail can be seen from the issue #329

**Comment by onurkomurcu** [comment]
Thank you all for your contributions!
