### ISSUE TITLE
Revising the Requirements Specification: Notifications

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#329]
### Issue Description

We completed a very thorough requirement analysis for our online learning platform last semester. You may see the requirements and the glossary from [this page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).

We have made the decision to update the requirements page in line with the development of our application this semester. Every group member will review some portions of the requirements according to their assignments from our [last meeting](https://github.com/bounswe/bounswe2022group2/issues/328). For the [notifications](https://github.com/bounswe/bounswe2022group2/wiki/Requirements#12--system-requirements) part, @xltvy and I, @surmelienes1, took the responsibility for updating the requirements and, if necessary, providing information under this issue.

### Step Details

Steps that will be performed:
- [x] Visiting the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).
- [x] Examining each notification related requirement definition in light of its applicability, necessity, and value to our project.
- [x] Making any necessary remarks and recommendations under this issue as a comment.

### Final Actions

We will make the required adjustments when our discussion with @xltvy over the notification related requirements is over. The final version of the related requirements will be shown on the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) at the associated section once we are done with the documentation. As a final demonstration of our group's joint efforts, we will comment our results on the issue #325.

### Responsible People

- [x] Altay Acar
- [x] Muhammed Enes Sürmeli

### Deadline of the Issue

15.10.2022 - Saturday - 23:59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

16.10.2022 - Sunday - 23:59

### Final To-Dos

- [x] Every responsible shared an info about the sections/parts s/he has performed.

**Comment by xltvy** [comment]
### Update:
I have gone over the notifications section of our requirements specification regarding the reviews we have made in our [meeting 2](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)). Below are my suggestions upon the notifications part of the requirements specification:
***
> 1.2.2.2. The system shall notify users regarding incoming messages from their communication channels.

Since chat is no longer a part of the app as a standalone communication channel and instead it is a discussion forum now, we can simplify it like this:
> 1.2.2.2. The system shall notify users regarding any posts on the discussion forum of the lectures they take or give.
***
> 1.2.2.4. The system shall notify learners when they achieve a milestone regarding their progress with respect to a course.

Again for the simplification and the current structure of our project we can revise this as:
> 1.2.2.4. The system shall notify users when they earn an achievement.
***
> 1.2.2.5. The system shall notify learners that they should give feedback about their lecturers whose course they have completed recently.

Just a better wording suggestion:
> 1.2.2.5. The system shall notify users to give feedback about completed lectures upon completion.
***
> 1.2.2.6. The system shall notify users when other users invite them to an organized in-person meeting.

I don't think we have event invitation feature in our project. We can convert this into something like this to make it more event-relevant:
> 1.2.2.6. The system shall notify users when an event is created for the lectures they take or give.
***
> 1.2.2.7. The system shall notify learners when lecturers create polls to help them contribute to some decisions taken during the lecture.

Again a better wording suggestion:
> 1.2.2.7. The system shall notify users when a poll is created in the lectures they take.
***
> 1.2.2.8. The mobile app system shall notify mobile users in such a way that they are kept engaged.
> 1.2.2.8.1. The system shall send a notification to the users who do not open the app for at least 1 day.

1.2.2.8. is very generic and does not say about any requirements **_specification_** I believe. So, we can simply wipe it out and keep 1.2.2.8.1. by making it 1.2.2.8:
> 1.2.2.8. The system shall notify users when they do not use the application for more than one day.
***
> 1.2.2.11. The system should notify users about other users they follow.
> 1.2.2.11.1. These notifications should be on the activities or accomplishments of the people they follow.

I think we can completely wipe out this two requirements specification, since we decided to show activities on a display in our application. I do not think also notifying users will be needed. It would be an overkill.
***
Those above are my suggestions upon the already provided notifications specification. The ones that I have not mentioned are simply fine for me. Besides that I think we can discuss on adding any needed notification suggestions such as:
1. Notifying users when a user gives a feedback on their lecture upon completion.
2. Notifying users who did not complete almost done section of the registration (additional personal information, interests etc.) to complete it.

**Comment by surmelienes1** [comment]
## Information

I have examined the suggestions offered by @xltvy above and have read the notifications part of our [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) specification keeping the reviews we did in our [meeting 2](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)) in mind. I have the following recommendations about the notification section of the requirements specification: 

* Since our TA, Alper, advised us to use forums for communication purposes in our application, we should replace the phrase "communication channel" with "discussion forum" in the requirement number 1.2.2.2.
 
* To meet the customer expectations and streamline the process, we might replace the milestone schema with accomplishments for the requirement 1.2.2.4.
 
* We should adjust the wordings for the requirement 1.2.2.6 to reflect the fact that our application now has an event based approach rather than in-person or online meetings.

* By condensing the provided statement, we might make the requirement 1.2.2.7 more clear.

* We could simply remove the 1.2.2.8 requirement and substitute it with the 1.2.2.8.1 requirement after rephrasing the latter, as Altay suggested in his remark above.

* In the 1.2.2.9 requirement, we might put turn on/off instead of the switch on/off phrase because the "switch" word is often used for electrical gadgets.

* Just as Altay mentioned, I think that the 1.2.2.11 and 1.2.2.11.1 requirements should be dropped so as not to unnecessarily complicate the development part and deviate from the basis of our application. Moreover, we better remove these two requirements as we have decided to develop a different part for user-user interaction purposes.

***

## Note

Taking into consideration the Altay's suggestions above, my final list for the notification part of our requirements would be as follows:

* 1.2.2.1 Users shall get notifications from the system.
* 1.2.2.2 The system shall notify users regarding any posts on the discussion forum of the lectures they take or give.
* 1.2.2.3 The system shall notify users when other users share notes with them.
* 1.2.2.4 The system shall notify users when they earn an achievement.
* 1.2.2.5 The system shall notify users to give feedback after each completed lecture.
* 1.2.2.6 The system shall notify users when an event is created for a lecture they are taking or giving.
* 1.2.2.7 The system shall notify users when a poll is created in a lecture they are taking.
* 1.2.2.8 The system shall notify users when they do not use the application for more than one day.
* 1.2.2.9 Users shall be able to turn their notifications on or off.
* 1.2.2.10 The system shall notify users when other users follow them.

For the two additional requirements Altay mentioned above, I believe we can incorporate them into our current notification-related requirements as follows:

* The system shall notify lecturers when a user provides feedback on one of their courses.

* The system shall notify users who did not complete almost done section of the registration.

***

## Awaiting Review

@mbatuhancelik may now evaluate all of the notification-related recommendations and the issue. I will update the requirements page as needed once the review process is over, after which I will close this issue.

**Comment by egemenatikk** [comment]
Thank you for your work @xltvy and @surmelienes1. I reviewed your suggestions and did not come across with anything to correct. I think you can update "Notifications" part of the requirements page with your suggestions.

I just have one question. In our second meeting we decided to add a reporting system to discussion forum of courses. Should users be notified when they are reported, should we add a requirement about that under "Notifications" title?

**Comment by surmelienes1** [comment]
## Response

I want to start by thanking you, @egemenatikk, for your review. I will be updating the [notification related requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements#:~:text=1.2.2.,Notifications).

Your proposal for adding a new requirement is fairly reasonable and can be introduced in a proper manner, but in my opinion, it would be better if we held off on doing so for the time being in order to avoid overcomplicating the project. It is possible to add a lot more notification subjects, but it does not appear to be quite feasible to implement each one in this short period of time. However, if we do not encounter a problem in the reporting mechanisms in the later stages of the project, we can discuss the addition of the relevant notification again.

**Comment by surmelienes1** [comment]
## Final Action

I have updated and finalized the section about notifications on the Requirements page.

As we could not see a part that needs to be changed about the diagrams related to notifications, we have decided with Altay, @xltvy, to leave them as they are for the time being.

As everything is finalized, I am closing this issue now. If you have more questions or suggestions, you can reopen this issue and write your ideas as a comment.
