### ISSUE TITLE
Revising the Requirements:  User-Lecture Interaction

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#330]
### Issue Description

Some changes to the [Requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) have been determined in [Meeting 2](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)). These changes are distributed to members. This issue concerns the changes made on 1.1.3.2- User-Lecture Interaction segment of User Requirements. For information on all changes to be made, see comments under #325 

### Step Details

Steps that will be performed:
- [x] Remove or update requirements according to the discussions.
- [x] Add a new requirement if anything is missing.
- [x] Determine any additions/removals from the glossary regarding these changes.

### Final Actions

Once all the changes are determined and worded with proper syntax, a proposal will be introduced under this issue for review. After team members' validation, the requirements page will be updated accordingly.

### Deadline of the Issue

15.10.2022 - Saturday - 23:59

### Reviewer

Egemen Atik

### Deadline for the Review

16.10.2022 - Sunday - 23:59

**Comment by ezgy** [comment]
Here are the changes I am proposing:

**1.** Remove "unique" keyword and merge the following requirements:
> 1.1.3.2.1.1. Lectures shall be given a unique title during creation.
> 1.1.3.2.1.2. Lecturer shall state the lectures topic in a specified field for sake of categorization.  

**Updated:**
1.1.3.2.1.1. Users shall enter a title and topic to create a lecture.

**2.** Add requirement regarding lecture materials:
1.1.3.2.1.2 Lecturer shall be able to add polls and notes as lecture material.
1.1.3.2.1.3 Lecturer shall organize lecture material in chapters.

**3.** Remove 1.1.3.2.5.3.
> ~1.1.3.2.5.3. Created events are only specified for various courses, which means some courses may not have an event-creating ability.~

**4.** Add information regarding poll types
1.1.3.2.6 Creating Polls:
* 1.1.3.2.6.1 Lecturers shall be able to create anonymous polls, multiple answer polls, and quiz polls as part of lecture material.

**5.** Add geolocation information to requirements about events
> 1.1.3.2.5.4. Created events have a specific date, duration, and limit for the number of participants.
> 1.1.3.2.5.7. Created events will be visible on the course info page along with the date, duration, and the number of participants.  

**Updated:** 
1.1.3.2.5.3.  Created events should have a specific date, duration, location and limit for the number of participants.  
1.1.3.2.5.6. Created events should be visible on the course info page along with the date, duration, location and number of participants.  

**6.** Remove 1.1.3.2.5.8
> ~1.1.3.2.5.8. Enrolled students will be able to notify that they will be joining community events with a button click.~

**Comment by ezgy** [comment]
These are all the changes I've gathered from Meeting 2 notes and discussions under #323. Please review @egemenatikk before I edit the requirements. Thanks in advance :)

**Comment by egemenatikk** [comment]
Thank you for your work @ezgy. I analyzed your work. I realized you added, edited and removed the requirements under "User-Lecture Interaction" title according to our discussion in the second meeting, correctly.

In our second meeting we talked about "earning achievements after completing specific number of courses" and "reporting in discussion forums of courses". I could not decide whether we should add the requirements about these topics under this title as well, or should we add it under another title. 

Other than that, I think "User-Lecture Interaction" section of our requirements is ready to be updated by your suggestions above.

**Comment by ezgy** [comment]
> In our second meeting we talked about "earning achievements after completing specific number of courses" and "reporting in discussion forums of courses". I could not decide whether we should add the requirements about these topics under this title as well, or should we add it under another title.

@egemenatikk since there is a section "Achievements and Badges" (see #333) I think how achievements are earned should be considered under that section and also adding here would be repetitive.  What do you think @onurkomurcu ?

Similarly for reporting I wasn't sure if it should be handled under user-lecture interaction or under the relevant section under system requirements, but I can add the following requirement under the section taking lectures:
- Users shall be able to report inappropriate comments in the discussion forum of the lecture.

Thank you for the detailed review. Do you think this addition is enough?

**Comment by egemenatikk** [comment]
Yes, I think you can update the "User-Lecture Interaction" part of the requirements with your suggestions. Thank you for your work again.

**Comment by ezgy** [comment]
The changes have been added to the [Requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).
