### ISSUE TITLE
Revising the Requirements: Authentication

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#331]
### Issue Description

We have already reviewed our requirements in the previous week. All team members read and analyzed our requirements from the previous semester. We also went over all the suggestions in our last regular weekly meeting (meeting notes). Now, it's time to update the related points with the suggested reviews. I took the responsibility of updating the requirements of authentication (especially signup and login) functionalities. I will check and update all related requirements according to our discussions and decisions.

### Step Details

Steps that will be performed:
- [x] Visit the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).
- [x] Check and note all decided revisions that should be performed for authentication functionalities.
- [x] Analyse each authentication-related requirement in terms of its applicability, necessity, and value to our project.

### Final Actions

- [ ] The final version of the related requirements will be shown on the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) in the associated section once we are done with the documentation.
- [x] Share the changes under this issue as a comment and share them with the other teammates.

### Deadline of the Issue

15.10.2022 - Saturday - 23:59

### Reviewer

Onur Kömürcü - @onurkomurcu 

### Deadline for the Review

15.10.2022 - Sunday - 23:59

**Comment by bahricanyesil** [comment]
I visited the requirements page and read all authentication-related requirements. I will propose the changes I suggested for the things we talked about in our last meeting under this issue as comments.

**Comment by bahricanyesil** [comment]
## 1st Suggestion

We should change the first item in the signup section from
1.1.1.1.1. Guests shall enter their username, email address, and strong passwords to be able to signup. These are the required information that users have to provide to enter the app.
To
1.1.1.1.1. Guests shall enter an unused username, an unregistered email address, and a strong password to signup.

The reason for this change is that we should indicate that the username and email the user entered should not be used before. The second sentence in the requirement seems unnecessary. Therefore, it's also removed.

**Comment by bahricanyesil** [comment]
## 2nd Suggestion
We should change the second item in the signup section from
1.1.1.1.2. Guests shall check the checkbox which indicates the agreement text of the privacy policy and terms&conditions to be able to signup. It is a required action.
To
1.1.1.1.2. Guests shall agree to the privacy policy and terms&conditions to signup.

Since we shouldn't go into the design and implementation-related details, I removed the checkbox part and explanation regarding that.

**Comment by bahricanyesil** [comment]
## 3rd Suggestion
We should changethe first item of the login section from
1.1.1.2.1. Users shall provide their usernames and passwords to be able to log in if they logged out or they are kicked out due to long inactivity.
To
1.1.1.2.1. Users shall provide their usernames and passwords to log in.

We don't have to give details about why the user is trying to log in. The second part seemed unnecessary and I decided to remove it.

**Comment by bahricanyesil** [comment]
## 4th Suggestion
We should change the item in the logout section from
1.1.1.5.1. Users shall be able to log out whenever they want from the settings screen.
To
1.1.1.5.1. Users shall be able to log out.

Again, we shouldn't give details about the design and implementation parts. Stating only the ability to log out is enough without explaining how to do it.

**Comment by bahricanyesil** [comment]
## 5th Suggestion
We should change the password section from multiple of requirements a single requirement like
To
1.1.1.6.1. Users shall be able to change their passwords by verifying their emails.

Having so much implementation-related information and details is not a desired thing in the requirements. Therefore, I removed detailed items and wrote a single requirement.

**Comment by bahricanyesil** [comment]
## 6th and Final Suggestion

Additionally, we should change the item in the delete account section from
1.2.7.1. System shall allow users to delete their accounts whenever they want from the settings screen.
To
1.2.7.1. System shall allow users to delete their accounts.

The reason for this change is the fact that we shouldn't give details about designs and screens.

**Comment by bahricanyesil** [comment]
I have re-read all authentication-related requirements and proposed my suggestions as compatible with our discussion in our weekly meeting under this issue item by item.

Now all suggestions and the issue are ready to be reviewed by @onurkomurcu. If the review is completed, I will make the necessary changes in the requirements page and then close the issue.

**Comment by onurkomurcu** [comment]
Updated parts look much more professional and appropriate. Thank you, @bahricanyesil!

**Comment by bahricanyesil** [comment]
Thank you for the review @onurkomurcu. I made the necessary updates on the requirements page. Therefore, I'm closing the issue.
