### ISSUE TITLE
Revising the Requirements: Achievements and Badges

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#333]
### Issue Description

Whole adjustment of the requirements were discussed and finalized in the [Meeting 2](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)). I am responsible for the achievements and badges related requirements. I will change the requirements according to the meeting notes. The work will be reviewed by the reviewer before I transfer them to the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements). 

After the requirements are updated, I will check the diagrams if it needs any changes.

### Step Details

Steps that will be performed:
- [x] Find the achievements and badges related requirements
- [x] Change them according to meeting notes
- [x] Check there is any conflict, misspell or double space
- [x] Update your changes regarding to the review, if any

### Final Actions

After the work is done, changed parts of the requirements can be seen under this issue.

### Deadline of the Issue

15.10.2022 - Saturday - 23.59

### Reviewer

Ecenur Sezer

### Deadline for the Review

16.10.2022 - Sunday - 23:59

**Comment by onurkomurcu** [comment]
Previous Achievements requirements as follows:
> 1.1.2.11. Achievements
> - 1.1.2.11.1. Users shall view the achievements they earned from the courses they have studied in the achievements section of their profile pages.
> - 1.1.2.11.2. Users shall be able to change the achievements, which are displayed in the achievements section of their profile pages.
> - 1.1.2.11.3. Users shall be able to view the most rare achievement they have earned based on the earning rate of this achievement across the whole platform, from the achievements section.

- For the sake of simplicity, there is no need to set some achievements private. For this reason, we can delete the 1.1.2.11.2.
- We decided that achievement system will be default all across the platform. If user complete specific amount of courses about any topic, s/he will earn achievement for that and these achievements will be displayed in his/her profile page.

When these changes were considered, my final work for the achievements requirements as follows:

> 1.1.2.11. Achievements
> - 1.1.2.11.1. Users shall view the achievements they earned from the courses they have studied in the achievements section of their profile pages.
> - 1.1.2.11.2 Users shall be able to earn achievements via completion of specific amount of courses with related topic.

***

Apart from these changes, following requirements should be also changed:
> 1.1.2.10. Interests and Knowledge
> - 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.
> - 1.1.2.10.2. Users shall view the knowledge base, consisting the courses, they have successfully completed.
> - 1.1.2.10.3. Users shall view the total number of badges they have earned for each course in their knowledge base.
> - 1.1.2.10.4. Users shall view the total number of completed courses and earned badges in their knowledge base.

- It was decided that there will be no badges. Achievements will be enough to provide learner's progress. Since achievements related requirements mentioned under the 1.1.2.11. Achievements, we can simply delete the last 2 requirements of 1.1.2.10. Interests and Knowledge.

Following would be the final version for the  Interests and Knowledge requirements:
> 1.1.2.10. Interests and Knowledge
> - 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.
> - 1.1.2.10.2. Users shall view the knowledge base, consisting the courses, they have successfully completed.

**Comment by onurkomurcu** [comment]
When the work is reviewed by @codingAku, I will look up to the use case diagram to change related use cases.

**Comment by codingAku** [comment]
Hello, thank you for quick revise! I do see just a couple of minor issues after checking meeting notes and your work.
1.1.2.11.1. Users shall view the achievements **they earned from the courses** they have studied in the achievements section of their profile pages.
I believe users don't earn achievements from courses, this was an early definition since in 352 class we have planned it this way. since 1.1.2.11.2 already explains how to earn, I think removing the bold part, and changing the order of 1.1.2.11.1 & 1.1.2.11.2 would be clearify the achievements completely.

Interests and Knowledge looks legit, although I believe that section will completely be moved to profile page. So when @gokayyildiz & @hasancan-code opens the revising profile page issue, we should link it with this one.

**Comment by onurkomurcu** [comment]
I missed that part. We can change 1.1.2.10.1 requirement with this.

> Users shall view the achievements they earned from the courses in the achievements section of their profile pages.

As you said, we can also change the order of them. By this way, it would be much clearer.

 I will mention this issue under the revising profile page issue when it is opened to prevent any confusion. 
 
 Thank you for your review, @codingAku!

**Comment by gokayyildiz** [comment]
As I mentioned in issue #345, we can separate the 

> 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.

into two requirements since it seems to emphasize two different operations during the use of the application.

**Comment by onurkomurcu** [comment]
> As I mentioned in issue #345, we can separate the
> 
> > 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.
> 
> into two requirements since it seems to emphasize two different operations during the use of the application.

It would be great. I will split that part into two part as following:

> 1.1.2.10.1 Users shall identify their interest areas
> 1.1.2.10.2 Users shall display their interest areas in their profile pages

**Comment by onurkomurcu** [comment]
According to these changes, diagrams will be changed. Progress of the diagram update can be tracked from the issue #346. 

From now on, everything seems adequate. If there will be any further suggestions, you can reopen this issue.
