### ISSUE TITLE
Revising the Requirements : User - User Interaction

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#334]
### Issue Description

After a very detailed discussion about our requirements in our weekly meeting, we have finalized how to update it. Now, we need to re-write and organize requirements section based on job-share. In that context, I have the responsibility to revise User - User Interaction section.  This issue is related to #325.

### Step Details

Steps that will be performed:
- [x] Add / remove / change the requirements that does not belong / missing in our project in User - User Interaction section.

### Final Actions

After the revision is complete, I will get it reviewed so we can secure it's fully compatible with our project goals.

### Deadline of the Issue

14.10.2022 - 23:59

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

15.10.2022 - 23:59

**Comment by codingAku** [comment]
The revision is complete. Here are the new User - User Interaction Requirements : 
* 1.1.3.1.1. Users shall see each others profiles. 
* 1.1.3.1.2. Users shall be able to follow each other.
* 1.1.3.1.3. Users shall see the information of people they follow; achievements and activities.
* 1.1.3.1.4. Users shall be able to share notes with each other.
* 1.1.3.1.5. Users shall be able to block other users.
* 1.1.3.1.6. Users could prevent other users to see their profile by blocking them.

**Comment by ezgy** [comment]
@codingAku I think the changes you made reflect what we discussed in the meeting. I just have one suggestion:
We mentioned the lack of requirements regarding private/public profiles. Since how much information we share with other users (that do not follow yet) is about user-user interaction, I think that could also be mentioned under this section.

**Comment by codingAku** [comment]
> @codingAku I think the changes you made reflect what we discussed in the meeting. I just have one suggestion: We mentioned the lack of requirements regarding private/public profiles. Since how much information we share with other users (that do not follow yet) is about user-user interaction, I think that could also be mentioned under this section.

Hello @ezgy , yes I have thought about them, but then I see they are mentioned in Profile page. And blocking is already mentioned, so I think it should be in profile page only to prevent redundancy.

**Comment by Koraytkn** [comment]
Hi Ecenur, I was reviewing the requirements in order to if anything related to one-to-one chat still exists and I have seen "1.1.3.1.4. Users shall be able to share notes with each other." I just wanted to ask if this requirement is still accurate since chat was how the users were supposed to share notes as far as I understand, now how will they be able to share notes? Thanks in advance, I didn't change this requirement without consulting you first @codingAku.

**Comment by ezgy** [comment]
> Hi Ecenur, I was reviewing the requirements in order to see if anything related to one-to-one chat still exists and I have seen "1.1.3.1.4. Users shall be able to share notes with each other." I just wanted to ask if this requirement is still accurate since chat was how the users were supposed to share notes as far as I understand, now how will they be able to share notes? Thanks in advance, I didn't change this requirement without consulting you first @codingAku.

Sharing notes is still an available feature, we discussed it in the meeting as "similar to sharing a note on iphone notes app" Users will be able to add another user to the note as a way of sharing. This action happens on the note page and not with the chat feature.
It is similar to this:
![image](https://user-images.githubusercontent.com/56553280/195994291-c56af463-e10e-4071-b39d-df36572d8be4.png)

**Comment by ezgy** [comment]
> > @codingAku I think the changes you made reflect what we discussed in the meeting. I just have one suggestion: We mentioned the lack of requirements regarding private/public profiles. Since how much information we share with other users (that do not follow yet) is about user-user interaction, I think that could also be mentioned under this section.
> 
> Hello @ezgy , yes I have thought about them, but then I see they are mentioned in Profile page. And blocking is already mentioned, so I think it should be in profile page only to prevent redundancy.

I agree that it makes sense to include this in the profile page section. I will remind the responsible people so that it's not missing in the end. With this, I think this issue is complete.
