### ISSUE TITLE
Revising the Requirements : Glossary

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#335]
### Issue Description

After a very detailed discussion about our requirements in our weekly meeting, we have finalized how to update it. Now, we need to re-write and organize requirements section based on job-share. In that context, I have the responsibility to revise Glossary section.  This issue is related to #325.

### Step Details

Steps that will be performed:
- [x]  Add / remove / change the descriptions that does not belong / missing in our project in Glossary section.

### Final Actions

After the revision is complete, I will get it reviewed so we can secure it's fully compatible with our project goals.

### Deadline of the Issue

14.10.2022 - 23:59

### Reviewer

Koray Tekin - @Koraytkn 

### Deadline for the Review

15.10.2022 - 23:59

**Comment by codingAku** [comment]
The revision of glossary is complete. Here are the changes:
ADDED  **Forum:** _Communication platform provided within the course in order for the learners and the lecturer to interact._
ADDED  **Progress:** _A state showing how many chapters in a lesson has been completed._
REMOVED **Badge**
UPDATED  **Message:** _A piece of information that is sent through Forum which contains letters and emojis._

**Comment by bahricanyesil** [comment]
Thanks for your work @codingAku. Can you please add "strong password" to the glossary as something like:

> Strong password: A password whose length is at least 8 and which contains at least one number, one upper and one lower case letter.

**Comment by Koraytkn** [comment]
As far as I understand you will review this issue once more after the [generic](https://github.com/bounswe/bounswe2022group2/issues/325) issue is complete, as a new member I do benefit from the glossary more than anyone I guess; so once the other sub-issues are complete and you review this issue I will read all of the definitions and also check the updates you have made. Thank you for your contributions @codingAku

**Comment by codingAku** [comment]
Hello, @bahricanyesil and @Koraytkn , the strong password is updated as  **A password whose length is at least 8 and which contains at least one number, one upper and one lower case letter.**

**Comment by egemenatikk** [comment]
Thank you for your work @codingAku, I just have one little suggestion. Since we decided in our second meeting that lecturer of a course will automatically be admin of the course and lecturer can give admin features to other users, should we change 

> Administrator: User with additional priveleges in a course, determined by the course creator.

to something like

> Administrator: Users with additional priveleges in a course, lecturer of the course (automatically) and users determined by the lecturer of the course (optionally).

**Comment by codingAku** [comment]
Good point, @egemenatikk. I did made the necessary changes. The most updated version now is this:
**User with additional privileges in a course, the course admin is the course creator by default. Additional admins can be determined by the course creator optionally**
I believe the issue can be closed now. Feel free to re-open for additional reviews.
