### ISSUE TITLE
Revising the Diagrams based on User -  User Interaction

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#336]
### Issue Description

After a very detailed discussion about our requirements in our weekly meeting, we have finalized how to update it. Now, we need to re-write and organize diagrams section according to new requirements based on job-share. In that context, I have the responsibility to revise the diagrams based on User - User Interaction requirements.

### Step Details

Steps that will be performed:
- [x] Revise the diagrams based on new requirements.

### Final Actions

After the revising is complete, a full review is needed.

### Deadline of the Issue

14.10.2022 - 23:59

### Reviewer

Bahrican Yesil - @bahricanyesil 

### Deadline for the Review

15.10.2022 - 23:59

**Comment by codingAku** [comment]
Main change in User - User Interaction is following a user and ability to see their achivements in their profile.Sequience diagram does not contain any specific section based on this, however use case & class diagram needed update.
Down below you can see the new versions of use case and class diagrams.
Important Note: Users can only see profile info of others when they are not following.
![latest](https://user-images.githubusercontent.com/64018144/195837084-b926fb65-7609-4cd1-a2c3-557f378bb5f0.jpg)
![class](https://user-images.githubusercontent.com/64018144/195837126-76c8294a-47e6-43e8-ba5d-66ac506a1190.jpg)

**Comment by bahricanyesil** [comment]
Thanks for your work @codingAku. First of all, can you update one sentence in your comment above: "Important Note: Users can only see profile info of others when they are not following."? I guess this should be "... others when they are following." if I have not missed something.

**Comment by codingAku** [comment]
> Thanks for your work @codingAku. First of all, can you update one sentence in your comment above: "Important Note: Users can only see profile info of others when they are not following."? I guess this should be "... others when they are following." if I have not missed something.

Hello, actually the sentence means that, users can only see profile info, and achievements and rest of the profile is only visible when they are following.

**Comment by bahricanyesil** [comment]
> > Thanks for your work @codingAku. First of all, can you update one sentence in your comment above: "Important Note: Users can only see profile info of others when they are not following."? I guess this should be "... others when they are following." if I have not missed something.
> 
> Hello, actually the sentence means that, users can only see profile info, and achievements and rest of the profile is only visible when they are following.

I mean the "not following" part. Am I missing something? Can you please remove "not" in that sentence?

**Comment by bahricanyesil** [comment]
Secondly, I have read the newly added requirements by you from [this issue](https://github.com/bounswe/bounswe2022group2/issues/334). I couldn't see any updates in the **class diagram** regarding to the following requirements (and also I couldn't see any previous implementations regarding these requirements):
- 1.1.3.1.4. Users shall be able to share notes with each other.
- 1.1.3.1.5. Users shall be able to block other users.

Here're my suggestions:
- For "1.1.3.1.4.": add the "shared_users: List<UID>" field to the "Note" class
- For "1.1.3.1.5.": add the "blocked_users: List<UID>" field to the "User" or "Profile" class, not sure which one fits best for now.

**Comment by bahricanyesil** [comment]
Finally, regarding to the use-case diagram updates:

- I saw that the "share note" functionality is added to the "chat" box previously. Can you move and link that functionality with the "note" box?
- Can you add functionality to "block users" just as "following users" regarding requirement 1.1.3.1.5. you added.

**Comment by codingAku** [comment]
Hello again, @bahricanyesil . Thank you for your valuable contribution. The class diagram has been updated with your advises, now:
1- User class have a list of blocked users.
2- Note class has shared_users list.
Changes on user diagram are down below. Share notes have been removed from discussion section.
![notes](https://user-images.githubusercontent.com/64018144/196045246-b53a0582-b350-4eb6-8047-3f4aab18f84b.png)
![block](https://user-images.githubusercontent.com/64018144/196045264-0616c5e9-e199-4c40-9328-0483dcfaba0c.png)

**Comment by bahricanyesil** [comment]
Thank you for the changes @codingAku. I don't see any additional improvement. So, I'm closing the issue.
