### ISSUE TITLE
Revising the Diagrams based on Signup&Login

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#337]
### Issue Description

We have a detailed discussion about our requirements in our last weekly meeting. We have determined the requirements to be updated and how to do updates. Now, we will revise and re-organize the diagrams according to the new requirement updates. Since I am the responsible person for updating the signup&login requirements, I will also update the diagrams related to those parts. You can see the details of the requirement update issue [here](https://github.com/bounswe/bounswe2022group2/issues/331).

### Step Details

Steps that will be performed:
- [x] Control the class diagram and detect the points that need to be updated (if there are any) with the update of requirements
- [x] Control the sequence and use-case diagrams and make the necessary updates (if any) with the update of requirements

### Final Actions

- [x] The final version of the diagrams will be available to be seen in their corresponding documents:
[Class Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram)
[Use-case Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Use-Case-Diagram)
[Sequence Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Sequence-Diagram)
- [x] Share the changes under this issue as a comment. So that, the other teammates will be informed.

### Deadline of the Issue

15.10.2022 - Saturday - 23:59

### Reviewer

Ecenur Sezer - @codingAku 

### Deadline for the Review

16.10.2022 - Sunday - 23:59

**Comment by bahricanyesil** [comment]
## Update

I analyzed the sequence diagram but couldn't see anything to update.

**Comment by bahricanyesil** [comment]
## Class Diagram Update

I analyzed the class diagram but couldn't detect anything to update.

**Comment by bahricanyesil** [comment]
## Ready for Review

I completed all steps mentioned, made the necessary updates, and shared them as comments under the issue. Now the issue is ready to be reviewed by @codingAku.

**Comment by codingAku** [comment]
I have checked the new Signup&Login requirements, and then compare them to use-case diagram. It looks adequate for now, thank you.
