### ISSUE TITLE
Revising the non functional requirements

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#339]
### Issue Description

As discussed in #323, updating our non functional requirements is required.

I will be going over them fix some of those in accordance with our second meeting.

Updates to the requirements will be updated in this issue.  

### Step Details

Steps that will be performed:
- [x] Update the requirements
- [x] Get the members approval for the updates
- [x] Update the wiki page

### Final Actions

Upon completion, I will check the class and sequence diagrams for necessary updates.

I believe use case diagrams wont be affected from nf requirements but I will be on look up for those too.

### Deadline of the Issue

15.10.2022 Saturday 23:59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

17.10.2022 Monday 23:59

**Comment by mbatuhancelik** [comment]
> 2.1.1. System should have both a Web interface and an Android application. These two interfaces must provide same features but different interactions.

To define different interactions:

> 2.1.1. System should have both a Web interface and an Android application, both interfaces shall contain same features while providing a user experience specific to their devices.

**Comment by mbatuhancelik** [comment]
> * 2.1.1.1. Mobile App should be designed to keep mobile users engaged.

As this is too vague, removed.

**Comment by mbatuhancelik** [comment]
2.1.3. is updated as 

> System should support English language.

 > * 2.4.1 The system should be able to handle at least 10.000 users and 500 user actions simultaneously. 

This is removed as the user activity is not easily defined. System performance will be measured using response time as stated in: 

 > * 2.4.2 The system should have a response time of at most 2.0 seconds excluding network based delay.


> * 2.5.2 The system should place more important things like headers or logos in the top left corner. The logo serves as a landmark that orients users when they first land on a page and helps them identify the website they are visiting.

This is part of the user interface design, and shall not be in requirements.

**Comment by mbatuhancelik** [comment]
> * 2.6.1 The system should get backups and send them off-site at regular intervals for the possibility of disasters.

I am leaving this as a side note here: 
If we are to use a DB service from a cloud vendor, this shall change too.

>  2.6.2 When the disaster occurs, the backup protocol should be activated; the last taken backup will be uploaded and the site will be updated in a short time.

For the same reason, changing this to:

>  2.6.2 System shall be able to reinitialize itself and continue functioning in case of an unexpected shutdown.

And, finally adding this: 

>  2.6.3 System shall keep logs regarding the unexpected shutdown.

**Comment by surmelienes1** [comment]
## Review

I want to start by thanking you, @mbatuhancelik, for your thorough examination and condensing of the non-functional requirements.

Except for the 2.1.1 requirement, all of the modifications you made appear to be very suitable and sufficient to me. However, I believe it would be more suitable to split the 2.1.1 requirement into two distinct requirements taking into account the guidelines for constructing the requirement.

In addition to these, although I cannot see them in what you suggested above, it would also be more suitable to divide the 2.5.1 and 2.5.2 requirements under the 2.5 "Usability" title into four separate requirements. Finally, I believe it would be more preferable to summarize requirement 2.5.3 as "The system should have a well-chosen typeface that should be readable and clean" to make it [atomic](https://www.guru99.com/learn-software-requirements-analysis-with-case-study.html#:~:text=starting%20with%20Atomic.-,Atomic,-So%20each%20and) and less vague.

**Comment by bahricanyesil** [comment]
Adding a requirement related to logs is a good idea, thank you @mbatuhancelik.

**Comment by mbatuhancelik** [comment]
2.1.1 is divided as: 

> * 2.1.1. System should have a Website interface that provides an web specific user experience.
> * 2.1.2. System should have a Android application interface that provides an mobile specific user experience.

2.5.1 is updated as you suggested.

2.5.2 is more strictly defined as: 

> * 2.5.2 The system should provide a direct feedback mechanism. Upon interaction, user shall be informed about success or failure of their action. 

Notice that this is a hard requirement for front, back, and mobile parts of the system, so I believe keeping it intact would keep our requirements cleaner.

**Comment by mbatuhancelik** [comment]
About 2.5.1, I suggest removing it since we cannot measure "user friendly interface"

**Comment by surmelienes1** [comment]
## Conclusion

Thank you, @mbatuhancelik, for your careful inspection of the non-functional requirements.

I have reviwed your updated and finalized sections of the non-functional requirements. I do not have anything to add right now. About 2.5.1, I suggest leaving as it is since the second statement explains what "user friendly interface" means.

As everything is finalized, I am closing this issue now. If you have more questions or suggestions, you can reopen this issue and write your ideas as a comment.
