### ISSUE TITLE
Revising the Requirements: Lecture Structure

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#341]
### Issue Description

Last week, we read all requirements, analyzed our diagrams and came up with suggestions to make them better as our main task. Then, in our [second meeting](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)) we discussed our suggestions, after that we shared parts of requirements page to edit them. I am assigned by updating the Lecture Structure.

### Step Details

Steps that will be performed:
- [x] Check the Lecture Structure requirements
- [x] Decide what to keep, what to remove, what to add
- [ ] Finalise the Lecture Structure requirements according to review

### Final Actions

I will share my intended suggestions here, edit them according to review if necessary. After my reviewer gives permission I will update the Lecture Structure requirements in our [Requirements Wiki Page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).

### Deadline of the Issue

15.10.2022 - Saturday - 23:59

### Reviewer

Altay Acar

### Deadline for the Review

15.10.2022 - Sunday - 23:59

**Comment by egemenatikk** [comment]
> Lectures shall deliver lecture material in text, images, and embedded videos.

My first suggestion is removing "embedded videos" from this requirement. We decided to use embedded videos as a "nice to have" feature, so it is not required but we can add it if we have time left at the end of semester.

**Comment by egemenatikk** [comment]
Secondly, I suggest to add a requirement:

> 1.1.4.5. Lecturer of a course will be admin of the course automatically.

**Comment by egemenatikk** [comment]
We also need to add the following requirements according to decision we took in our meeting and PS hour:

> 1.1.4.7. Every lecture shall have a general discussion forum.
> 1.1.4.8. Every lecture shall have a discussion forum per chapter.

**Comment by egemenatikk** [comment]
I guess we can add the following requirement under this title as well:

> 1.1.4.9. Lecture shall be able to navigate the learners to their annotations and notes.

**Comment by xltvy** [comment]
> Secondly, I suggest to add these requirements:
> 
> > 1.1.4.5. Lecturer of a lecture shall be the admin of the lecture automatically.
> > 1.1.4.6. Lecturer of a lecture shall be able to add additional admins to the lecture.
> 
> I could not decide where should we add these requirements, though. Would adding these to "Lecture" title under "System Requirements" be more accurate?

I think 1.1.4.5. is a system requirement, we can use it under the section of 1.2.4. Lecture and make it like: "The system shall assign the user who creates the lecture as the admin of the lecture automatically."

Second one is user requirement I believe. So, making it 1.1.4.5. will be adequate.

**Comment by xltvy** [comment]
> I guess we can add the following requirement under this title as well:
> 
> > 1.1.4.9. Lecture shall be able to navigate the learners to their annotations and notes.

What did you mean by navigating the learners to their annotations and notes? I think we can make it more specific/clear if we add it to our requirements specification.

**Comment by egemenatikk** [comment]
> > I guess we can add the following requirement under this title as well:
> > > 1.1.4.9. Lecture shall be able to navigate the learners to their annotations and notes.
> 
> What did you mean by navigating the learners to their annotations and notes? I think we can make it more specific/clear if we add it to our requirements specification.

You are right, we can fix it as follows:

1.1.4.9. Annotations and notes shall be viewable from inside lectures.

**Comment by xltvy** [comment]
I think it is all set and done right know. Thank you for your good work, closing #341
