### ISSUE TITLE
Revising the Diagrams based on User - Lecture Interaction 

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#343]
### Issue Description

Throughout the week some changes have been made to the Requirements. Following these changes, the design diagrams should be updated accordingly to match them. This issue corresponds to updating the diagrams in accordance with changes in User-Lecture interaction. For the updates on these requirements see #330.  

### Step Details

Steps that will be performed:
- [x] Revise the diagrams based on new requirements.

### Final Actions

Once the changes are determined, [Class Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram),[Use-case Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Use-Case-Diagram) and [Sequence Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Sequence-Diagram) should be updated accordingly. 

### Deadline of the Issue

15.10.2022 - Saturday - 23:59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

16.10.2022 - Sunday - 23:59

**Comment by ezgy** [comment]
For Use-Case Diagram:
- Location was added to provided information under Create Event case.
- Reporting other users should be added under the discussion section, but chat has not been updated to discussion yet.

For Sequence Diagram, I saw no changes to be made. 

For Class Diagram:
 - Under Enrollment, removed the following:
 -quiz_id: UID
-poll_id: UID
-event_id: UID
-chapter_id: UID
-chapters: List<Chapter> 
-achievements: List<Achievement>
-badges: List<Achievement>
-event_date: Date
-course_materials: List<Course_Material>
-event_duration: Double
-topics: List<Topic>
I believe this information should be kept in Event/Course classes. Enrollment class should only be responsible for connecting a User to a Course.  Also badges have been removed. 
- Under enrollment the following should be added:
-user_id: UID
- I did not remove the corresponding get methods, I believe the chain of information flow would be better determined by the Backend team.
- Report Class should be connected to discussion when that part is completed.

**Comment by egemenatikk** [comment]
Thank you for your work @ezgy. I agree with your changes in both use case diagram and class diagram. Noticed that you kept Notes: List<Note> in Enrollment class, I agree with that as well.

I have nothing to add or change to your suggestions.
