### ISSUE TITLE
Revising the Requirements: Chat to forum Transformation

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#344]
### Issue Description

In the second weekly meeting of our group, we discussed possible updates for requirements and diagrams. One of the outcomes was to remove the one-to-one chat functionality with discussions specific to lectures and chapters of a course. I am the responsible person for updating the requirements and relevant diagrams accordingly. This issue is related to the generic requirements review [issue](https://github.com/bounswe/bounswe2022group2/issues/325).

### Step Details

Steps that will be performed:
- [x] Editing the requirements.
- [x] Editing the class diagram.
- [x] Editing the use case diagram.
- [x] Editing the sequence diagram.
- [x] Checking other requirements sections for any requirement mentioning chat functionality.

### Final Actions

After this issue is over, other team members will be informed via the [generic issue](https://github.com/bounswe/bounswe2022group2/issues/325).

### Deadline of the Issue

15.10.2022 - 23.59

### Reviewer

Hasan Can Erol

### Deadline for the Review

16.10.2022 - 23.59

**Comment by Koraytkn** [comment]
I have removed the chat requirements section and replaced it with forum/discussion requirements. Section 1.2.5 under the requirements title is now updated @hasancan-code

**Comment by Koraytkn** [comment]
I have updated the class diagram and the corresponding [wiki page](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram)

**Comment by Koraytkn** [comment]
I have updated the Use Case Diagram and the corresponding [wiki page](https://github.com/bounswe/bounswe2022group2/wiki/Use-Case-Diagram)

**Comment by Koraytkn** [comment]
I have removed the chat-related sequence diagram part and added a new sequence namely "create an entry" the new version of the sequence diagram can be seen [here](https://github.com/bounswe/bounswe2022group2/wiki/Sequence-Diagram)

**Comment by Koraytkn** [comment]
I am adding a  sub-requirement to:
***
>User-Lecture Interaction

part since the creating discussion and adding entry requirements now need to be specified. @hasancan-code I would appreciate review, especially on this part since I was not in the team during the initialization of requirements. Thanks!

**Comment by Koraytkn** [comment]
Under the Functional Requirements title, 1.1.2.3.7 is now live namely "Lecture Discussions".

**Comment by hasancan-code** [comment]
First of all, I appreciate your effort but I've things to ask. I did not exactly understand why we needed a Discussion Class. How is the task provided by Discussion Class different from what the database does? 
For the sequence diagram, I think we can go with the user, discussion engine, and database. When the user posts an entry, post goes with the postEntry to the Discussion Engine and goes database with the forwardEntry method. For getting entries, the process can be done backward. In this case, we are designing just the creating entry part so I think we do not need to do this.

**Comment by hasancan-code** [comment]
In addition, the requirements seem complete to me.
