### ISSUE TITLE
Revising the Requirements: Profile Page

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#345]
### Issue Description

We discussed on the updates for the requirements and diagrams of our project before starting the implementation as a team in the second weekly meeting. After the discussions, there are related parts that need to be updated for the requirements related to the Profile Page. @hasancan-code and I, @gokayyildiz are responsible for updating the requirements accordingly. This issue is also related to the issue which is about generic requirements review [issue](https://github.com/bounswe/bounswe2022group2/issues/325).

### Step Details

Steps that will be performed:
- [x] Going over the requirements page
- [x] Examining each requirement which is related to the profile page and questioning its feasibility for the project
- [x] Making recommendations for possible changes as comment under this issue

### Responsible People
- [x] Hasan Can Erol
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

15.10.2022 - Saturday- 23.59

### Reviewer

Bahrican Yesil

### Deadline for the Review

16.10.2022 - Sunday- 23.59

**Comment by gokayyildiz** [comment]
I reviewed the first part of Profile related requirements and these are my comments about them
***
> 1.1.2.2. Users shall be able to edit their profile page

Is it editing the bio, avatar kind of thing, or editing the structure of the profile page? If it is just editing these simple features, we can delete this requirement because the bio and avatar edit requirements can be given below.

***

> 1.1.2.3. Full name of the users shall be able to seen on their profile pages.

As I see from the sign-up requirements full name of the user has not been asked by the signing-up process. Is it a requirement for the user to provide a full name or optional? If it is the case we should a requirement like: 

> Users shall provide their full name before the first login 

or can be added to the sign-up requirement as

> Users shall be required to enter full name during sign-up.

or we can delete this requirement and provide their username on profile page.

***
> 1.1.2.6. Users shall have a bio in their profile pages.

can be corrected grammatically as 

> 1.1.2.6. Users shall have a bio on their profile pages.

and if requirement 1.1.2.2 is deleted,  we can add this as a requirement.

> Users shall be able to update their bio.

****

> 1.1.2.7. Users shall have a "My Events" section on their profile pages.

Can be updated after the final decision on events.
 
***

> 1.1.2.8. Users who are qualified as "Lecturer" will see the events they have organized on their "My Events" section with the headline: "You are the organizer!".

> 1.1.2.9. Users who are qualified as "Learners" will see the events they are participating in on their "My Events" section with the headline: "You are participating!".


These should be deleted

**Comment by gokayyildiz** [comment]
Comments for the requirements under the Interest & Knowladge topic
***
> 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.
we can separate this into two requirements like
> Users shall be able to identify their interest areas.
> Interest areas shall be displayed in user's profile pages.

***
> 1.1.2.10.2. Users shall view the knowledge base, consisting the courses, they have successfully completed.
> 1.1.2.10.3. Users shall view the total number of badges they have earned for each course in their knowledge base.
> 1.1.2.10.4. Users shall view the total number of completed courses and earned badges in their knowledge base.

last two can be deleted and the first one is enough the describe the whole since badge concept is omitted. 

>  Users shall be able to view the knowledge base, consisting the courses, they have successfully completed.

**Comment by bahricanyesil** [comment]
Thanks for your work @gokayyildiz. I have reviewed the points you mentioned.

> I reviewed the first part of Profile related requirements and these are my comments about them
> ***
> > 1.1.2.2. Users shall be able to edit their profile page
> 
> Is it editing the bio, avatar kind of thing, or editing the structure of the profile page? If it is just editing these simple features, we can delete this requirement because the bio and avatar edit requirements can be given below.
> 

I couldn't understand what you meant in this part.


> ***
> 
> > 1.1.2.3. Full name of the users shall be able to seen on their profile pages.
> 
> As I see from the sign-up requirements full name of the user has not been asked by the signing-up process. Is it a requirement for the user to provide a full name or optional? If it is the case we should a requirement like: 
> 
> > Users shall provide a full name at the first log-in.
>  
> or we can use the username as default full name and user can edit the full name later and add a requirement like
> 
> > Users shall be able to edit their full name.
> 
> 
> or can be added to the sign-up requirement as
> 
> > Users shall be required to enter full name during sign-up.
> 
> or we can delete this requirement and provide their username on profile page.
> 

Thank you for pointing out the above problem. I think we can just set the username as default fullnama and then allow user to edit it afterwards.

> ***
> > 1.1.2.6. Users shall have a bio in their profile pages.
> 
> can be corrected grammatically as 
> 
> > 1.1.2.6. Users shall have a bio on their profile pages.
> 
> and if requirement 1.1.2.2 is deleted,  we can add this as a requirement.
> 
> > Users shall be able to edit their bio.
> 

I think having a general requirement as "Users shall be able to edit their profile" is a better way than stating the ability to edit all parts of their profile one by one.

> ****
> 
> > 1.1.2.7. Users shall have a "My Events" section on their profile pages.
> 
> Can be updated after the final decision on events.
>  
> ***
> 
> > 1.1.2.8. Users who are qualified as "Lecturer" will see the events they have organized on their "My Events" section with the headline: "You are the organizer!".
> 
> > 1.1.2.9. Users who are qualified as "Learners" will see the events they are participating in on their "My Events" section with the headline: "You are participating!".
> 
> 
> These should be deleted 
> 

Yes, these ones should be deleted.

> ***
> 
> There is a further suggestion from @bahricanyesil in issue #323 
> 
> > Users shall be able to change their usernames with a unique username not used by anyone else.

**Comment by bahricanyesil** [comment]
> Comments for the requirements under the Interest & Knowledge topic
> ***
> > 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.
> we can separate this into two requirements like
> > Users shall be able to identify their interest areas.
> > Interest areas shall be displayed on the user's profile pages.
> 

You are right but please check whether the determination of interest areas is mentioned in the almost done section to avoid duplicate requirements.

> ***
> > 1.1.2.10.2. Users shall view the knowledge base, consisting of the courses, they have successfully completed.
> > 1.1.2.10.3. Users shall view the total number of badges they have earned for each course in their knowledge base.
> > 1.1.2.10.4. Users shall view the total number of completed courses and earned badges in their knowledge base.
> 
> The last two can be deleted and the first one is enough the describe the whole since the badge concept is omitted. 
> 
> >  Users shall be able to view the knowledge base, consisting of the courses, they have successfully completed.
> 
> 

You're right, I agree with you.

**Comment by onurkomurcu** [comment]
After the completion of my work on _**1.1.2.10. Interests and Knowledge**_ and **_1.1.2.11. Achievements_** requirements under the profile page, I updated the parts in the requirements page. You can see the details from the issue from [here](https://github.com/bounswe/bounswe2022group2/issues/333). To prevent any intersection, I want to mention here as well. If you have any additional feedbacks, I will consider them.

**Comment by gokayyildiz** [comment]
Comments on the requirements under the Learner Profile topic,

***

1.1.2.12.1. Progress Tracking, should be carried out directly under Profile Page topic without any change.

***

For the lecture notes, I could not imagine how we are planning the place it on the profile page. So, I am not sure if we should keep this requirement

> 1.1.2.12.2.2. Users shall view the most recent time of edit for each lecture note. 

I am not sure if there is a page in the application that only shows the notes and last time of edit kind of data on the page for the user. But if we are planning to make such a page, I think maybe just the title of the note is enough to be on the profile page, the other details are can be accessed through the notes page.

*** 

For the annotations, I find the requirements a bit too much to be presented on the profile page, 

> 1.1.2.12.3.3. Users shall be able to see how many annotations they have and from how many categories, from how many courses and the total number of upvotes they have received.

Do we really need that statistical data on the profile page?

***

> 1.1.2.12.3.2. Users shall be able to browse their annotations by category, by course, by history, and by upvotes they have received.

I think this requirement as a definition of filtering mechanism, category, and course can be good filters for annotations but I do not understand how to filter by history or upvotes. 

***

To me, just to offer 1.1.2.12.3.1. will be enough to offer on the profile page, the other details can be applied on a specific annotation page.

**Comment by gokayyildiz** [comment]
Comments on the requirements under the Lecturer Profile topic,

***

Since the team omit the separate profile structures for the learner and lecturer, maybe these requirements are a bit too specific for the profile page.

***

> Users shall be able to see the courses they have provided teaching material as a lecturer and their reputation in their profile pages. 

Is this reputation just mean the overall score of the lecturer, and at the current form since we do not specify if a user is a learner or lecturer, presenting such a point for each user might not be the best practice. Maybe showing the courses given as a sub-window on the profile page might be an option, then showing a rating in these sub-windows if some courses exist. 

***

> 1.1.2.13.1.2. Users shall view the cover photo, a basic bar chart that shows the rate of stars and the average rating they have received for each course in the lecturer profile section.

We can delete it because of the similar reasons that I mentioned above

***

> 1.1.2.13.1.3. Users should be able to enroll in a course, which is provided by the owner of the profile page from the lecturer profile section.

We can delete it too since we can just put a link for the course and enrollment can be done at the course page.

***
The recommendations section could be deleted since we can see this information through the course page as the instructor of the course. Also, there is a notification mechanism that notifies the lecturer of feedback, and these notifications can route the instructor to the related section on the lecture page.

**Comment by bahricanyesil** [comment]
> Comments on the requirements under the Learner Profile topic,
> 
> 1.1.2.12.1. Progress Tracking, should be carried out directly under Profile Page topic without any change.
> 
> For the lecture notes, I could not imagine how we are planning the place it on the profile page. So, I am not sure if we should keep this requirement
> 

We can show the completed course and completion ratio or some related statistics. It didn't seem unreasonable to me. However, we may change it to "Users shall be able to track their progress."
Because we need a subject and shouldn't give design related details. Can you update this requirement to a most appropriate form @gokayyildiz?

> > 1.1.2.12.2.2. Users shall view the most recent time of edit for each lecture note.
> 
> I am not sure if there is a page in the application that only shows the notes and last time of edit kind of data on the page for the user. But if we are planning to make such a page, I think maybe just the title of the note is enough to be on the profile page, the other details are can be accessed through the notes page.
> 

I'm not sure whether this one should be a "required/absolutely must have" feature. So, we may completely remove it from the requirements. If we will include it, then we can show the edit time in the part where we display the content of the note (most probably note detail screen but the design part is not important).

> For the annotations, I find the requirements a bit too much to be presented on the profile page,
> 
> > 1.1.2.12.3.3. Users shall be able to see how many annotations they have and from how many categories, from how many courses and the total number of upvotes they have received.
> 
> Do we really need that statistical data on the profile page?
> 

I agree with you. We can remove the extra details. You can read the project description and only leave the ones which are written there.

> > 1.1.2.12.3.2. Users shall be able to browse their annotations by category, by course, by history, and by upvotes they have received.
> 
> I think this requirement as a definition of filtering mechanism, category, and course can be good filters for annotations but I do not understand how to filter by history or upvotes.
> 
> To me, just to offer 1.1.2.12.3.1. will be enough to offer on the profile page, the other details can be applied on a specific annotation page.

I think we need to have a filtering mechanism for annotations. So, please don't remove this requirement. About your filtering by history or upvotes question:
- for upvotes: I think we can remove this filter, it doesn't seem so essential to me.
- for history: user can set a start and end date and see the annotations which are created between those 2 dates.

**Comment by bahricanyesil** [comment]
> Comments on the requirements under the Lecturer Profile topic,
> 
> Since the team omit the separate profile structures for the learner and lecturer, maybe these requirements are a bit too specific for the profile page.
> 
> > Users shall be able to see the courses they have provided teaching material as a lecturer and their reputation on their profile pages.
> 
> Is this reputation just mean the overall score of the lecturer, and at the current form since we do not specify if a user is a learner or lecturer, presenting such a point for each user might not be the best practice. Maybe showing the courses given as a sub-window on the profile page might be an option, then showing a rating in these sub-windows if some courses exist.
> 

We can just show two separate rows for "taken courses" and "given courses" and then show the other details (how many people took the course, what is the rating, and so on) in the details of a specific course. So, we can change this requirement and merge it with the learner one as "Users shall be able to see the all courses they took and gave.". We should also remove the "profile screen" part since it is a design detail.

> > 1.1.2.13.1.2. Users shall view the cover photo, a basic bar chart that shows the rate of stars and the average rating they have received for each course in the lecturer profile section.
> 
> We can delete it because of the similar reasons that I mentioned above
> 

We should show at least the average rating and maybe the cover photo of a lecture. However, this should be shown in the lecture detail screen, not the profile screen.

> > 1.1.2.13.1.3. Users should be able to enroll in a course, which is provided by the owner of the profile page from the lecturer profile section.
> 
> We can delete it too since we can just put a link for the course and enrollment can be done at the course page.
> 

You're right. This process should be on the detail page of a course (a button at the bottom with "enroll" text), we don't need to show it directly on the profile page. Simply, remove it.

> The recommendations section could be deleted since we can see this information through the course page as the instructor of the course. Also, there is a notification mechanism that notifies the lecturer of feedback, and these notifications can route the instructor to the related section on the lecture page.

I couldn't understand your first sentence. Why the recommendations section could be deleted? Isn't it the part where the user can see the recommended lectures? So we need to have it. However, most probably, the correct place for the recommendations will be the home screen (but we shouldn't go into design details in the requirements).

Routing to a specific page with the notification can make harder our work at the first stage. So, please don't add a requirement related to routing to a specific page on notification click. Instead, we can only have notifications about feedbacks (without dynamic routing).

**Comment by ezgy** [comment]
In addition to these changes, there should also be requirement(s) regarding what is visible on a profile when it's private versus public. We determined public&private profiles as a requirement last term but from what I see it's not in the requirements. just a reminder @gokayyildiz @hasancan-code

**Comment by hasancan-code** [comment]
I agree with Ezgi, we mentioned that for lectures privacy requirements

> 2.2.2. Lectures can be private or public. If a lecture is private, its content should not be visible to every user in the app.

but even though we discussed last semester that users shall be able to change their profile page's visibility, we did not add it to the requirements.

I think we should add the requirements like

> 1.1.2.14. Users shall be able to determine their profile page visibility as public or private.
> 1.1.2.15. Followers, Follows, My Events, Interest Areas, Achievements, Progress, Notes, and Annotations sections have to be hidden on private profiles.

**Comment by gokayyildiz** [comment]
I updated the profile section under the requirements page according to the comments above and after a quick lookup and review we can close this issue. @hasancan-code @bahricanyesil

**Comment by bahricanyesil** [comment]
I don't have any further comments except the ones I mentioned above. Thanks for your work @gokayyildiz.
