### ISSUE TITLE
Revising the Diagrams based on Achievements

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#346]
### Issue Description

I have changed the achievements requirements. Changes can be seen from this issue #333. Diagrams will be changed according to the changes. If there is unnecessary things in the diagrams, they will be deleted. If there is missing points after the revise of requirements, they will be added. 

### Step Details

Steps that will be performed:
- [x] Check use case diagram
- [x] Make necessary changes, if needed
- [x] Check class diagram
- [x] Make necessary changes, if needed
- [x] Check sequence diagram
- [x] Make necessary changes, if needed
- [x] Show the previous and new version of the diagrams to be reviewed issue clearly

### Final Actions

The previous and new version of the changed parts of diagrams will be provided in order to ease the review process.

### Deadline of the Issue

16.10.2022 - Sunday - 23.59

### Reviewer

Ecenur Sezer

### Deadline for the Review

17.10.2022 - Monday - 23.59

**Comment by onurkomurcu** [comment]
For the use case, followings were changed according to the changed requirements:
**View earned badges** use case is removed since there won't be any badges.
![Screen Shot 2022-10-16 at 16 29 14](https://user-images.githubusercontent.com/92719802/196038317-30255394-1296-4210-813a-795639bdfeca.png)
![Screen Shot 2022-10-16 at 16 33 41](https://user-images.githubusercontent.com/92719802/196038372-1902111b-e5b0-4e78-8f44-983e9745ca4f.png)

***

Achievement won't be specific for the courses. Achievement will be same all across the platform.
![Screen Shot 2022-10-16 at 13 39 40](https://user-images.githubusercontent.com/92719802/196038393-3d78f950-0f3c-45cc-99db-0a1df3c6e1ec.png)
![Screen Shot 2022-10-16 at 13 43 52](https://user-images.githubusercontent.com/92719802/196038440-dcaf6ff8-b1b9-4c66-8028-586a17f02e20.png)

***

Whole achievements can be seen if the profile is public. There won't be any additional setting for achievements.
![Screen Shot 2022-10-16 at 13 46 41](https://user-images.githubusercontent.com/92719802/196038466-0582da06-57e2-4137-839b-d23df5892519.png)
![Screen Shot 2022-10-16 at 13 46 49](https://user-images.githubusercontent.com/92719802/196038500-04a983b5-999c-4db5-ad1b-ac299f8d9ba3.png)

**Comment by onurkomurcu** [comment]
For the class diagram, following changes are necessary:

## Enrollment class:
###### Removed:
> +getBadges:(user_id: UID): List<Badge>

## Profile class:
###### Removed:
> -earnedBadges:string[]
> -displayedAchievements: string[]
> +addDisplayedAchievement(ach:string):void
> +removeDisplayedAchievement(ach:string):void

## Course class:
###### Removed:
> -badges: List<Achievement>
> +addBadge:(badge: Badge): boolean
> +removeBadge:(name:String): boolean
> +getBadge(id:UID): Badge
> +getAllBadges():List<Badge>
> +addAchievement:(name:String, visual:String): boolean
> +removeAchievement:(name:String): boolean


## Rewarding class:
###### Removed:
> -badge:Badge
> +getBadge():Badge

***

Apart from these, badge class was also removed.
![Screen Shot 2022-10-16 at 16 56 02](https://user-images.githubusercontent.com/92719802/196039388-bc5f3a7e-db54-4c10-990b-4e72e5be9903.png)

**Comment by onurkomurcu** [comment]
For the sequence diagrams, there was only one action that includes achievements. Revise can be found below.
![Screen Shot 2022-10-16 at 17 03 57](https://user-images.githubusercontent.com/92719802/196039830-76212f01-37f6-4962-a6c6-de7ffa72465e.png)
![Screen Shot 2022-10-16 at 17 04 12](https://user-images.githubusercontent.com/92719802/196039840-41a34ee3-1940-433a-be67-103431fcc971.png)

**Comment by codingAku** [comment]
Hello Onur, as I see you have removed achievement privacy settings from all diagrams. I have checked requirements again and now it seems they all come together. Thank you.
