### ISSUE TITLE
Revising the Diagrams based on Lecture Structure

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#347]
### Issue Description

As we decided in our second meeting, I made changes under "Lecture Structure" title of our requirements. Following these changes, design diagrams should be updated to be consistent with our requirements. This issue corresponds to updating the diagrams according to changes made in issue #341.

### Step Details

Steps that will be performed:
- [ ] Update diagrams according to newly updated Lecture Structure requirements

### Final Actions

After necessary changes is determined, I will update all parts related to Lecture Structure in the diagrams accordingly.

### Deadline of the Issue

16.10.2022 - Sunday - 23:59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

17.10.2022 - Monday - 23:59

**Comment by egemenatikk** [comment]
I changed **"see course annotations"** to **"see course annotations and notes"**.

It takes place after **"View Course Page"**

**Comment by surmelienes1** [comment]
## Conclusion

Thank you, @egemenatikk, for your thorough examination and adjustments of the Diagrams based on Lecture Structure.

I have reviewed your updated and finalized sections of the diagrams. I do not have anything to add right now.

As everything is finalized, I am closing this issue now. If you have more questions or suggestions, you can reopen this issue and write your ideas as a comment.
