### ISSUE TITLE
Dockerization of the API

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#355]
### Issue Description

As the API is close to initialization, we need to dockerize it. However, since the development is still underway, we need a flexible container that runs the code in our local so that rebuilding the container for each commit wont be necessary.

### Step Details

Steps that will be performed:
- [x] Initialize node based container for the API
- [x] Initialize DB container
- [x] Establish communication between those
- [x] create a volume so that container can read code in the real OS
- [x] Wrap it all using docker compose

### Final Actions

Upon completion, members will get a dev environment running with a single docker compose.

When we are in the production stage, containers must be updated for production.

### Deadline of the Issue

21.10.2022 23:59

### Reviewer

Ecenur Sezer

### Deadline for the Review

22.10.2022 23:59

**Comment by mbatuhancelik** [comment]
I was mistaken about creating a volume and letting docker read the code from it. Apparently the container will need to copy the code every time.

**Comment by mbatuhancelik** [comment]
Besides that, current branch sets up the server with docker compose up with no problems, I will be editing it further for:

- Saving logs of the server on a crash condition.
- optimize initialization

**Comment by mbatuhancelik** [comment]
I was mistaken about being mistaken about not being able to read the code every time container ran. Last version on the branch does exactly that

Besides that I optimized by creating a inter container that has our packages, so packages wont be installed each time we ran the container. If we want to install new packages, we need to rebuild the container.

**Comment by mbatuhancelik** [comment]
Upon further investigation, apparently updating the code and not the docker image is not logical since there is no simple way to merge previously installed npm packages and newly written code and docker in production mode runs under 2 seconds, so we can use the production container for trial and error and handling this case is not worth the effort.

I updated the branch accordingly.

**Comment by codingAku** [comment]
PR has been approved and dockerization has been merged.
