### ISSUE TITLE
W3 annotation model research

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#362]
### Issue Description

As discussed in our last meeting, each member will perform research about W3 annotation model so that we can prioritize its implementation in Milestone 2.

### Method to Gather Information

Results of each individual research are collected on our Discord channel. After each initial research is done and the findings are gathered on our Discord channel, I will summarize them and create a separate wiki page for the research results.

### Researchers

- [ ] Bahrican Yesil
- [ ] Egemen Atik
- [ ] Altay Acar
- [ ] Ezgi Aysel Batı
- [ ] Muhammed Enes Sürmeli
- [ ] Onur Kömürcü
- [ ] Mehmet Batuhan Çelik
- [ ] Hasan Can Erol
- [ ] Koray Tekin
- [ ] Mehmet Gökay Yıldız
- [ ] Ecenur Sezer

### Deadline of the Issue

25.10.2022 Saturday 13.00

### Deadline for the Review

25.10.2022 Saturday 23.59

### Final To-Dos

- [ ] Collected the results of the researches via the mentioned channel.
- [ ] Summarized the research results and created a separate wiki page for it.
- [ ] Added and linked the newly created wiki page under the "research" title of the sidebar.
- [ ] Added and linked the newly created wiki page under the "research" title of the main wiki page.

**Comment by onurkomurcu** [comment]
I think we can reopen this issue when we start working on the annotation feature. For now, I'm closing this issue.
