### ISSUE TITLE
Sign_up endpoint

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#365]
### Issue Description

As discussed in our last meeting, our API needs to provide an endpoint named signup. I/O details of the endpoint are given bellow:

Request -->
* Email
* Username
* Password

Response --> 
* Error/Success message

I will take the responsibility to implement the abovementioned endpoint under this issue.

### Step Details

Steps that will be performed:
- [x] Initialize the user model in mongooese.
- [x] Create a validator for the request body.
- [x] Determine the URL of the endpoint.
- [x] Implement the Endpoint function.
- [x] Handle Routing.
- [x] Manually test the endpoint.

### Final Actions

Upon completion of the implementation, we can move on to verify email endpoint.
While taking progress in the verify email endpoint, I will be implementing unit tests for the API function.

### Deadline of the Issue

22.10.2022 Saturday 14.00

### Reviewer

Hasan Can Erol

### Deadline for the Review

22.10.2022 Saturday 23.59

**Comment by mbatuhancelik** [comment]
I implemented the endpoint with detailed logs. It serves under  POST API_URI/auth/signup.

You can find an example request here: https://documenter.getpostman.com/view/18740569/2s84Dmw3zM

Creating a PR now

**Comment by mbatuhancelik** [comment]
Apparently I forgot to send the verification email to the user, I am working on that now.

**Comment by codingAku** [comment]
Hello, the PR has been closed and merged with reviews. Closing the issue.
