### ISSUE TITLE
Creating Issue Templates

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#37]
I will be creating some issue templates to ensure unity among the team members and not miss some important steps that will make the issue description clearer. We have discussed this in our second and third meetings and decided that it will be helpful for the issue creators to directly fill the required sections without thinking about "what is required".

The issue templates should contain the following ones but they can be expanded in the future and more may be added:

- [x] General Issue Template:
   * This will have the general required information, steps that should be considered while creating/managing/closing an issue regardless of the details of the issue.
   * It will create a base for any issue and its sections/subsections can be expanded acc. to the specific requirements of an issue. 

- [x] Research Issue Template:
   * We generally have at least one issue for some research topics every week. Because of this reason, it will be good to have a specific issue template for research issues.
   * In this way, we can point out some unique steps that should be performed while creating a research issue (like adding it under the research title of the sidebar)
   * It will also have a checklist so that we will not be dealing with creating it each time. In most cases, research issues are done by all team members and we track them via a checklist.

- [x] Group Issue Template:
   * This will be for the issues that are performed by more than 2 or more people. We generally create checklists for these issues even though all team members are not responsible for them.
   * In some cases, we have sub-issues for this type of issue. So I will add a note that reminds us to link the sub-issues in those cases.

After I created the templates, I will both share them under this issue as comments and send them to our TA (Egemen İşgüder) to add them to the GitHub settings. (I chatted  with Suzan Üsküdarlı via our group Slack channel and we've decided to share the templates with our TA so that he will be adding on our behalf of us since we don't have the required permissions to directly add them.)

Altay will review the results of this issue, the templates I created. He will make the final comments and I will be revising accordingly.

**Deadline: 18.03.2022 - Friday - 23:59
Reviewer: @xltvy  - Deadline: 19.03.2022 - Saturday - 23:59**

**Comment by bahricanyesil** [comment]
I have created the generic issue template. You can see it [here](https://github.com/bounswe/bounswe2022group2/blob/master/.github/ISSUE_TEMPLATE/generic_template.yml).

You can use it while creating your next issue, it's ready to use 🚀

It contains the following main sections:
1. Title
2. Issue Description
3. Step Details (Optional)
4. Final Actions (Optional)
5. Deadline of the Issue
6. Reviewer (Optional)
7. Deadline for the Review (Optional)

**Comment by bahricanyesil** [comment]
I have created the research issue template. You can see it [here](https://github.com/bounswe/bounswe2022group2/blob/master/.github/ISSUE_TEMPLATE/research_template.yml).

You can use it while creating your next issue about a research topic, it's ready to use 🚀

It contains the following main sections:
1. Title
2. Issue Description
3. Method to Gather Information
4. Researchers
5. Deadline of the Issue
6. Reviewer (Optional)
7. Deadline for the Review (Optional)
8. Final To-Dos

**Comment by bahricanyesil** [comment]
I have created the group issue template. You can see it [here](https://github.com/bounswe/bounswe2022group2/blob/master/.github/ISSUE_TEMPLATE/group_issue_template.yml).

You can use it while creating your next issue, it's ready to use 🚀

It contains the following main sections:
1. Title
2. Issue Description
3. Step Details
4. Final Actions
5. Responsible People
6. Deadline of the Issue
7. Reviewer (Optional)
8. Deadline for the Review (Optional)
9. Final To-Dos

**Comment by bahricanyesil** [comment]
All templates are created and ready to be reviewed by @xltvy.

**Comment by xltvy** [comment]
I have reviewed the issue template. Wonderful job, I could not find any edit suggestions. So, I am closing this issue.

**Comment by bahricanyesil** [comment]
Thanks for the review @xltvy!
