### ISSUE TITLE
Initialization of the frontend project

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#371]
### Issue Description

Initialization of the frontend part for the project that we are building, Learnify.

Under this issue, we kickstart our project.

### Step Details

Steps that will be performed:
- [x] Creating .gitignore file 
- [x] Initializing the npm project 
- [x] Loading required packages
- [x] Creating README

### Final Actions

Initial file structure decided and in addition to that initial form structure has been applied for sign up and sign in pages. This pages has not yet been designed for the end use.

### Deadline of the Issue

23.10.2022 - Sunday

### Reviewer

Koray Tekin

### Deadline for the Review

24.10.2022 - Monday

**Comment by gokayyildiz** [comment]
I created the initial project and initial file structure of the front-end project. Addition to that creating the initial file structure, created the initial sign up and sign in form designs

**Comment by gokayyildiz** [comment]
me and other frontend team members started to work on the initial project after finalizing this issue.
Reviewed by @xltvy , @surmelienes1 , @Koraytkn

**Comment by xltvy** [comment]
Thank you for your work, closing #371
