### ISSUE TITLE
Mobile Team: Setting up development Environment

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#372]
### Issue Description

As we are starting to develop the authentication functionalities this week, mobile team members should setup their development environments and be ready to work on the application. This process includes several steps: 

### Step Details

Steps that will be performed:
- [x] download and set up flutter
- [x] download and set up android studio
- [x] set up an emulator OR unlock debugging mode on a physical android device

### Final Actions

After these steps are performed, run the command `flutter doctor` on a terminal to check if everything is set up properly. Don't forget to accept android licenses( flutter doctor will guide you on how to) if using a windows device. 

### Responsible People

- [x] Bahrican Yesil @bahricanyesil 
- [x] Egemen Atik @egemenatikk 
- [x] Ezgi Aysel Batı @ezgy 
- [x] Onur Kömürcü @onurkomurcu 

### Deadline of the Issue

24/10/2022 

### Final To-Dos

- [ ] Every responsible performed the steps required.

**Comment by bahricanyesil** [comment]
## Update

I set up my Flutter environment, installed Android Studio, created an emulator, and used it. Here's the result of the flutter doctor command.

<img width="611" alt="Screen Shot 2022-10-23 at 16 16 49" src="https://user-images.githubusercontent.com/60237280/197394443-51b9507e-8242-4e38-9ec5-396f0b23def9.png">

**Comment by ezgy** [comment]
I've set up my environment and also checked it with a dummy project using a physical android device. As seen, everything is working as needed: 
![image](https://user-images.githubusercontent.com/56553280/197394708-0bfee663-0f9d-48c2-acf8-88642e705e84.png)

**Comment by onurkomurcu** [comment]
Since everybody complete the set up, this issue can be closed.

**Comment by egemenatikk** [comment]
![image](https://user-images.githubusercontent.com/100771925/197736351-5069923a-b758-43e4-b990-7b55d5402d85.png)

I have set up my environment and run an example app using an emulator. As seen from the image above, it found an issue that Visual Studio is not found, but it is not a problem because Visual Studio is used to develop desktop applications in Windows with flutter.
