### ISSUE TITLE
Frontend: Implementing Forgot Password Screen

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#379]
### Issue Description

The forgot password screen will be created and integrated into the current pages and connections are made with other screens.

### Step Details

Steps that will be performed:
- [x] Page design completed
- [x] Implementation completed
- [x] Connected with sign in screen via a link
- [x] PR is merged
- [x] Feature is tested on frontend/dev branch

### Deadline of the Issue

26.10.2022 - Wednesday - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

28.10.2022 - Friday- 23.59

**Comment by gokayyildiz** [comment]
Successfully reviewed and merged the PR by @xltvy. If there is no other comments on this issue, we can close it and continue on the backend connection with another issue.

**Comment by xltvy** [comment]
Closing #379
