### ISSUE TITLE
Backend: Implementation of Login API

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#380]
### Issue Description

As a part of the backend team, we have planned some features to be completed until Milestone 1. First API initialization I am working on is the endpoint for users log in. In our scenario, users will enter their e-mail and password to login.
Structure of the API is down below.

Login:
Request -->

- Password
- Email

Response -->

- Error/Success message
- Access token
- User

### Step Details

Steps that will be performed:
- [x] Create the API
- [x] Test it over Postman for mock data

### Final Actions

After the API is done,  I will create a PR related to this issue and my backend team members will review 

### Deadline of the Issue

27.10.2022 - 00.00

### Reviewer

Hasan Can Erol

### Deadline for the Review

28.10.2022 - 00.00

**Comment by codingAku** [comment]
Explanation and PR is open #381

**Comment by hasancan-code** [comment]
I tried the code on my local and it works as shown. Seems like this particular task is done.

**Comment by codingAku** [comment]
PR reviewed and closed, closing.
