### ISSUE TITLE
Mobile: Writing Tests for Forget Password Screen

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#383]
### Issue Description

As we decided on [Mobile Meeting #1](https://github.com/bounswe/bounswe2022group2/wiki/Mobile-Team-Meeting-1-for-451-(17.10.2022)), I am responsible for implementing Forget Password screen of the mobile application. Implementation of the screen is #375 . I will also write tests for this screen.

### Step Details

Steps that will be performed:
- [x] Determine testable parts
- [x] Write tests 
- [x] Run tests and verify they pass 

### Final Actions

Once all the tests are created and pass, a pull request will be created to merge the corresponding branch into dev.

### Deadline of the Issue

27.10.2022 - Thursday - 16:59

### Reviewer

Egemen Atik

### Deadline for the Review

28.10.2022 - Friday - 23.00

**Comment by ezgy** [comment]
the tests are ready to be merged. mobile team (@onurkomurcu  @bahricanyesil  @egemenatikk ) members can review under pr #442 
The tests pass, as can be seen in the screenshot:
![image](https://user-images.githubusercontent.com/56553280/198875829-da964f3d-cdb9-4e72-be57-c0eac88e12eb.png)

**Comment by egemenatikk** [comment]
Corresponding PR numbered #442 is merged into dev branch, so I am closing this issue.

**Comment by ezgy** [comment]
pr #442 is merged, so this task is complete.
