### ISSUE TITLE
Mobile: Back-end Connection of Forget Password/Verify Email Endpoint

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#384]
### Issue Description

As we decided on [Mobile Meeting #1](https://github.com/bounswe/bounswe2022group2/wiki/Mobile-Team-Meeting-1-for-451-(17.10.2022)), I am responsible for implementing Forget Password screen of the mobile application. Implementation of the screen is https://github.com/bounswe/bounswe2022group2/issues/375 . This screen should send a request to send email verification code endpoint, so this connection should be implemented

### Step Details

Steps that will be performed:
- [x] implement request to be sent
- [x] connect onclick functionality to sending request
- [x] verify connection via testing

### Final Actions

Once desired connection is provided, the branch will be merged into dev via a pull request.

### Deadline of the Issue

27.10.2022 - Thursday - 16:59

### Reviewer

Onur Kömürcü

### Deadline for the Review

28.10.2022 - Friday - 23.00

**Comment by ezgy** [comment]
The forgot password screen has been implemented(See #375). Since backend endpoint for sending the verification code is not yet ready, this issue is dependent on the completion of #406

**Comment by codingAku** [comment]
> The forgot password screen has been implemented(See #375). Since backend endpoint for sending the verification code is not yet ready, this issue is dependent on the completion of #406

Hello Ezgi, verifying email endpoint is ready and deployed.

**Comment by ezgy** [comment]
pr #433 is open and ready to be reviewed by mobile team(@egemenatikk @onurkomurcu @bahricanyesil) members 🚀

**Comment by egemenatikk** [comment]
Since corresponding pull request, PR numbered #433, is merged, I am now closing this issue. Thank you for your work @ezgy .
