### ISSUE TITLE
Documenting Meeting Notes for the Meeting 1 of Front-End Team 

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#388]
### Issue Description

As decided in the general team meeting sub-teams will be making their own meetings and holding notes of the tasks and progress. This issue is related to the creation of the front-end teams first meetings notes page in our wiki page.teams'

### Step Details

Steps that will be performed:
- [x] The notes that were taken in the meeting about individual assignments will be organized.
- [x] The discussion topics through the first meeting will be titled. 

### Deadline of the Issue

24.10.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

**Comment by Koraytkn** [comment]
I have implemented the first meeting notes page and provided the page link to our wiki page.

**Comment by Koraytkn** [comment]
While creating the first meeting's meeting notes wiki page I left the date and issue fields of action items empty, since we have all determined the corresponding deadlines ourselves after initial task sharing, it would be great if you could fill in those fields; then we can close this issue @xltvy @surmelienes1 @gokayyildiz. Thanks in advance.

**Comment by gokayyildiz** [comment]
Thank you for your effort, we can close the issue as you mentioned.
