### ISSUE TITLE
Determining Lecture Requirements

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#39]
### Issue Description

As discussed in meeting#3, we have to determine requirements regarding lectures. Our main objective under this issue is to define lecture structure while keeping progress tracking and privacy in mind.

### Final Actions

Integrate requirements stated under this issue to the [main requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).

### Deadline of the Issue

21.03.2022 Monday 23:59

### Reviewer

Ecenur Sezer

### Deadline for the Review

22.03.2022 Tuesday 10:00

**Comment by mbatuhancelik** [comment]
## Glossary

Chapters: Set of Sections.

Section: A single piece of indivisible lecture content like a pdf file, text, or **video.** 

Private: A piece of information that can only be seen by chosen users.

Public: A piece of information that can be seen by all users.

## User Requirements

### Lecture structure

1. Lectures shall have a unique name.
2. Lectures shall contain sections either as a group of chapters or as individual sections, each having their own titles.
3. Sections shall contain a single text or video.
4. Lectures shall have 2 sections named “Introduction” and “Events” that cannot be part of any chapter.
5. Introduction section shall provide a overview of lecture content consisting of lecturer, description,and topics.
6. Description in the introduction shall be a text of video.
7. Event section shall contain events specific to the sections lecture.

### Privacy

1. Lecturer shall set lectures, chapters, and sections as private.
2. Lecturers shall choose which learners shall see which private lecture, chapter, or section.
3. Private lectures shall have public chapters and sections meaning that all users who can see the lecture can see these chapters and sections. 

## System Requirements

1. The system shall set the user created the lecture as the lecture’s lecturer.
2. The same lecturer shall not be able to create multiple lectures with the same name.
3. Learners shall not be able to see private content if they are unauthorized.
4. Newly created lectures, chapters, and sections shall be private initially as long as the lecturer states otherwise.

**Comment by mbatuhancelik** [comment]
A prototype is proposed, I may work on this more. Comments are most welcomed!

**Comment by codingAku** [comment]
"The same lecturer shall not be able to create multiple lectures with the same name." 
I believe it is already specified that every lecture must have a unique name so this may be duplicating it. Other than that, seems pretty accurate. Thank you for your hard work.

**Comment by mbatuhancelik** [comment]
Thanks for pointing that out. With fixing that and some re-phasing, this is current version:

## Glossary

Chapters: Set of Sections.

Section: A single piece of indivisible lecture content like a pdf file, text, or **video.** 

Private: A piece of information that can only be seen by chosen users.

Public: A piece of information that can be seen by all users.

## User Requirements

### Lecture structure

1. Lectures shall have a unique name.
2. Lectures shall contain sections either as a group of chapters or as individual sections, each having their own titles.
3. Sections shall contain a single text or video.
4. Lectures shall have 2 sections named “Introduction” and “Events” that cannot be part of any chapter.
5. Introduction section shall provide a overview of lecture content consisting of lecturer, description,and topics.
6. Description in the introduction shall be a text or video.
7. Event section shall contain events specific to the sections lecture.

### Privacy

1. Lecturer shall be able to set lectures, chapters, and sections as private.
2. Lecturers shall be able to authorize learners to see private lectures, chapters, or sections.
3. Private lectures shall have public chapters and sections meaning that all users who can see the lecture can see these chapters and sections. 

## System Requirements

1. The system shall set the user created the lecture as the lecture’s lecturer.
2. Learners shall not be able to see private content if they are unauthorized.
3. Newly created lectures, chapters, and sections shall be private initially as long as the lecturer states otherwise.

**Comment by mbatuhancelik** [comment]
After checking out integrity with glossary and other requirements in the wiki, second point in system requirements is removed and others are merged to [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements).
