### ISSUE TITLE
Frontend: Implementation of Login Page

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#390]
### Issue Description

According to the output of both general ["team meeting3"](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-3-for-451-(18.10.2022)) and the Front-End ["team meeting1"](https://github.com/bounswe/bounswe2022group2/wiki/Front-end-Team-Meeting-1-for-451-(19.10.2022)) the responsibility of implementing the Login page was assigned to me.

### Step Details

Steps that will be performed:
- [x] Use the page structure determined for Authentication related pages.
- [x] Provide multi-page navigation support.
- [x] Customize the page using our own logo, typeface, and color coding.
- [x]  Implement a form field and other additional structures for Login.

### Final Actions

After the each part of front-end initialization is over the PR's will be opened and initialization will be merged to development branch.

### Deadline of the Issue

28.10.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

30.10.2022 - 23.59

**Comment by Koraytkn** [comment]
I would appreciate it if you could provide review and close this issue, I will be creating a new issue for backend connection and validation of forms process for Login page. Thanks in advance @gokayyildiz

**Comment by gokayyildiz** [comment]
Succesfully implemented and PR merged https://github.com/bounswe/bounswe2022group2/pull/399
