### ISSUE TITLE
Backend: Implementation of Resend Email Verification

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#406]
### Issue Description

As a part of the backend team, we have planned some features to be completed until Milestone 1. First API initialization I am working on is the endpoint for resending verification emails. 

Request --> 
Email from the body

Response --> 
Error/Success message

### Step Details

Steps that will be performed:
- [x] Create the API
- [x] Test it on Postman

### Final Actions

After the API is done, I will create a PR related to this issue and my backend team members will review

### Deadline of the Issue

27.10.2022 23.59

### Reviewer

Ecenur Sezer

### Deadline for the Review

28.10.2022 23.59

**Comment by hasancan-code** [comment]
Postman results are below
![image](https://user-images.githubusercontent.com/74256913/198298120-dab0e087-ba15-48c2-b575-93e6b92d37c9.png)
![image](https://user-images.githubusercontent.com/74256913/198298142-24bc9e60-dbbb-4db2-86af-d726e5d944b7.png)

**Comment by ezgy** [comment]
I've used this endpoint in my section on mobile and observed it works. Thank you!
