### ISSUE TITLE
Creating Community Event Requirement

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#41]
### Issue Description

Since we talked about the interaction of community events, I will create a requirement under the User-Lecture Interaction section.

### Deadline of the Issue

20.03.2022 - Monday 23.59

### Deadline for the Review

20.03.2022 - Tuesday 23.59

**Comment by codingAku** [comment]
Review from any fellow developer is needed. Thank you already.

**Comment by ezgy** [comment]
The requirements added include all the important aspects we talked about. Thank you for your work!
