### ISSUE TITLE
Create the registered lecturer scenario

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#42]
### Issue Description

As we have discussed in our [meeting 3](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%233-(17.03.2022)), one of our pre-determined user scenarios is about a registered lecturer. In this user scenario, we focus on a lecturer who has already signed up and has been using the app actively. The lecturer has already created some lectures and has a reputation from the students. We will focus on his action to create a new lecture in the app.

### Step Details

We will focus on the following sections in our user scenario:

1. Persona
2. User Story
3. Goals
4. Preconditions
5. Scenario
6. Acceptance Criteria

According to our decision in the meeting, responsible people for this persona:
- [x] @surmelienes1 
- [x] @bahricanyesil 
- [ ] @ahmet633 

[Here's the link of the wiki page for this user-scenario](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Taşkıran)

We will work together with @surmelienes1 for the persona. However, to avoid the conflicts, we predetermined the sections that we will be individually focus on.

@bahricanyesil will be focusing on the persona, user story, goals and preconditions parts.
[Here's](https://github.com/bounswe/bounswe2022group2/issues/44) the link for corresponding sub-issue.

@surmelienes1 will be focusing on the scenario and acceptance criteria parts.
The appropriate sub-issue may be found at this [link](https://github.com/bounswe/bounswe2022group2/issues/46).

@ahmet633 will be designing the mockup.

We will be analyzing, reading, reviewing and communicating about each other's parts. So, this will be a collective work even though we have defined the sections above.

### Final Actions

We will create separate issues for the parts we have divided. After each issue has completed and required info is commented under them, we will gather the complete information by linking under this issue. Finally, we will convey the final scenario report to a wiki page under the scenario section in the sidebar.

Finally, @onurkomurcu will review our final user scenario and make the final comments under this issue.

### Deadline of the Issue

21.03.2022 - Monday - 20:00

### Reviewer

Onur Kömürcü

### Deadline for the Review

22.03.2022 - Tuesday - 11:00

**Comment by bahricanyesil** [comment]
I created a separate issue to share the info I wrote for the sections "Persona", "User Story", "Goals", and "Pre-Conditions". Here's the corresponding sub-issue #44.

**Comment by bahricanyesil** [comment]
I created a wiki-page for this scenario that we will be working on. I also linked it in the sidebar and home wiki page. You can check it out [here](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Taşkıran).

**Comment by bahricanyesil** [comment]
I have finished the detailed explanations of the sections I am responsible for. All texts are commented under the sub-issue #44 and also they are written to the [wiki page of this scenario](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Taşkıran). You can view from both places. It is ready to review, I am open to all suggestions and review feedbacks.

**Comment by surmelienes1** [comment]
I created a new issue to provide the information I wrote for the "Scenario" and "Acceptance Criteria" parts. The relevant sub-issue may be found here at #46.

**Comment by surmelienes1** [comment]
I have completed the comprehensive explanations for the parts for which I was responsible. All the parts are reported as comments under the sub-issue #46, and they are also included to the scenario's wiki page [here](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Ta%C5%9Fk%C4%B1ran#scenario). It is now ready for evaluation, and all the suggestions and additions are welcome.

**Comment by bahricanyesil** [comment]
It is ready for review by @onurkomurcu.

**Comment by bahricanyesil** [comment]
We're waiting for the mockup sub-issue of @ahmet633 .

**Comment by surmelienes1** [comment]
As you mentioned, it would be more logical to use the term "**_course_**" instead of "**_lecture_**" because a course has a more inclusive meaning compared to a lecture.

I have made the necessary changes to the Scenario and Acceptance Criteria parts, thank you for your suggestion and contribution @onurkomurcu.

**Comment by bahricanyesil** [comment]
> I review all sections except mockup part. When mockup is done, I will also review it. Firstly, I appreciate your work. I enjoyed when I read them. I have only 2 suggestions for the overall document. Other than these, I have no question or suggestion.
> 
> * All "**_student_**" words should be replaced with "**_learner_**" to be consistent with glossary.
> * "**_lecture_**" term should be changed with "**_course_**" in some parts of the document. I think that, "**_course_**" will be more relevant to context in many parts.
> 
> I will be waiting for your responses @bahricanyesil @surmelienes1 .

I made the necessary changes, thank you for the review.

**Comment by bahricanyesil** [comment]
> There is one thing that I realize now. As we discussed in meeting 3, scenarios should be implemented for website. However, all sections were developed for app in this scenario. You should change the scenario accordingly @bahricanyesil, @surmelienes1. I'm sorry to mention this issue late.

I couldn't understand what did you mean by "all sections were developed for app". Our features will be same for both mobile and web, there can be just interaction differences. Can you specify them clearly?

**Comment by ahmet633** [comment]
Here is the scenario mockup (from the subissue #58):
![l1](https://user-images.githubusercontent.com/36857236/159791265-121641bc-29cd-4123-92fd-930ae4b2079e.PNG)
![l2](https://user-images.githubusercontent.com/36857236/159791274-cba80180-19fa-4817-ae3d-ef64141e9d6c.PNG)
![l3](https://user-images.githubusercontent.com/36857236/159791281-c0ade271-977d-4218-821c-0e05d467b120.png)
![l4](https://user-images.githubusercontent.com/36857236/159791289-788030db-b0ac-4475-83e5-0f06f0dacde7.png)

If there is anything to be changed, feel free to reopen and comment the subissue.
