### ISSUE TITLE
AWS deployment of backend

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#423]
### Issue Description

As now we have some endpoints in dev branch, lets serve them on AWS so that mobile and front teams will easily work on connection.

### Step Details

Steps that will be performed:
- [x] Create an EC2 instance
- [x] Get an ellastic IP for the instance
- [x] Set up ports open to the worls
- [x] Clone our repo
- [x] Create .env files for the server
- [x] Docker compose build
- [x] Docker compose up

### Final Actions

Upon completion, we can work on connection between back and frontend.

### Deadline of the Issue

28.10.2022 Friday: 20:00

### Reviewer

Altay Acar

### Deadline for the Review

29.10.2022 Friday: 20:00

**Comment by mbatuhancelik** [comment]
Seems like: 3.75.151.200 will be our IP for this semester. 
Currently backend is serving at port 3000.

**Comment by bahricanyesil** [comment]
We can think to use GitHub actions after the demo. You may take note of this.

**Comment by mbatuhancelik** [comment]
Github actions is a good idea, I will check that out.

Besides that, the server is up!

**Comment by bahricanyesil** [comment]
I tested it on the android app and worked successfully.

**Comment by xltvy** [comment]
I tested it on the web application and it is working. Good work, well done! Closing #423
