### ISSUE TITLE
Mobile: Back-end Connection of Verification Endpoint

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#434]
### Issue Description

As we decided on our [first mobile team meeting](https://github.com/bounswe/bounswe2022group2/wiki/Mobile-Team-Meeting-1-for-451-(17.10.2022)), I implemented the verification screen for our application, you can view issue regarding this task from issue numbered #395. 

Then, I also implemented tests for the verification screen, you can view issue regarding to this task from issue numbered #417.

Now, I need to provide a connection from verification screen to verification endpoint.

### Step Details

Steps that will be performed:
- [x] Implement verify email request model
- [x] Update verification view model and auth service classes accordingly
- [x] Implement verify function
- [x] Test whether connection is provided or not

### Final Actions

After I complete all steps above, I will open a pull request and after getting reviews from mobile team members, I will merge the pull request and close this issue.

### Deadline of the Issue

29.10.2022 - Saturday - 01:00

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

30.10.2022 - Sunday - 14:00

**Comment by egemenatikk** [comment]
Implementation for back-end connection of verification screen is completed. Firstly, I implemented verify email request model. Then, I implemented verify email response model and hence user model. Then, I implemented POST method and verify email function in verification view model.

**Comment by egemenatikk** [comment]
Additionally I implemented resend verification functionality by using verify email request model and POST method for requesting verification code implemented by @ezgy .

**Comment by egemenatikk** [comment]
I opened the pull request, PR numbered #435, upon merging that pull request I will close this issue.

**Comment by ezgy** [comment]
pr #435 is merged, so this issue is complete. Thanks for your work!
