### ISSUE TITLE
Frontend: Backend connection for the Login page

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#441]
### Issue Description

As the front-end team, we have created the initial versions of authentication-related pages in the previous week, and now for each of those pages, the assignee of the corresponding page task will be also implementing the back-end connection. This issue also includes the verification of the user input before using an end-point, thus decreasing the traffic in the server.

### Step Details

Steps that will be performed:
- [x] Read the API documentation for Login 
- [x] Create request and response models for the login-related cases
- [x] Authenticity control
- [x] Establish the endpoint connection with the login button
- [x] Try related endpoints on postman before implementing on code

### Final Actions

I will create a branch related to this issue from the frontend/dev branch, which we use for the development of notify web app in correlation with the main dev branch, then I will be committing for related steps and finally creating a pull request and finalize the functionalization of  login page and this issue.

### Deadline of the Issue

30.10.2022 - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

31.10.2022 - 23.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @Koraytkn for your valuable contributions! I tested the changes you have made on my local system, and they worked very well.

I will now close this issue since the related pull request #446 has been merged.
