### ISSUE TITLE
Frontend: Backend connection for the Forget Password page

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#444]
### Issue Description

We created the initial versions of authentication-related pages in the previous week as the frontend team. Now, the assignee of each page will be also implementing the back-end connection. During this backend connection task, we also go over the verification of the user input before using an end-point, thus decreasing the traffic in the server.

### Step Details

Steps that will be performed:
- [x] Understand the implementation of the backend
- [x] Try related endpoints on postman before implementing on code
- [x] Understand the resend endpoint the one related to the forget password page
- [x] Create request and response models for the login-related cases
- [x] Establish the endpoint connection with the Send button
- [x]  PR is merged

### Deadline of the Issue

30.10.2022 - Sunday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

31.10.2022 - Monday - 23.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! I tested the changes you have made on my local system, and they worked very well.

I will now close this issue since the related pull request #445 has been merged.
