### ISSUE TITLE
Mobile: Writing Tests for Login Page

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#447]
### Issue Description

I worked on the login page implementation. It can be seen from issue #396  and PR of it is #398. My new task is writing tests for login page to observe results clearly and be sure that everything works fine. 

### Step Details

Steps that will be performed:
- [x] Think about the whole cases including edge cases
- [x] Determine the most critical/important ones
- [x] Write tests and execute them
- [ ] Provide results here

### Final Actions

When everything is seems adequate, results of the test will be provided here and PR will be opened.

### Deadline of the Issue

31.10.2022 - Monday - 20.00

### Reviewer

Egemen Atik

### Deadline for the Review

31.10.2022 - Monday - 23.59

**Comment by ezgy** [comment]
I've approved and merged the tests. Thank you for your work!

**Comment by onurkomurcu** [comment]
I have missed the providing results here but reviewers tested themselves. I should provide test results here to prove my work :). Thank you!
![Screen Shot 2022-11-03 at 23 42 12](https://user-images.githubusercontent.com/92719802/199830198-3c17c3fd-5044-4aaa-897d-068008d3c60d.png)
