### ISSUE TITLE
AWS Deployment of the Web Application

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#459]
### Issue Description

As part of the the development of our web application's frontend, we, as the frontend team have implemented all authentication related pages. To make the application's live version can be accessible from web, we need to deploy it through AWS.

### Step Details

Steps that will be performed:
- [x] Create an EC2 instance
- [x] Get an elastic IP for the instance
- [x] Set up ports open to the worlds
- [x] Clone our repo
- [x] Create .env files for the server
- [x] Docker compose build
- [x] Docker compose up

### Final Actions

After I have completed the AWS deployment, I will provide the IP address of our live web application both here in this issue and on our wiki homepage.

### Deadline of the Issue

31.10.2022 - Monday - 23.59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

01.11.2022 - Tuesday - 23.59

**Comment by xltvy** [comment]
Our web application is live now. You can access it from http://3.75.151.200

**Comment by mbatuhancelik** [comment]
I verified the application is running, signed in, verified my email and logged in.
All seems fine
Closing now.
