### ISSUE TITLE
First Demo: Creating Entrance Slide 

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#460]
### Issue Description

For our first demo, we decided to prepare a short slide for entrance and showing which requirements we have completed. I will be preparing this slide.

### Step Details

Steps that will be performed:
- [x] Decide on which requirements are completed.
- [x] Create the slide.

### Deadline of the Issue

31.10.2022 - 00.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

1.11.2022 - 13.00

**Comment by codingAku** [comment]
The slide is complete. You can access it from [here](https://drive.google.com/file/d/1BkNdEZqsbCjGTolUUOrQMxO-5cwHAY-d/view?usp=sharing)

**Comment by onurkomurcu** [comment]
Slide seems adequate and professional. Thank you, @codingAku !
