### ISSUE TITLE
Frontend: Unit Tests for Forget Password page

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#464]
### Issue Description

The forgot password page is ready. Before that, I made the overall page layout, validation, and backend connection. I will now provide unit tests for the application's forgot password page as the last step.

### Step Details

Steps that will be performed:
- [x] Investigating the unit testing techniques for frontend
- [x] Decide what to test
- [x] Implement the tests 
- [x] PR is merged

### Deadline of the Issue

31.10.2022 - Monday - 22.30

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

31.10.2022 - Monday - 23.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! I ran the tests you have implemented on my local system, and they all worked as expected.

I will now close this issue since the related pull request #463 has been merged.
