### ISSUE TITLE
Frontend: Creating mock home page and adding to the repository

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#465]
### Issue Description

Creation of a mock home page to present our vision in the presentation and set a goal to the team in terms of design.

### Step Details

Steps that will be performed:
- [x] Creation of mockup
- [x] Addition to the code

### Final Actions

Temporary addition of the page is done and now active on our code

### Responsible People

- [x] Altay Acar - For creating the home page design.
- [x] Mehmet Gökay Yıldız - For integrating the design into our code base.

### Deadline of the Issue

31.10.2022 - Monday - 22.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

31.10.2022 - Monday - 23.59

**Comment by gokayyildiz** [comment]
@xltvy created the mockup page for our use 
<img src='https://user-images.githubusercontent.com/42673110/199099772-4e0c3cc2-0b8d-4ad5-ad7b-11bd5b6dee8d.jpg'>

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! I tested the changes you have made to the home page on my local system, and they worked very well.

I will now close this issue since the related pull request #461 has been merged.
