### ISSUE TITLE
Frontend: Login Page Unit Test Implementation

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#466]
### Issue Description

As the finalization of the front-end continues, before deploying our initial pages to the server, as the front-end team we have assigned the tasks of implementing the unit tests among us according to the pages we have created. As the outcome of this decision since I have created the lay-out, functionality and initialization for the Login page previously I will also be implementing the unit tests for the Login page. 

### Step Details

Steps that will be performed:
- [x] Investigating the unit testing techniques for frontend
- [x] Decide what to test
- [x] Implement the tests 
- [x] PR is merged

### Final Actions

After the implementation of the unit tests is over, the relevant pull request will be created and merging to development branch will be done. 

### Deadline of the Issue

31.10.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

01.11.2022 - 23.59

**Comment by gokayyildiz** [comment]
Nicely completed the unit tests, PR is merged issue closed

**Comment by Koraytkn** [comment]
The implementation of the unit tests have finalized, the related updates can be seen at [related pull request](https://github.com/bounswe/bounswe2022group2/pull/467)
