### ISSUE TITLE
Determining Goals and Pre-Conditions for the non-Registered Learner Scenario

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#49]
### Issue Description

I will be creating a prototype for goals and pre-conditions to be used under #47 non-Registered Learner Scenario.
I will document the progress under this issue.

### Step Details

- [x] Goals
- [x] Pre-conditions

### Final Actions

The goals and pre-conditions from this issue shall be used in #47.

### Deadline of the Issue

21.03.2022 Monday 13:00

**Comment by egemenatikk** [comment]
I created the goals for the unregistered learner. Here is the list of goals:

- Since she is not registered to the app yet, firstly she wants to create an account for herself.
- She wants to look at lecturer profiles and take lectures about topics she is interested in from lecturers she choose.
- Then, she intends to earn these lectures' achievements, earn badges and more importantly, learn from them.
- While learning the lectures, she wants to create notes related to the learning material. Thus, she wants to connect, annotate, tag and share these notes.
- Another wish of this users is being able to add friends and text them, personally and in-group.
- This user cares about privacy, so she wants to be able to choose who can see her profile page, achievements, badges. Furthermore, she wants to be able to block other users if she wishes.

It's open to any suggestions, reviews and contributions.

**Comment by egemenatikk** [comment]
I created the pre-conditions for the unregistered learner. Here is the list of pre-conditions:

- She does not have an account for the app, so she has not logged in to the app yet.
- She tries to create her account, so that the initial screen she saw is the "create an account" page.
- She has experience in most of the features of the app like creating notes, taking lectures, earning badges, adding friends, blocking other users.

It's open to any suggestions, reviews and contributions.

**Comment by mbatuhancelik** [comment]
>     * Another wish of this users is being able to add friends and text them, personally and in-group.

I think we should remove this. We have not stated that this scenario should include chatting in the meeting, thus it contradicts with the user story.
