### ISSUE TITLE
Milestone 1: Evaluation of the Status of Deliverables

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#493]
### Issue Description

For the Milestone 1, I will complete the part that presents our evaluations and the status of the deliverables. A part of that work has been done by @onurkomurcu and I will complete the part.

### Step Details

Steps that will be performed:
- [x] Individual Contribution Reports
- [x] Software
- [x] Mobile Deliverables (APK and Manual)
- [x] Group Review

### Deadline of the Issue

04.11.2022 - Friday - 12.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

04.11.2022 - Friday - 20.00

**Comment by gokayyildiz** [comment]
### Individual Contributions Reports
Individual Contributions Reports have been filled with all the work done by each of our group members since the beginning of this semester. It is built as an index-like structure that enables you to access the detail of any issue mentioned or any pull request made by any of our group members. It shows a comprehensive summary of the work done throughout this semester.

Each team member writes just about their work and the whole part was constructed by all of us.
***

### Software

The software product that we have been working on is prepared within the goals determined in the project plan for Milestone 1. Three legs of our team have managed to meet the goals for Milestone 1, so we have a fully working, dockerized, and deployed frontend and backend. We also presented our deployed, working project in class during demo sessions without any fault or bug.

We started to implement the project after deciding on our design criteria and separating the team into sub-teams at the beginning of the semester. Then we started implementing the project within separate teams but constantly communicating with each other.


***

### Mobile Deliverables (APK and Manual)

In addition to the work done by the backend and frontend teams, the mobile team also provided a fully working mobile application and managed to present during in-class demos. The mobile team has also provided a manual to those that are eager to use the app on their local android environments.

The mobile team started to implement their projects after the same process that is mentioned under the Software section and prepared a manual.


***

### Group Review
,
Group Review is the work that is currently done by the team as the final work of Milestone 1. We both evaluate the ongoing project, the tools that have been used, the status of our deliverables, the team members, and the part of the milestone that we have completed so far.

**Comment by gokayyildiz** [comment]
@onurkomurcu  we can review and add it to the final document now

**Comment by onurkomurcu** [comment]
Everything seems great. Thank you, @gokayyildiz !
