### ISSUE TITLE
Milestone 1: Executive Summary 

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#498]
### Issue Description

After the job share for Milestone-1 Report. I have the duty to write an executive summary of our project.

### Step Details

Steps that will be performed:
- [x] Explain the project
- [x] Mention the current status

### Final Actions

After completion, the summary needs to be reviewed.

### Deadline of the Issue

4.11.2022 - 04.00

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

4.11.2022 - 15:00

**Comment by codingAku** [comment]
PR is open. The Pr includes:

Our application is an online learning platform named Learnify, where learning is accomplished through collaboration. Our application name comes from the words Learn and Unify. Each user can add their expertise to the learning space on our platform by adding any content, comments, notes, or even annotations to the already-existing learning materials. The application is not based on teachers and students, it has a forum  where the users who take part a learning space can share their thoughts and recommendation.There are also annotation available for learning space contents so the users can take notes and reminders for theirselves and other users. This features provide ultimate collaboration on learning spaces. Our application works on mobile and web platforms. The current status of our application is that it supports sing-up, login, email verification, forgot password and resend email verification code features. These were the requirements we aimed to implement for Milestone-1.

**Comment by ezgy** [comment]
I've read your summary and have no further suggestions. I've approved and merged pr #499
