### ISSUE TITLE
Frontend: Implementation of Home Page

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#519]
### Issue Description

As we have discussed in our [second frontend team meeting](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%232-of-the-Frontend-Team), as the next step of our web application development I will be implementing the home page of our web application. We have discussed the general layout of the home page and the components that will be present there. Below are the components we have decided upon:
* Header
* My learning spaces
* Popular learning spaces
* Recommended learning spaces
* Activity / feed
* Create learning space button
* Any needed filler illustration

Since header will be a static component of itself, the implementation of the header will be done in a separate issue, this issue is only related to home page only components, which are everything else mentioned above expect the header.

Also, functionalities and endpoints for most of the components like recommended learning spaces, activities, etc. are not ready yet, those components will be filled with draft material like lorem ipsum texts or free images. As the backend development progresses, all of those components will be updated with working functionalities.

### Step Details

Steps that will be performed:
- [x] Create a general design for the home page using [Figma](https://www.figma.com) following the aesthetic guidelines of our web application
- [x] Implement a filler header
- [x] Implement my learning spaces component
- [x] Implement popular learning spaces component
- [x] Implement recommended learning spaces components
- [x] Implement activity / feed component
- [x] Implement create learning space button
- [x] Decide on any needed filler illustration
- [x] Implement the footer
- [x] Update the header after header implementation is done

### Final Actions

I will create a separate branch from our frontend development branch to continue with the implementation. After everything is done and every change is committed, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

07.11.2022 - Monday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

08.11.2022 - Tuesday - 23.59

**Comment by xltvy** [comment]
## Update
I have created the mockup. Here is the screenshot:
<img width="856" alt="Ekran Resmi 2022-11-05 22 37 18" src="https://user-images.githubusercontent.com/68481602/200137953-2298ddbd-056a-4ae8-b451-1566c2992031.png">

I will further implement the home page based on this mockup.

**Comment by Koraytkn** [comment]
This initial design exactly represents the calming, ordered, and cheerful structure of our application. Thank you for your efforts @xltvy. We are all looking forward to seeing the further functional implementation of this colorful home page.

**Comment by xltvy** [comment]
## Update
I have created the PR for this issue. Merging #536 will close this issue.

**Comment by xltvy** [comment]
## Info
Here is the screenshot of the implemented home page:
<img width="1467" alt="Ekran Resmi 2022-11-10 18 49 12" src="https://user-images.githubusercontent.com/68481602/201144746-c8134f1b-b4d8-484e-bb3a-5c675ade5a98.png">

**Comment by xltvy** [comment]
Since #536 is merged, I am closing this issue.
