### ISSUE TITLE
Designing the homepage and profile page templates for the mockups

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#52]
### Issue Description

As part of the general design process for mockups of our Online Learning Platform, I will be designing a homepage and a profile page. The pages will include the features specified in the [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) of our project.

- This issue is a sub-issue of #45 . It will be linked there to easily access but specific details will be under this issue.
- After the initial phase for the profile page requirements is finished, this issue will be closed and reviewing process will continue under the main issue mentioned above.

### Deadline of the Issue

21.03.2022 - Monday - 23.59

Will be reviewed under the main issue after all user requirements are specified.

**Comment by xltvy** [comment]
### Update

I have created a homepage design. Since we have not discussed about and determined a name for our OLP yet, I have used a random name called **"circlespace"**. So, it is a subject to change.

Details about the homepage:
* Since there is not any guest users in our platform, only a sign in and sign up options are available.
* Top categories and featured topics are shown in the homepage, they have been selected randomly in the first draft of the mockup, in the application they will be selected according to the rating and usage.
* There is also a **"view all"** option for "Top Categories" and "Featured Topics" part to browse through categories and topics available in our platform.
* In the navigation bar there are four components:

   > Browse: to browse through the app (courses, people, etc.)
   > Search: semantic search tool
   > Contact: to get in touch with the official's of the platform
   > About: general description about the platform

A preview of the homepage is provided below:

<img width="800" alt="Ekran Resmi 2022-03-20 15 30 22" src="https://user-images.githubusercontent.com/68481602/159350635-689d3084-e87a-49f1-9e68-860cb04a0307.png">

**Comment by ezgy** [comment]
great design for the home page, very vibrant.

**Comment by bahricanyesil** [comment]
Great job @xltvy, thanks for your good work!

Just a small note: we may make sign-in/sign-up buttons more apparent.

**Comment by xltvy** [comment]
> Great job @xltvy, thanks for your good work!
> 
> Just a small note: we may make sign-in/sign-up buttons more apparent.

Thank you! I added a blurred drop shadow for both of these buttons, now it is more apparent I guess. Thank you, for your suggestion too.

**Comment by xltvy** [comment]
### Update

I have created a profile page design. With the draft name and logo of **"circlespace"**. So, it is a subject to change as mentioned.

I used Cosmo Kramer from Seinfeld TV-Series as the character for our profile page example.

Details about the profile page:
* There is an information section on top of the page, including name, avatar, bio, and interests.
* There are three sub-sections under the profile information:
   > Knowledge Base and Achievements
   > Learner Profile
   > Lecturer Profile

A preview of the profile page is provided below:

<img width="800" alt="Ekran Resmi 2022-03-23 18 45 59" src="https://user-images.githubusercontent.com/68481602/159740851-2add09db-d27c-45a8-b0af-b7bb7eebac12.png">
