### ISSUE TITLE
Mobile: Implementing Information Section of Learning Space Detail Screen

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#524]
### Issue Description

After we completed our planned tasks for Milestone-1, we decided to start implementing some learning space-related parts of our application. According to [our third mobile team meeting](), I am assigned by implementing information section in the learning space detail screen. This section will include:

* Image of learning space
* Title of learning space
* Description of learning space
* Categories related to learning space
* Participant number and creator name of learning space

### Step Details

Steps that will be performed:
- [x] Add image to sliver app bar
- [x] Add title to sliver app bar
- [x] Add description to sliver app bar
- [x] Create a generic category widget 
- [x] Add a list of category widgets to sliver app bar
- [x] Add creator name and participant number to sliver app bar
- [x] Add edit icon to right-top of sliver app bar
- [x] Add back navigation icon to left-top of sliver app bar

### Final Actions

After I complete my implementation, I will test the screen on an emulator. If screen works as it should, I will open a pull request to merge my implementation with the base code in the dev branch. After at least one of my team members approve my pull request, I will merge it and close this issue.

### Deadline of the Issue

07.11.2022 - Monday - 23:59

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

08.11.2022 - Tuesday - 15:00

**Comment by egemenatikk** [comment]
I completed implementation of learning space information part in learning space detail screen, here is a screenshot of the finale look of my part: 

![image](https://user-images.githubusercontent.com/100771925/200403424-810cd455-3a19-481d-ae91-8c6db67b48a8.png)

**Comment by ezgy** [comment]
I've reviewed your work and see no problems other than the terminology change of Course -> Learning Space and Chapter -> Post as @onurkomurcu mentioned in his review to pr #528.  If you fix them I can merge it and close this issue.
