### ISSUE TITLE
Frontend: Research on Annotation Implementation

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#526]
### Issue Description

We had discussions about "Annotation's Importance" both with our customers and inside our own development team. Finally, in the second group meeting of our front-end team, this subject was also one of the main topics of the discussion. As can also be seen in the [meeting notes](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%232-of-the-Frontend-Team), we have decided to create a related issue where the members of the front-end team will share their findings after a research process, and the best option, the most appropriate method for our application will be detected. 

### Researchers

- [x] Altay Acar
- [x] Muhammed Enes Sürmeli
- [x] Koray Tekin
- [ ] Mehmet Gökay Yıldız

### Deadline of the Issue

12.11.2022 - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

14.11.2022 - 23.59

### Final To-Dos

- [x] Collected the results of the research via the mentioned channel.
- [x]  Conducted additional research together to integrate the method that has been decided on, into our application.

**Comment by Koraytkn** [comment]
I have found a page that could be useful to ease our implementation of annotations, https://react-annotation.susielu.com/.

**Comment by Koraytkn** [comment]
As far as I understand there are different modules and implementation methods to provide the "Annotations functionality"; they generally differ by the depiction of the annotation specific arrows or the content type of the annotation. For example we can see two different annotation implementations/depictions here:
<img width="480" alt="Screen Shot 2022-11-07 at 18 26 43" src="https://user-images.githubusercontent.com/74411541/200348501-9a7df4d8-4104-49e6-844d-26d0e3baac1e.png">
 
<img width="316" alt="Screen Shot 2022-11-07 at 18 28 02" src="https://user-images.githubusercontent.com/74411541/200348851-3cd690d3-dafe-4d75-8855-b37a05117f99.png">

We can select a design that would fit our current applicatio the best and continue with it.

**Comment by surmelienes1** [comment]
## Update

Thank you @Koraytkn for sharing your findings. I also discovered [a website](https://blog.ceshine.net/post/text-annotation-2/) that would be very helpful to us as we utilize React to construct the frontend counterpart of the project's annotation-related section.

Since annotation on this website is implemented entirely from scratch without the use of pre-made react packages, it may be an excellent example for us to comprehend the background mechanism. Additionally, the code components are supplemented by blog-style posts, which can make it very simple to comprehend and implement the annotation logic.

**Comment by xltvy** [comment]
# Update
Better late than never, I guess I have found a good package to use in our project for implementing the annotation functionality. [Annotatorjs](http://annotatorjs.org) webpage provides a good JavaScript library for implementing the annotation. We can further try it out.

**Comment by gokayyildiz** [comment]
Under the light of the standards defined in [the w3c website](https://www.w3.org/TR/annotation-model/). The website referred by @xltvy is a very good option to follow in terms of implementing the annotations in our web page in a good way. So, it is better to follow the guide after that we have the contents that we want to add annotations.

**Comment by gokayyildiz** [comment]
Since all the research up to now is enough for this issue, further details can be discussed under the issue which is specific for the implementation of the annotations.
