### ISSUE TITLE
POST /ls endpint implementation

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#532]
### Issue Description

To continue with the implementation, we shall be able to perform CRUD operations on learning spaces.
A POST endpoint to initialize learning spaces will be implemented under this issue.

### Step Details

Steps that will be performed:
- [x] Convert course term to learning_space in the backend.
- [x] Initialize the learning space model using Course class diagram.
- [x] Implement the endpoint
- [x] Write tests.

### Final Actions

Upon completion, GET endpoints for the learning_space should be implemented.

### Deadline of the Issue

10.11.2022 23:59

### Reviewer

Ecenur Sezer

### Deadline for the Review

11.11.2022 23:59

**Comment by mbatuhancelik** [comment]
I created the learning space schema alongisde with chapters schema, chapters schema has a many to one relationship with learning spaces. 
Using those schemas I implemented the endpoint, you can find an example input output to the endpoint bellow.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/63948452/201474672-d070a601-0038-44d1-8ee4-ff4db98afc08.png">

**Comment by mbatuhancelik** [comment]
Endpoint also provides additional input in the body names `icon` which is used to set the icon id. This id is an integer between 0 and 20, used to identify the icon in the frontend page.

**Comment by codingAku** [comment]
Related PR is already merged.
