### ISSUE TITLE
Documenting Meeting Notes for the Meeting 6 of CMPE 451

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#535]
### Issue Description

We conducted our weekly meeting on Tuesday, November 8, 2022, at PS hours, like we did the weeks prior. I took notes throughout our conversation this week, so I will write up the meeting notes and post them to our wiki page.

### Step Details

Steps that will be performed:
- [x] The notes I took throughout the meeting will be collected.
- [x] These notes must adhere to the requirements listed on the [Meeting Notes template](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-Notes-Template). The sections that should be in the meeting notes are described in depth in the template.
- [x] Meeting notes should link to the [Home wiki page](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes) and the [Sidebar](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes), if necessary.

### Final Actions

The page will be generated, and then links will be placed in the appropriate areas, such the sidebar.

### Deadline of the Issue

11.11.2022 - Friday - 23:59

**Comment by onurkomurcu** [comment]
We will ask our TA whether we should document the meeting notes for this semester or not. So, this issue can be closed for now. It can be reopened if documenting meeting notes is necessary.

**Comment by surmelienes1** [comment]
## Conclusion

After documenting the meeting notes for the sixth general team meeting, I have connected it to the necessary locations, including [Home wiki page](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes) and [the Sidebar](https://github.com/bounswe/bounswe2022group2/wiki#-meeting-notes).

[The meeting notes](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%236-of-451-(08.11.2022)) can be read for any further information.
