### ISSUE TITLE
Frontend: Learning Space page creation of initial layout

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#541]
### Issue Description

I was assigned this responsibility after the frontend teams' 3. meeting task sharing, I will create the general layout for the learning spaces page and fill the fields with mock objects. 

### Step Details

Steps that will be performed:
- [x] Determine the components needed
- [x] Place the components in a visually satisfying manner  
- [x]  Finalize the page structure
- [x] Consider the UX

### Final Actions

The related branch and PR will be connected to this issue.

### Deadline of the Issue

02.12.2022 - 20.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

03.12.2022 - 23.59

**Comment by Koraytkn** [comment]
<img width="1505" alt="Screen Shot 2022-11-13 at 22 31 06" src="https://user-images.githubusercontent.com/74411541/201540533-2aa65d7f-34a6-4bab-b89e-88752b8aba4e.png">

The initial version of the learning space page can be seen in the image.

**Comment by Koraytkn** [comment]
<img width="1512" alt="Screen Shot 2022-12-01 at 20 43 53" src="https://user-images.githubusercontent.com/74411541/205124096-9ac26f0f-a8eb-4dc8-982b-ed563dd2b8e1.png">

-Entries part made scrollable
-Left-side image updated
-Buttons' content updated 
-Side-boxes updated 
-Entries filled with mock data

**Comment by Koraytkn** [comment]
Related pull-request has been examined and approved by other front-end team members.

**Comment by gokayyildiz** [comment]
I reviewed the work and we can close this issue
