### ISSUE TITLE
Frontend: Create Learning Space Page 

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#543]
### Issue Description

A page to do the creation of a learning space is required to create a learning space. For this purpose we will do the essential part of using a learning space by creating it.

### Step Details

Steps that will be performed:
- [x] Create the layout
- [x] Create the components
- [x] Connect the page to the related button on home page

### Deadline of the Issue

16.11.2022 - Wednesday - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

19.11.2022 - Saturday- 23.59

**Comment by gokayyildiz** [comment]
layout of the page after discussions with the frontend team
![createls](https://user-images.githubusercontent.com/42673110/204840313-3c0a1d8a-3df5-4d9e-8ebf-ad3d5694c829.png)

**Comment by Koraytkn** [comment]
Such a nice design, and great functionality. I am certain that the users will be satisfied with the experience of LS creation.
