### ISSUE TITLE
Determining Chat Requirements

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#55]
### Issue Description

As discussed in meeting#3, we have to determine requirements regarding chat. Our main objective under this issue is to define chat structure. The chat requirements will be under the system requirements on the [wiki](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) page. 

### Deadline of the Issue

21.03.2022 Monday 23:59

### Reviewer

Onur Kömürcü

### Deadline for the Review

22.03.2022 Tuesday 10:00

**Comment by onurkomurcu** [comment]
I reviewed your work. It looks good. I have no question or suggestion regarding this topic. I am closing this issue. Good job!
