### ISSUE TITLE
Frontend: Backend connection of Create Learning Space Page

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#576]
### Issue Description

Backend connection for create learning space page will be implemented according to the design declared in [#551](https://github.com/bounswe/bounswe2022group2/issues/551 ) 

### Step Details

Steps that will be performed:
- [x] Categories connected to list the categories at the Dropdown component
- [x] İnput field implementations
- [x] Post request implementation

### Final Actions

Backend connection completed and pr is merged

### Deadline of the Issue

01.12.2022 - Thursday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

03.12.2022 - Saturday- 23.59

**Comment by gokayyildiz** [comment]
Related PR is merged and main backend connection is made.

**Comment by Koraytkn** [comment]
Flawless connection, thanks!
