### ISSUE TITLE
Providing The Mockups For Registered Lecturer Scenario

### ISSUE THREAD

**Issue by ahmet633** [bounswe/bounswe2022group2#58]
### Issue Description

As determined in [meeting 3](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%233-(17.03.2022)), I will be creating the mockups for the [Registered Lecturer Scenario](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Ta%C5%9Fk%C4%B1ran).

- This issue is a subissue. You can find the parent issue #42 

### Final Actions

After I created the mockups, I will then comment under the parent issue #42 that I completed this task.

### Deadline of the Issue

22.03.2022 - Tuesday - 23.59

**Comment by bahricanyesil** [comment]
Thank you for the design @ahmet633. [Here's ](https://www.figma.com/file/tpvTWyPsigFFyR5f9lYvIl/CMPE352-mockups?node-id=59%3A233) the design link. It's in the same Sigma link with the other scenarios.

I have some questions/feedbacks:
1. If I didn't misunderstand, you meant "learners" with "authorized users". If so, we can change it to something like "enrolled learners".
2. As I remember we will not have built-in video as lectures. So you may remove that section.

I don't have any further things for now apart from these. Thank you for your work!

**Comment by ahmet633** [comment]
Hello @bahricanyesil, about your questions:
1. Yes, I meant learners. I will be changing the text to a more descriptive one (such as 'Learners with access').
2. In the old requirements, it was written as sections could contain video files. Since these requirements changed I will be removing the parts concerning the video files.

**Comment by bahricanyesil** [comment]
Thank you @ahmet633. I don't have any further comment for now. If you are finished, you can close the issue.

**Comment by ahmet633** [comment]
I will be commenting the mockup on the parent issue as well. Also I will be updating the relevant wiki page for the [scenario](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Ta%C5%9Fk%C4%B1ran). Here are the mockup files:
![l1](https://user-images.githubusercontent.com/36857236/159790826-d721962e-6f80-4d74-9df2-21a598979132.PNG)
![l2](https://user-images.githubusercontent.com/36857236/159790839-cef17b7d-aac8-4dc7-aecb-1dbc08c86710.PNG)
![l3](https://user-images.githubusercontent.com/36857236/159790854-d816da2c-bcac-4322-928a-4efe94de92d3.png)
![l4](https://user-images.githubusercontent.com/36857236/159790859-7488dbce-2e9e-417f-9f63-2f343c51cbd5.png)

**Comment by ahmet633** [comment]
I have added click icons for the mock-ups as we decided on our 5th meeting. You can check them [here](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Ta%C5%9Fk%C4%B1ran). Willing to make changes according to the reviews.

**Comment by bahricanyesil** [comment]
Thank you @ahmet633. I have reviewed what you've done. I don't see any problem, it became better with the click icons. We can close the issue.
