### ISSUE TITLE
Home Wiki Page

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#6]
I should create the home wiki page. The wiki page should contain the following sections:
- Team meeting ss that includes the photo of the teammates
- List of the members of the team with their names
(link of their personal wiki pages will be added later on when they are ready as a separate issue)
- Brief introduction, who we are, about part

You can add the sections you want to see as a response to this issue. I can create an issue for them later on.

**Comment by bahricanyesil** [comment]
Created the base home wiki page, you can analyze [here](https://github.com/bounswe/bounswe2022group2/wiki)

**Comment by egemenatikk** [comment]
I have ordered members of our group according to Moodle participants list.
