### ISSUE TITLE
Create the Initial Version of the User Class Diagram

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#60]
### Issue Description

I will create the user class diagram. I will attach the screenshot of the diagram that I created with the help of an online digram tool as comment. First of all, you should consider that this is an initial version of the user class diagram. It may be expanded in the future with the addition of other class diagrams, new features, required attributes and so on.

### Step Details

- [x] I will attach the screenshot of the diagram.
- [x] I will create a wiki page for class diagrams and I will add this initial diagram screenshot. 

### Final Actions

The diagram is open to any suggestion, review and feedback. I will be closing the issue after the review is finished. We can open another issue for the updates/revisions in the future. This issue aims to provide initial layer for the user class diagram, not the complete diagram.

### Deadline of the Issue

27.03.2022 - Sunday - 23:59

### Reviewer

@mbatuhancelik 

### Deadline for the Review

30.03.2022 - Wednesday - 17:00

**Comment by bahricanyesil** [comment]
I created the initial version of user class diagram. Here's the screenshot of it:

<img width="689" alt="Screen Shot 2022-03-26 at 20 53 08" src="https://user-images.githubusercontent.com/60237280/160251483-bc047f39-1932-47c1-8e28-f0f8ad89e5d5.png">

The class attributes are followings:
- userId
- username
- email
- password
- isEmailConfirmed
- isActive
- deviceToken
- createdAt
- updatedAt
- deletedAt
- language

It has the following operations:
+ login
+ register
+ verifyEmail
+ sendVerificationCode
+ forgotPassword
+ changePassword
+ deleteUser
+ getUser

Parameter, response and other type details can be seen in the screenshot. We can add new items or we can remove/update some of them according to your feedbacks.

**Comment by bahricanyesil** [comment]
Now it is ready to be reviewed by @mbatuhancelik and all other team members.

**Comment by bahricanyesil** [comment]
TO ALL TEAM MEMBERS:
I can give you the permission in the online tool that I used to view or edit the diagram if you share your email address with me.

**Comment by bahricanyesil** [comment]
I created a separate wiki page class diagrams. For now I added the ones that I created title by title. In the future we will connect all with ones that will be created and we will create and put only one screenshot containing all details.

You can view the corresponding wiki page [here](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram).

**Comment by mbatuhancelik** [comment]
Can't see anything to be added, or to be removed.
