### ISSUE TITLE
Mobile: Writing Tests of the Text Annotation Feature

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#606]
### Issue Description

I have already implemented the text annotation feature. Now, I will write its unit tests with this issue.

### Step Details

Steps that will be performed:
- [x] Determine the testable parts
- [x] Code separate lines for each testable part
- [x] Run and be sure to pass all tests

### Final Actions

I will run the tests and if the code passes all, I will open a PR. After at least 1 person from the mobile team approved the pull request, it will be merged into the main branch.

### Deadline of the Issue

03.12.2022 - Saturday [23.59]

### Reviewer

Egemen Atik

### Deadline for the Review

04.12.2022 - Sunday [23.59]

**Comment by bahricanyesil** [comment]
I've completed all steps mentioned in the issue description and opened a PR. You can view it [here](https://github.com/bounswe/bounswe2022group2/pull/607).

**Comment by bahricanyesil** [comment]
Here's the successful test pass result:

<img width="372" alt="Screen Shot 2022-12-03 at 00 03 25" src="https://user-images.githubusercontent.com/60237280/205385717-4ab19862-34bd-4b2e-aa05-0e602b336b1c.png">

**Comment by ezgy** [comment]
The pr is merged so this issue is complete
