### ISSUE TITLE
Create the Initial Version of the Token Class Diagram

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#61]
### Issue Description

I will create the token class diagram. I will attach the screenshot of the diagram that I created with the help of an online digram tool as a comment. First of all, you should consider that this is an initial version of the token class diagram. It may be expanded in the future with the addition of other class diagrams, new features, required attributes and so on.

### Step Details

- [x] I will attach the screenshot of the diagram as comment
- [x] I will add the screenshot of the diagram to the class diagrams wiki page created with the issue #60.

### Final Actions

The diagram is open to any suggestion, review and feedback. I will be closing the issue after the review is finished. We can open another issue for the updates/revisions in the future. This issue aims to provide initial layer for the token class diagram, not the complete/final diagram.

### Deadline of the Issue

27.03.2022 - Sunday - 23:59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

30.03.2022 - Wednesday - 17:00

**Comment by bahricanyesil** [comment]
I created the initial version of the token class diagram. Here's the screenshot of it:

<img width="709" alt="Screen Shot 2022-03-26 at 21 03 03" src="https://user-images.githubusercontent.com/60237280/160251937-5aba84a6-0070-4dd3-8d46-5e0da4e8d9e6.png">


The class attributes are followings:
- userId
- refreshToken
- expireDate
- createdAt
- createdByIp

It has the following operations:
+ logout
+ refreshToken

Parameter, response and other type details can be seen in the screenshot. We can add new items or we can remove/update some of them according to your feedbacks.

**Comment by bahricanyesil** [comment]
Now it is ready to be reviewed by @mbatuhancelik and all other team members.

**Comment by bahricanyesil** [comment]
TO ALL TEAM MEMBERS:
I can give you the permission in the online tool that I used to view or edit the diagram if you share your email address with me.

**Comment by bahricanyesil** [comment]
I added this diagram to the class diagram wiki page. You can view it [here](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram).

**Comment by mbatuhancelik** [comment]
LGTM! Closing now to return while determining connections between classes.
