### ISSUE TITLE
Mobile: Image Annotation Cropped Preview - Annotations Screen

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#614]
### Issue Description

My teammate Ezgi is implementing an annotations screen. Since this screen is strongly connected to the annotation screen and its functionalities, and dependencies, It's my responsibility to adapt and adjust the annotation feature for this screen. We need to show multiple annotations if there is more than one annotation for a text. We also need to show a preview of the intersected rectangle area for a clicked point on an image if there are multiple annotations there.

### Step Details

Steps that will be performed:
- [x] Change the parameters of the annotations screen to get a list of annotations
- [x] Change annotate callback actions to show an annotation screen instead of a text dialog
- [x] Implemented CroppedImagePainter to show annotated image part as a preview in the annotations screen
- [x] Found unique annotations to display multiple annotations which annotated the same part
- [x] Fixed start and end offset assigns to avoid minus subtraction values, start offset is set as it is always less than the end offset
- [x] Implemented future builder and get image method to load the cropped image.
- [x] A lot of design improvements in the annotations screen

### Final Actions

I've completed all steps mentioned in the issue description. All these changes will be implemented under the branch Ezgi opened. You can view it [here](https://github.com/bounswe/bounswe2022group2/pull/613).

### Deadline of the Issue

03.12.2022 - Saturday [23.59]

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

04.12.2022 - Sunday [23.59]

**Comment by bahricanyesil** [comment]
All of the mentioned steps are completed and pushed as commits under the branch "mobile/annotation-screen-560". [Here](https://github.com/bounswe/bounswe2022group2/pull/613) is the corresponding PR. You can see the details of my contributions in [this comment](https://github.com/bounswe/bounswe2022group2/pull/613#issuecomment-1335968876).

**Comment by bahricanyesil** [comment]
Here's a video recording demonstrating the work done with this PR:

https://user-images.githubusercontent.com/60237280/205410322-63088202-e426-4b84-acbd-a0cbf63ebcae.mp4

**Comment by bahricanyesil** [comment]
It is ready to be reviewed by @ezgy.

**Comment by ezgy** [comment]
I've tested the part you implemented and it works great. Thank you for the help!
