### ISSUE TITLE
Reviewing User Interaction Requirements

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#62]
### Issue Description

User Interaction in User Requirements defined under #23 shall be revised according to our TA Egemen İşgüder's advices. While doing so, its beneficial to check their integrity with other requirements.

Note: 1.1.3.2.5 Community Events is not created by me, so I wont lay a hand on it.

  

### Final Actions

Merging the requirements defined there to wiki page.

### Deadline of the Issue

27.03.2022 - Sunday - 23.59

### Reviewer

@ezgy 

### Deadline for the Review

28.03.2022 - Monday - 23.59

**Comment by mbatuhancelik** [comment]
<details><summary> 1.1.3 👩🏼‍💻 User Interaction</summary><blockquote>

<details><summary>1.1.3.1. User-User Interaction</summary>

* 1.1.3.1.1. Users shall see each others profiles. 

* 1.1.3.1.2. Users shall be able to track each other.

* 1.1.3.1.3. Users shall see information regarding people they track such as tracked persons profile, achievements, and activities.

* 1.1.3.1.4. Users shall be able to share notes with each other.

</details>

<details><summary> 1.1.3.2. User-Lecture Interaction</summary>
<blockquote>
<details><summary> 1.1.3.2.1. Creating Lectures</summary>

* 1.1.3.2.1.1. Lecturer shall state the lectures topic in a specified field for sake of categorization.

* 1.1.3.2.1.2. Lectures shall deliver lecture material in text, images, and embedded videos.

</details>

<details><summary>1.1.3.2.2. Editing Lectures</summary>

* 1.1.3.2.2.1. Lecturer shall be able to edit lecture material.

* 1.1.3.2.2.2. Lecturer shall be able to delete lectures.

* 1.1.3.2.2.3. Lecturer should be able to set his/her lecture as private or public.

* 1.1.3.2.2.4. Lecturer should be able to set a part of the lecture as private.

</details>

<details><summary> 1.1.3.2.3. Taking Lectures</summary>

* 1.1.3.2.3.1. User shall see the content within sections as lecturer intended.

* 1.1.3.2.3.2. Users shall navigate in lecture material.

* 1.1.3.2.3.3. Users shall see which parts of the lecture they completed.

* 1.1.3.2.3.4. Users shall be notified type of the poll they are taking beforehand.

* 1.1.3.2.3.5. Users shall receive confirmation of their expertise on the topic upon completion of a lecture. 

* 1.1.3.2.3.6. Users shall be able to rate lectures. 

</details>

<details><summary> 1.1.3.2.4. Notes and Annotation</summary>

* 1.1.3.2.4.1. Each user shall have his/her notes section under each lecture.

* 1.1.3.2.4.1. User shall keep notes under notes section via typing.

* 1.1.3.2.4.2. User shall be able to  mention other notes from other lectures or/and other users in his/her.

* 1.1.3.2.4.2. Mentions shall create a link from mentioning note to mentioned note.

* 1.1.3.2.4.3. Users shall annotate lecture content by matching lecture content to notes.

</details>

</details>
<blockquote>
</blockquote></details>

A prototype is given above.  Changes made are:

* 1.1.3.3 Browsing is removed since it is duplicate

* Previously I used a section, chapter structure derived from LaTex to describe editing and progress tracking. This structure is removed. Section and Chapter shall be removed glossary.

* 1.1.3.2.2.2 Lecturer shall be able to delete lectures. added

* 1.1.3.2.3.7. Lectures shall include a communication channel where user can interact with other users and the lecturer. This channel is to be defined is removed as chat requirements are stated under #55 .

* 1.1.3.2.4. Notes and Annotation has now more detailed requirements

* 1.1.3.1.5. Users shall be able to organize meetings by specifying 3 fields: duration, geolocation, date. is removed since community events are now described under 1.1.3.2.5

* Markdown fixes

**Comment by ezgy** [comment]
The changes made have improved the section. The overall structure proposed seems very well and includes all points discussed. 

Some suggestions:
* On 1.1.3.2.3.1 "User" could be "Users" in order to better fit the rest of them.
* Section and Chapter have been removed from the glossary as suggested, but I noticed section is still used in the prototype under 1.1.3.2.3.1 and 1.1.3.2.3.7. Do you think _section_ should be defined within the context of the platform (and thus included in the glossary) or should we assume it is used in its default meaning?  
* 1.1.3.2.4.2 Seems unnecessary as it reiterates the meaning of notes and doesn't add functionality.  Maybe rewriting to focus more on application functionality (for example "create notes" instead of "keep") could be better.   
* 1.1.3.2.4.4 is a system requirement.  

There are no major changes to be made,  this issue can be closed once the prototype has been merged to the requirements page. Great work 🚀

**Comment by mbatuhancelik** [comment]
> * Section and Chapter have been removed from the glossary as suggested, but I noticed section is still used in the prototype under 1.1.3.2.3.1 and 1.1.3.2.3.7. Do you think _section_ should be defined within the context of the platform (and thus included in the glossary) or should we assume it is used in its default meaning?

Yes it is in default meaning.

After implementing your suggestions, I merged changes to the wiki page

**Comment by egemenatikk** [comment]
I have added the following entry under the 1.1.3.1 👩🏼‍💻 User Interaction requirements:

1.1.3.1.5. Users shall be able to block other users to decide who can see their profile pages.

I have removed this entry from the privacy requirements last week and decided that it would fit under User Interaction requirements. Also, I have removed unnecessary empty lines under this requirement.
