### ISSUE TITLE
Learning Space Making modular and providing the back-end connection

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#624]
### Issue Description

While Learning space, keeps improving in terms of content, and style; a need for back-end connection and modularization of this page has occurred.

### Step Details

Steps that will be performed:
- [x] Providing modularization. 
- [x] Connecting back-end endpoints.

### Final Actions

Via the provided modularization, this component will be benefited from other pages.

### Deadline of the Issue

03.12.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

03.12.2022 - 23.59

**Comment by Koraytkn** [comment]
Implementation has been finalized.

**Comment by Koraytkn** [comment]
@gokayyildiz You can view the changes via this [issue](https://github.com/bounswe/bounswe2022group2/tree/dev-frontend-backend-of-ls)

**Comment by gokayyildiz** [comment]
Related changes are reviewed and connections are made according to your design. I now close the issue.
