### ISSUE TITLE
Frontend: Connection of create ls page with created ls page

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#625]
### Issue Description

By communicating with the group members we need to make connections between create-ls page and created ls page via props.

### Step Details

Steps that will be performed:
- [x] Connection implemented

### Deadline of the Issue

03.12.2022 - Saturday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

04.12.2022 - Sunday- 23.59

**Comment by Koraytkn** [comment]
I have reviewed the related [pull request](https://github.com/bounswe/bounswe2022group2/pull/627) for this issue, seems like modularization is finalized; thanks for your contribution.
