### ISSUE TITLE
Determining Admin Requirements

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#65]
### Issue Description

I will be determining admin requirements which will be consistent with the all requirements. All the progress can be seen from here. If you have any suggestion and question regarding this topic, feel free to contribute. 

### Deadline of the Issue

27.03.2022 - Sunday - 23.59

### Reviewer

Egemen Atik

### Deadline for the Review

28.03.2022 - Monday - 23.59

**Comment by onurkomurcu** [comment]
* Admin shall evaluate reports and takes action accordingly.
* Admin shall be able to ban users permanently and temporarily.
* Admin shall be able to view all contents.
* Admin shall be able to remove any content.

These are the admin requirements should be included in the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements). It will be seperate section under User Requirements as Administration.

**Comment by egemenatikk** [comment]
If I remember correctly, our platform should resemble Wikipedia in terms of users' contribution. I think Admin can control these contributions, whether they are correct, related to subject or not.

By saying "Admin shall evaluate reports and takes action accordingly", did you also mean the requirements I talked about above. If not, should we add it as another entry under Admin requirements?

**Comment by onurkomurcu** [comment]
If admin has no background about the course, s/he cannot evaluate whether a content is eligible to publish or not. So, this control mechanism should be done by lecturer. We can indicate this requirement under **1.1.3.2.2. Editing Lectures** section  as an entry. If there is ethical or privacy kind of concerns, admin shall check this issue. We can differentiate these kind of reports, so reports can be evaluated by relevant users and evaluation process will be more accurate with this way. I think that report system has to be clarified in the requirements under **2.2. Privacy** section. 

I'm looking forward for your thoughts about this idea. Do you think it is convenient enough to be implemented?

**Comment by onurkomurcu** [comment]
Thank you for your review @egemenatikk. It was good to mention. This review topic was discussed in meeting 5. Admin will be selected by the lecturer for his/hers course(s). Thus, we didn't specify report system. If this is necessary to specify, we will include to the requirements. For this moment, current admin requirements are adequate with respect to our assistant's feedback and our discussion. If you have any question and suggestion about this topic, please reopen this issue and contribute.
