### ISSUE TITLE
Frontend: Implementation of Edit Post Feature

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#659]
### Issue Description

We should have a page component where co-learners can edit existing posts which are located in learning space posts section.

This component will include three input fields, one for entering the title of post and one for entering the image url for the post, and the final one for entering the contents of the post. While editing an existing post, these input fields will contain the existing post's data.

Finally, there will be a submit button indicating that editing is done.

### Step Details

Steps that will be performed:
- [x] Add edit post model
- [x] Create edit post component design
- [x] Add input fields and button to page
- [x] Edit navigation routes

### Final Actions

I will create a branch from the frontend development branch to address this specific issue. After completing all of the above activities, I will generate a pull request in accordance with the issue. I will be committing the modifications to that branch throughout the development phase. This issue will be resolved once the PR is accepted and integrated into our development branch.

### Deadline of the Issue

05.12.2022 - Monday - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

06.12.2022 - Tuesday - 10.00

**Comment by xltvy** [comment]
Since #661 is merged, closing this issue.
