### ISSUE TITLE
Reviewing Community Events Requirement

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#66]
### Issue Description

I will be adding the discussed features about creating, canceling, joining, and displaying to the community events section of our wiki page.

### Deadline of the Issue

28.03.2022 - Sunday 23.59

### Reviewer

Batuhan Çelik

### Deadline for the Review

30.03.2022 - Wednesday 23.59

**Comment by codingAku** [comment]
You can check our [wiki page](https://github.com/bounswe/bounswe2022group2/wiki) under the User Lecture Interaction - Community Events section for the changes I have made.

**Comment by mbatuhancelik** [comment]
1.1.3.2.5.3. These events are only specified for various courses. 
This one seems like needs more clarification.
Other requirements look good to me.

**Comment by codingAku** [comment]
The section 1.1.3.2.5.3 has been updated. Thank you for the review.

**Comment by codingAku** [comment]
I have changed the "these events" phrase to "created events" in requirements, Community Events section.
