### ISSUE TITLE
Frontend: Backend Connection For Edit Post

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#660]
### Issue Description

I have prepared edit post section of the learning space page but it does not yet send post request to our backend service to edit the post. 

Now, it is time to provide the backend connection to edit post component so that proper requests can be sent and edited posts can be put to our database.

### Step Details

Steps that will be performed:
- [x] Determine request model
- [x] Determine response model
- [x] Determine functions needed
- [x] Add these function calls to proper places in code
- [x] Test the connection

### Final Actions

I will create a branch from the frontend development branch to address this specific issue. After completing all of the above activities, I will generate a pull request in accordance with the issue. I will be committing the modifications to that branch throughout the development phase. This issue will be resolved once the PR is accepted and integrated into our development branch.

### Deadline of the Issue

05.12.2022 - Monday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

06.12.2022 - Tuesday - 10.00

**Comment by xltvy** [comment]
Since #661 is merged, closing this issue.
