### ISSUE TITLE
Backend: Unit Tests for Edit Post Endpoint

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#665]
### Issue Description

Now that our edit posts endpoint is implemented on #600 , I will implement the related unit tests.

### Step Details

Steps that will be performed:
- [x] Implement the unit tests.
- [x] Create a PR

### Final Actions

The related PR merge will close the issue.

### Deadline of the Issue

6.12.2022 - 04:00

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

6.12.2022 - 12:00

**Comment by codingAku** [comment]
Related PR #666 is open.

**Comment by mbatuhancelik** [comment]
I merged the PR, closing the issue.
