### ISSUE TITLE
Adding My Events requirement to User Profile Page

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#67]
### Issue Description

This issue is about the community events section. We have decided that users will have a "my events" section on their profile page. I will add the details to the Profile Page section of our wiki.

### Deadline of the Issue

28.03.2022 - Monday 23.59

### Reviewer

Batuhan Çelik

### Deadline for the Review

30.03.2022 - Wednesday 23.59

**Comment by codingAku** [comment]
Under the Profile Page section in Requirements, these have been added:
* 1.1.2.7. Users shall have a "My Events" section on their profile pages.
* 1.1.2.7. Users who are qualified as "Lecturer" will see the events they have organized on their "My Events" section with the headline: "You are the organizer!".
* 1.1.2.7. Users who are qualified as "Learners" will see the events they are participating in on their "My Events" section with the headline: "You are participating!".

**Comment by mbatuhancelik** [comment]
Cant see anything more or less than required. LGTM!
