### ISSUE TITLE
Milestone-2 Report: API Documentation

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#677]
### Issue Description

On our Milestone-2 Report, APIs implemented since Milestone-1 needs to be documented over postman and linked to the report.
@mbatuhancelik and @codingAku will document the endpoints and add examples.

### Step Details

Steps that will be performed:
- [x] Document endpoints
- [x] Link postman with brief status.

### Final Actions

Related PR merges on both developers will close the issue.

### Deadline of the Issue

8.12.2022 - 00.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

9.12.2022 - 14.00

**Comment by codingAku** [comment]
Related PR #685 open.

**Comment by mbatuhancelik** [comment]
I added my part to the doccumentation. I guess Ece added her part to, I will have it checked by Ece and then we can send it for the review.
