### ISSUE TITLE
Frontend: Unit Tests for Learning Spaces by Categories Page

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#679]
### Issue Description

The development of the learning spaces by category page was strongly dependent on the other parts of our web application. Thus, it was not ready for unit test by the second customer demo. However, since the learning spaces by category page is now complete, we need to test it by using unit tests before getting it done completely.

So, I will implement unit tests for the categories page and provide results here.

### Step Details

Steps that will be performed:
- [x] Test the page snapshot
- [x] Test if components are rendered correctly
- [x] Share results

### Final Actions

I will create a separate branch on our frontend development branch and then do the implementation of the unit testing. When everything is set and done, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

07.12.2022 - Wednesday - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

08.12.2022 - Thursday - 23.59

**Comment by xltvy** [comment]
## Update
I have implemented unit tests regarding the learning spaces by category page. Here are the resutls:

<img width="508" alt="Ekran Resmi 2022-12-07 23 17 37" src="https://user-images.githubusercontent.com/68481602/206287620-1558cfbd-b411-4303-ab5f-2a079bc1645a.png">

**Comment by xltvy** [comment]
Any implementation detail can be tracked from #680

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your valuable contributions! I ran the tests you have implemented on my local system, and they all worked as expected.

Since I have nothing else to add at this time, I will now close this issue. You can reopen this issue and add your comments if you have any new questions or recommendations.
