### ISSUE TITLE
Frontend: Unit Tests for Not Found Page

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#681]
### Issue Description

The other components of our web application influenced how the not found page was developed. Because of this, by the second customer demo, it was not ready for a unit test. Since the not found page is now finished, we must use unit tests to test it before finishing it entirely.

I will implement unit tests for the not found page and share the results in the comment section below.

### Step Details

Steps that will be performed:
- [x] Test the page snapshot
- [x] Test if components are rendered correctly
- [x] Share results

### Final Actions

I will create a branch from the frontend development branch to address this specific issue. After completing all of the above activities, I will generate a pull request in accordance with the issue. I will be committing the modifications to that branch throughout the development phase. This issue will be resolved once the PR is accepted and integrated into our development branch.

### Deadline of the Issue

08.12.2022 - Thursday - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

09.12.2022 - Friday - 14.00

**Comment by xltvy** [comment]
Since #683 is merged, closing this issue.
