### ISSUE TITLE
Frontend: Unit Tests for Navigation Bar and Semantic Search Component

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#682]
### Issue Description

The development of the navigation bar and semantic search component was strongly dependent on the other parts of our web application. Thus, it was not ready for unit test by the second customer demo. However, since the navigation bar and semantic search component is now complete, we need to test it by using unit tests before getting it done completely.

So, I will implement unit tests for the navigation bar and semantic search component and provide results here.

### Step Details

Steps that will be performed:
- [x] Test the component snapshot
- [x] Test if sub-components are rendered correctly
- [x] Test if buttons work properly
- [x] Test if input fields work properly
- [x] Share results

### Final Actions

I will create a separate branch on our frontend development branch and then do the implementation of the unit testing. When everything is set and done, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

07.12.2022 - Wednesday - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

08.12.2022 - Thursday - 23.59

**Comment by xltvy** [comment]
## Update
I have implemented unit tests regarding the `NavBar.js` component. Here are the resutls:

<img width="523" alt="Ekran Resmi 2022-12-07 23 42 36" src="https://user-images.githubusercontent.com/68481602/206292372-f08b0e94-fb1f-4a48-8dd3-54b82b484d82.png">

**Comment by xltvy** [comment]
Any implementation detail can be tracked from #684

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your valuable contributions! I ran the tests you have implemented on my local system, and they all worked as expected.

Since I have nothing else to add at this time, I will now close this issue. You can reopen this issue and add your comments if you have any new questions or recommendations.
