### ISSUE TITLE
Frontend: Unit Testing Initialization for Dropdown, SelectionGrid, JoinLSButton Components

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#695]
### Issue Description

In terms of functionality, the dropdown, selection grid and join button serves us as expected during the whole preparation time and during the demo. They are still well functioning in any use. In this issue, I will initialize a unit testing structure to make this components testable without any further need. So this initialization and tests will be useful when it comes to adding new feature to these components.

### Step Details

Steps that will be performed:
- [x] Unit test for Dropdown
- [x] Unit test for SelectionGrid
- [x] Unit test for JoinLS button

### Deadline of the Issue

08.12.2022 - Thursday - 19.59

### Reviewer

Koray Tekin

### Deadline for the Review

08.12.2022 - Thursday - 23.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! I have run all the test you have written on my local and they worked as expected! I will now close this issue since the related pull request has been merged.
