### ISSUE TITLE
Software Design: Use Case Diagram - Non Lecture related use cases

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#70]
This is a sub issue from #71 

### Issue Description

As we discussed in meeting 5(URL to be added), there are use cases not related to viewing a single lecture. They need to be added to our use case diagram.

Following people are responsible for creating diagrams in-line with requirements, maintain integrity between diagrams ,and asking for requirement updates when needed:

@mbatuhancelik 
@egemenatikk 
@codingAku 
@surmelienes1 

### Step Details

Cases That will be handled:
- [x] Authentication
- [x] Viewing profiles 
- [x] Chat
- [x] Viewing Homepage
- [x] Searching - Browsing

### Final Actions

- [x] Check overall integrity between diagrams created here and all diagrams.
- [x] Check overall integrity between diagrams created under this issue.
- [x] Merge Diagrams
- [x] Get reviewed by reviewer
- [x] Get reviewed by all members of the group at the meeting at 02.04.2022 Saturday 15.00
- [ ] Add diagrams to wiki page

### Deadline of the Issue

02.01.2022 Saturday 14.00

### Reviewer

Altay Acar

### Deadline for the Review

02.01.2022 Saturday 15.00

**Comment by mbatuhancelik** [comment]
I created #72 to create the use case diagram for signing in.

**Comment by surmelienes1** [comment]
I completed all of the pre-checks and implemented the viewing profile part of the use case diagram. @xltvy reviewed and approved my work in the #73

**Comment by mbatuhancelik** [comment]
Authentication diagrams are completed under #72 and reviewed by all in our class diagram meeting.

**Comment by xltvy** [comment]
Non Lecture related part of the Use-Case Diagram is completed and reviewed by the whole class in the [use-case review meeting](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%235.1---Class-Diagram-Meeting-(02.04.2022)). So, I am closing this issue.
