### ISSUE TITLE
Software Design: Use Case Diagram - Viewing Profiles

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#73]
### Issue Description

* This is a sub issue of the #70.

* The use case diagram for viewing profiles and actions related to these viewed profiles will be created under this issue.

* The [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) to be covered by these use cases will be shared here.

* The use case diagram will be generated using the Lucichart app, and the related link will be shared here.

### Final Actions

* The Use Case Diagram to be generated here must be combined with the use case diagrams of the other team members at #70.

### Deadline of the Issue

02.04.2022 - Saturday - 14.00

### Reviewer

Altay Acar

### Deadline for the Review

02.04.2022 - Saturday - 15.00

**Comment by surmelienes1** [comment]
## Information 1
The [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) that will be covered in this part of the use-case diagram are provided below:

### Change Password
* 1.1.1.6.1. Users shall be able to request a password change in their profile screens.

### 🗿 Profile Page

* 1.1.2.2. Users shall be able to edit their profile page.

* 1.1.2.4. Users shall have an avatar.

* 1.1.2.5. Users shall be able to change their avatars.

* 1.1.2.6. Users shall have a bio in their profile pages.

* 1.1.2.7. Users shall have a "My Events" section on their profile pages.

#### Interests and Knowledge

* 1.1.2.10.1. Users shall identify their interest areas and display them in their profile pages.

* 1.1.2.10.2. Users shall view the knowledge base, consisting the courses, they have successfully completed.

#### Achievements

* 1.1.2.11.1. Users shall view the achievements they earned from the courses they have studied in the achievements section of their profile pages.

* 1.1.2.11.2. Users shall be able to change the achievements, which are displayed in the achievements section of their profile pages.

#### Learner Profile

##### - Progress Tracking

* 1.1.2.13.1.1. Users shall be able to see the courses they have provided teaching material as a lecturer and their reputation in their profile pages.

* 1.1.2.13.1.3. Users should be able to enroll a course, which is provided by the owner of the profile page from the lecturer profile section.

##### - Lecture Notes

* 1.1.2.12.2.1. Users shall view their notes taken from the courses in the lecture notes section of their profile pages.

* 1.1.2.12.2.2. Users shall view the most recent time of edit for each lecture note.

##### - Annotations

* 1.1.2.12.3.1. Users shall access the annotations they have added for course material from the annotations section of their profile pages.
Change Password

#### Lecturer Profile

##### - Courses and Reputation

* 1.1.2.13.1.1. Users shall be able to see the courses they have provided teaching material as a lecturer and their reputation in their profile pages.

* 1.1.2.13.1.3. Users should be able to enroll a course, which is provided by the owner of the profile page from the lecturer profile section.

##### - Recommendation

* 1.1.2.13.2.1. Users shall be able to see the feedback they have received for the courses they provide teaching material in the recommendations section.

* 1.1.2.13.2.2. Users shall be able to view comment and star rating for each feedback, alongside the commentator’s name and first letter of their surname, a basic profile picture with their initials, and the name of the course.

***

## Information 2
The mockup section for the related part is the following one:
* Viewing Profile Page

![](https://user-images.githubusercontent.com/68481602/159740851-2add09db-d27c-45a8-b0af-b7bb7eebac12.png)

***

## Information 3
I have completed the corresponding part of the diagram. You can see it directly [here](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c&page=0_0#).

Additionally, here's the screenshot of the corresponding part:
<img width="1062" alt="Screen Shot 2022-04-02 at 22 52 25" src="https://user-images.githubusercontent.com/74325266/161399028-d1a3bd84-036e-4019-b5e7-277d33c9a249.png">

***

## Information 4
I completed all of the pre-checks and implemented the use case diagram. So it is ready for @xltvy's review. Since we have already reviewed the use case diagram in our meeting today, it seems not to have more aspects to discuss further. However, all the team members are encouraged to provide feedbacks for the final diagram.

**Comment by xltvy** [comment]
I have reviewed the viewing profile pages part of the use-case diagram one last time. I think it is good enough. Thank you for your comprehensive work! I am closing the issue.
