### ISSUE TITLE
Software Design: Use-Case Diagrams - Searching, Browsing and Viewing Homepage

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#74]
### Issue Description

This is a sub-issue of #70. In Use-Case Diagrams, I will be completing the Searching and Viewing Homepage parts. 

These use cases shall cover 1.2.3. from [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) and Mock-ups of [Registered-User Scenario](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Ta%C5%9Fk%C4%B1ran).

Diagram in [Lucichart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Step Details

Steps that will be performed:
- [x] Checking mock-ups for homepage.
- [x] Checking requirements for searching properties.
- [x] Create a registered user on diagram.
- [x] Complete the diagram on related topics on Lucidchart.

### Deadline of the Issue

2.04.2022 - Saturday 14.00

### Reviewer

This issue will be reviewed under #70 

### Deadline for the Review

2.04.2022 - Saturday 15.00

**Comment by codingAku** [comment]
UPDATE: All tasks related to the issue has been completed. "About" and "Contact" pages need more detail for me to add to diagram. 
Important Note: On Lucidchart, ecenurSezer and Ecenur Sezer are both me. I accidently created an account with my personal e-mail and needed to switch to my college e-mail adress. All work done by these two user is done by me.

**Comment by mbatuhancelik** [comment]
I think some <<includes>> relations in the graph should be <<extends>> relations for example, browsing shall be extended by browsing lectures, browsing users, and browsing notes.

**Comment by codingAku** [comment]
Sections one View Homepage has been moved to user actions with extending View Homepage. "Includes" and "extends" tags have been deleted and new ones added. Thank you.

**Comment by xltvy** [comment]
Thank you for your comprehensive work! I have reviewed the searching, browsing, and viewing homepage section of the use-case diagram. Here are some points I would like to mention:
* We may add some details about what **about** and **contact** pages will be consisted of. These details are definitely a subject of further discussion in a meeting. This is a notification for the upcoming days.
* For the **browse** part, we may add an option of browse categories (such as math, science, coding - these should not be in the use-case diagram right now, it is only for clear explanation)
* For the search part, I think providing an option as an extension tag for the sorting of search results also needed. For example, sort by the course rating, sort by the number of followers, sort alphabetically etc.

**Comment by codingAku** [comment]
> Thank you for your comprehensive work! I have reviewed the searching, browsing, and viewing homepage section of the use-case diagram. Here are some points I would like to mention:
> 
> * We may add some details about what **about** and **contact** pages will be consisted of. These details are definitely a subject of further discussion in a meeting. This is a notification for the upcoming days.
> * For the **browse** part, we may add an option of browse categories (such as math, science, coding - these should not be in the use-case diagram right now, it is only for clear explanation)
> * For the search part, I think providing an option as an extension tag for the sorting of search results also needed. For example, sort by the course rating, sort by the number of followers, sort alphabetically etc.

Thank you so much for the review. I agree with first two comments, however, the last one is not on our requirements. Since this will be a contradiction, I believe they shouldn't exist on our diagram.

**Comment by xltvy** [comment]
> > Thank you for your comprehensive work! I have reviewed the searching, browsing, and viewing homepage section of the use-case diagram. Here are some points I would like to mention:
> > 
> > * We may add some details about what **about** and **contact** pages will be consisted of. These details are definitely a subject of further discussion in a meeting. This is a notification for the upcoming days.
> > * For the **browse** part, we may add an option of browse categories (such as math, science, coding - these should not be in the use-case diagram right now, it is only for clear explanation)
> > * For the search part, I think providing an option as an extension tag for the sorting of search results also needed. For example, sort by the course rating, sort by the number of followers, sort alphabetically etc.
> 
> Thank you so much for the review. I agree with first two comments, however, the last one is not on our requirements. Since this will be a contradiction, I believe they shouldn't exist on our diagram.

Considering its absence from requirements, I also think that we can close this issue without any addition about third point. However, let us note this down for further discussion in the future, if such a feature will be required.
