### ISSUE TITLE
Software Design: Use Case Diagram - Admin User and Course Creation Sections of the Use Case Diagram

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#75]
## Issue Description

* This is a sub issue of the #71.

As the first step of our design work for our online learning platform, we will create our **Use Case Diagram**. For each member of the team to work on **Use Case Diagram** we have divided it into subsections and each member will comprehensively determine their assigned part. Each part then will be evaluated and reviewed by other members. Three subsection is provided below:

- [Admin User and Course Creation](https://github.com/bounswe/bounswe2022group2/issues/75)
- [Non-Lecture Related Use Cases](https://github.com/bounswe/bounswe2022group2/issues/70)
- [Enrolled Course Actions](https://github.com/bounswe/bounswe2022group2/issues/69)

This structure may be enhanced/enlarged and new base titles can be added in the future. If you can find, you can write them as a  comment to this issue.

According to our decision in meeting 5, responsible people for the **Admin User and Course Creation** are, the sub issues regarding personal work will be provided alongside the names upon creation:
- [ ] [Ahmet Yiğit Özdoğan](https://github.com/bounswe/bounswe2022group2/wiki/Ahmet-Yiğit-Özdoğan)
- [x] [Altay Acar](https://github.com/bounswe/bounswe2022group2/wiki/Altay-Acar) - #77 
- [x] [Ezgi Aysel Batı](https://github.com/bounswe/bounswe2022group2/wiki/Ezgi-Aysel-Batı) - #79 

These people will create separate issue for the subtitle s/he work and will link those issues under this main issue with a summary comment.

There is a one reviewer for this issue and she will review what the assignees found, what others are commented at the end and will make the last sentences before closing the issue to be sure that everything works well.

**Deadline: 02.04.2022 - Saturday - 14.30**
**Reviewer: [Ecenur Sezer](https://github.com/bounswe/bounswe2022group2/wiki/Ecenur-Sezer)** - Deadline: 05.04.2022 - Tuesday - 17.00

**Comment by ezgy** [comment]
I will be working on adding admin operations to the use case diagram. For details about progress see #79

**Comment by xltvy** [comment]
Use case diagram is reviewed by whole class and finalized. We were waiting for a response from @ahmet633 to close the issue. But, since he has not responded yet and the diagram is ready, I am closing this issue.
