### ISSUE TITLE
Mobile: Research on Map Packages in Flutter

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#751]
### Issue Description

We will integrate maps into our mobile application in the events section to show the event location by using the geolocation standard. We need to find and integrate a **free** package into our app to visually show the event location using the coordinates. With this issue, possible solutions will be searched and the results will be shared under as comments.

### Step Details

Steps that will be performed:
- [x] Look at possible map packages
- [x] Analyse their billing settings
- [x] Look at their input parameters and capabilities
- [x] Select the most appropriate one by indicating the reasons

### Final Actions

After the research has been done, all research results will be shared under comments. Finally, the most suitable package will be selected and it will be used in our application.

### Deadline of the Issue

19.12.2022 - Monday [23.59]

### Reviewer

Egemen Atik

### Deadline for the Review

20.12.2022 - Tuesday [23.59]

**Comment by bahricanyesil** [comment]
I've completed my research and found the following packages possible to integrate:

[**1. Google Maps**](https://pub.dev/packages/google_maps_flutter)
It's the most common, reliable, and easy-to-implement solution for maps. However, they changed their policy and removed the free tier for using the API. Instead, they give free usage monthly at a fixed fee and they require a billing account. Even though I researched some workarounds to have a free testing API key, finding a solution that clearly has a free tier is a better idea. Therefore, we will not use Google Maps and will look at other alternatives.

[**2. Yandex Maps**](https://pub.dev/packages/yandex_mapkit)
Yandex Maps is also another common way to use. However, the package is developed by an unverified publisher and it has fewer likes (which is important in pub.dev). It is also hard to integrate into the app and customizing it requires more time. I have already created a free API Key on the Yandex Developer console, integrate it with the native files of the app, and render a Yandex Map in the app. However, we can find an easier and better solution than this.

[**3. Open Street Map - Flutter Map**](https://pub.dev/packages/flutter_map)
Open Street Map is a widely-used, open-source, completely free solution. Therefore, this one could be the best solution for us if it is also easy to integrate into our app with Flutter. I found two packages: [flutter_map](https://pub.dev/packages/flutter_map) and [flutter_osm_plugin](https://pub.dev/packages/flutter_osm_plugin). My choice is to use the flutter_map since it is more common and easy to customize with lots of examples.

**Comment by bahricanyesil** [comment]
As it is stated in the above comment, Open Street Map will be integrated into the app with the Flutter Map package. The issue will be closed after the review of @egemenatikk.

**Comment by onurkomurcu** [comment]
I reviewed your work, @bahricanyesil. It will be useful when we are implementing the events functionality. Thank you for your great research!

**Comment by bahricanyesil** [comment]
Thanks for the quick review @onurkomurcu!
