### ISSUE TITLE
Software Design: Use Case Diagram - Course Creation

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#77]
### Issue Description

As part of the software design process, we, as the whole team, will provide a use case diagram for our project. As part of this collective effort, I will be preparing the **course creation** sub-section of the diagram.

* This issue is a sub-issue of #75 .
* Alongside with the progress, the relevant [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) that will be covered will be shared here.
    > 1.1.3.2
    > 1.1.4 (excluding 1.1.4.4.)
* The use case diagram will be generated using the Lucichart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Step Details

Steps that will be performed:
- [x] Create course
- [x] Edit course
- [x] Delete course
- [x] Set admin

This is a list of main actions regarding the course creation process. There may be more sub-actions related to each action in the list. Additionally, this structure may be enhanced/enlarged and new base titles can be added in the future.

### Final Actions

* After each section of the course creation process are determined and combined into a diagram, it will be merged into the main use-case diagram provided in this [link](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

02.04.2022 - Saturday - 14.30

### Reviewer

@codingAku 

### Deadline for the Review

02.04.2022 - Saturday - 15.00

**Comment by xltvy** [comment]
## Info
The [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) that will be covered in this part of the use-case diagram are provided below:
* 1.1.3.2.1.1. Lectures shall be given a unique title during creation.
* 1.1.3.2.1.2. Lecturer shall state the lectures topic in a specified field for sake of categorization.
* 1.1.3.2.2.1. Lecturer shall be able to edit lecture material.
* 1.1.3.2.2.2. Lecturer shall be able to delete lectures.
* 1.1.3.2.2.3. Lecturer should be able to set a part of the lecture as hidden to be able to edit in different times.
* 1.1.4.1. Lectures shall deliver lecture material in text, images, and embedded videos.
* 1.1.4.2. Lectures shall have an Introduction where the lecturer presents the lecture in a text.
* 1.1.4.3. Lecturers shall be able to place quiz polls before a section of lecture.
* 1.1.4.4. Lectures shall have a main page where users can see introduction, events, sections, notes, annotations, and polls.
* 1.2.4.1. The system shall set the user created the lecture as the lecture’s lecturer.
* 1.2.4.2. Newly created lectures, chapters, and sections shall set as private initially as long as the lecturer states otherwise.

**Comment by xltvy** [comment]
## Update
I have finished the course creation part of the use-case diagram. This issue will be reviewed and if necessary edited/updated further.

**Comment by xltvy** [comment]
## Info
A screenshot of the related part of the use-case diagram is provided below. Arrows of **"Create Course, Delete Course, Edit Course"** are stemming directly from **Registered User** and have <includes> tag on them.

<img width="690" alt="Ekran Resmi 2022-04-03 14 26 24" src="https://user-images.githubusercontent.com/68481602/161425630-33d85309-9c8e-413b-bd54-65e86a91cba8.png">

**Comment by codingAku** [comment]
Since your work displays the discussed arguments in our meetings, I believe it is adequate. Thank you.
