### ISSUE TITLE
Frontend: Implementation Of Profile Page

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#771]
### Issue Description

The profile page is an important feature of our web application as it allows users to interact with each other and build relationships within the community. This is a generic group issue to initialize the general layout of the profile page structure according to requirements. @gokayyildiz and I are the assignees, as the outcome of our front-end group meeting on 14.12.2022.

### Step Details

Steps that will be performed:
- [x] Components of the profile page will be decided in the front-end group meeting.
- [x] After the decision of the main components the necessary CSS objects will be considered. 
- [x] A brunch will be created for the general use of these responsibilities assignees.
- [x] During the process sub-issues will be created and mentioned in this generic issue.
- [x] In case of necessity for new end points, the back-end team will be informed.
- [x] Each assignee will create a new branch rooting from the generic one for this issue during the implementation of the new functionalities.

### Final Actions

When the implementation finalizes, the generic brunch for this issue will be PR'ed to the frontend-dev branch where our production takes place as the front-end team. 

### Deadline of the Issue

26.12.2022 - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

27.12.2022 - 23.59

**Comment by Koraytkn** [comment]
I have created the initial branch that both @gokayyildiz and I will be using during the process, It can be observed [here](https://github.com/bounswe/bounswe2022group2/tree/dev-frontend-profile-page-general-development)

**Comment by gokayyildiz** [comment]
I have created the sub issue #795 and created the profile picture component to upload pictures and send it to the db. after the completion of the backend endpoint we can upload profile pictures and see the picture when we enter the profile

**Comment by Koraytkn** [comment]
I have created a [sub-issue](https://github.com/bounswe/bounswe2022group2/issues/836) related to the implementation of the user name component on the profile page.

**Comment by gokayyildiz** [comment]
Related issue #824  is created and completed

**Comment by gokayyildiz** [comment]
#837 is created to link pages

**Comment by gokayyildiz** [comment]
#844 is related to profile page development also

**Comment by Koraytkn** [comment]
I have created the component to display the Learning Spaces that the related user is participating in on the profile page. I have also provided the modularization and back-end connection. Related [issue](https://github.com/bounswe/bounswe2022group2/issues/851)

**Comment by Koraytkn** [comment]
Revision [issue](https://github.com/bounswe/bounswe2022group2/issues/856) for finalizing the structure, naming of the components, and content of the page.

**Comment by Koraytkn** [comment]
The PR including the merge of the Profile General Development branch has been merged to the dev-frontend branch. I am marking this issue as completed and closing with this comment.
