### ISSUE TITLE
Software Design: Use-Case Diagram -  View Course Page

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#78]
### Issue Description

This issue is a sub-issue of #70. View course page action will be added in user actions and detailed in the use-case diagram. 1.1.4.4.  from [Requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) will be the guide for this issue.

### Deadline of the Issue

2.04.2022 - Saturday 14.00

### Deadline for the Review

2.04.2022 - Saturday 15.00

**Comment by codingAku** [comment]
"1.1.4.4. Lectures shall have a main page where users can see introduction, events, sections, notes, annotations, and polls."
According to the requirement, view course page action has been added to the diagram on [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c&page=0_0#).

**Comment by xltvy** [comment]
I have reviewed the issue one last time after our review meeting for use case diagram and I will now close this issue since I don't see any changes to be further made. Thank you for your work!
