### ISSUE TITLE
Backend: Create Annotations Service and POST Create Annotations Endpoint for Annotation Service

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#781]
### Issue Description

After our second Milestone, the annotation service application needs to be implemented independently. For this purpose, a new create annotation endpoint needs to be implemented, which works on Annotations DB.

The request needs:
{
    "@context":"http://www.w3.org/ns/anno.jsonld",
    "type":"Annotation",
    "body": String,
    "target":{
        "source":sourceURL,
        "selector":{
            "type":"TextPositionSelector",
            "start":StartIndex,
            "end":EndIndex
        }
 
 }   }

The response will be:
{
resultMessage: success or relevant error message,
annotation: Annotation model that has been created
}

### Step Details

Steps that will be performed:
- [x] Create external service for annotations
- [x] Dockerize the new external service
- [x] Implement create annotations endpoint
- [x] Manually test it over postman and share documentation

### Final Actions

After implementation is done, deployment of new service needed.

### Deadline of the Issue

22.12.2022 - 00.00

### Reviewer

None

### Deadline for the Review

23.12.2022

**Comment by codingAku** [comment]
Please do see the first implementation of create annotation endpoint. Important Note: For the sake of simplicity, frontend URL not fixed yet, so mock URL and Learning Space and Post ID has been used. ls_id represents Learning Space ID, post_id represents Post ID for the annotation.
https://documenter.getpostman.com/view/16983185/2s8Yt1tADd#52bc3b6f-ade5-4e62-b50d-a26a94698408

**Comment by codingAku** [comment]
Related PR #785 is open. It includes dockerization and implementation of annotation service with create annotation endpoint.

**Comment by mbatuhancelik** [comment]
I checked the PR and merged it, closing this for now.
