### ISSUE TITLE
Frontend: Home Page Popular Learning Spaces Backend Connection

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#792]
### Issue Description

As the development of the learning space preview component is completed, unit tested, and successfully passed the unit tests, now we can connect the components in the home page with the related endpoint from our REST API.

The most popular four learning spaces in our application depending on the participant amount will be rendered in and accessible from the home page. This part will be consisted of learning space preview boxes that correctly displaying fetched results from our API. I will be implementing the outlined parts.

### Step Details

Steps that will be performed:
- [x] Create a function to handle related API request
- [x] Store the results in an array
- [x] Map results to the learning space preview boxes
- [x] Render the boxes in the related part of the home page

### Final Actions

I will create a separate branch from our frontend development branch to continue with the implementation. After everything is done and every change is committed, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

22.12.2022 - Thursday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

23.12.2022 - Friday - 23.59

**Comment by xltvy** [comment]
## Update

I have established backend connection between the popular learning spaces part of the home page and the REST API. Any implementation detail can be tracked from #801 . Merging it will close this issue.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your contributions! I have tested all the changes you have made and everything works very well!

Since related pull request #801 has now been merged, I will close this issue.
