### ISSUE TITLE
Frontend: Creating Profile Picture Component

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#795]
### Issue Description

Addition of the component which is related to adding a profile picture on the profile.

### Step Details

Steps that will be performed:
- [x] Create the profile picture component
- [x] Insert into the profile page

### Deadline of the Issue

23.12.2022 - Friday - 19.59

### Reviewer

Altay Acar

### Deadline for the Review

23.12.2022 - Saturday - 23.59

**Comment by gokayyildiz** [comment]
Created the component and putted in profile page.
<img width="1440" alt="Ekran Resmi 2022-12-22 20 59 29" src="https://user-images.githubusercontent.com/42673110/209199046-13ff3973-0606-496e-bc6b-a64b39cdcc30.png">
<img width="1440" alt="Ekran Resmi 2022-12-22 20 59 22" src="https://user-images.githubusercontent.com/42673110/209199068-5034b508-0da2-40e2-a62e-c78ef35ef002.png">

**Comment by Koraytkn** [comment]
Related PR has been approved and merged thus I am closing this issue after marking it as complete.
