### ISSUE TITLE
Frontend: Create Comment Component for Learning Space Posts

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#798]
### Issue Description

The foundation of our application will be learning spaces with posts, comments, contributors, and events, all of which have functional elements in the form of various buttons. A user must utilize the components on the page in order to use any learning space's features. In accordance with the user experience slides from the lecture, we have agreed as a group to proceed with the implementation of a comment component to enable users to quickly access the capabilities they like under the posts. This decision was made at our general meeting.

After our last meeting for the frontend team, I was given the specified duty above. I will design the comment component for the learning spaces page posts and fill in all the fields with the relevant elements.

### Step Details

Steps that will be performed:
- [x] Give a basic layout for the elements of the Learning space page comments
- [x] Organize the elements so that they comply with the general page layout
- [x] Link each element to its corresponding field on the learning space page
- [x] Finalize all work related to the necessary elements

### Final Actions

To proceed with the implementation, I will create a separate branch from our frontend development branch. I will be making a pull request in accordance with the changes made when everything is finished and committed, and I will connect that pull request to this issue. The modifications will be active on our development branch after acceptance and merging, at which point this issue will be closed.

### Deadline of the Issue

22.12.2022 - Thursday - 20.59

### Reviewer

Altay Acar

### Deadline for the Review

22.12.2022 - Thursday - 23.59

**Comment by surmelienes1** [comment]
## Update

All the related work about this issue can easily be tracked from the pull request #799

**Comment by xltvy** [comment]
Thank you for your work. Since #799 is merged, closing this issue now.
