### ISSUE TITLE
Software Design: Use Case Diagram - Note Actions

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#80]
### Issue Description

- This is a sub issue of the issue #69.
- The use case diagram for creating and viewing notes will be created under this issue.
- The [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) to be covered by these use cases will be shared here.
- Diagram in [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Step Details

Steps that will be performed related to the following parts:
* Creating Notes
* Editing Notes
* Viewing Notes

- [x] Checking mock-ups.
- [x] Checking requirements related to notes.
- [x] Complete the diagram on related topics on [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Final Actions

The Use Case Diagram to be generated here must be combined with the use case diagrams of the other team members at #69.

### Deadline of the Issue

02.04.2022 - Saturday - 14.00

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

02.04.2022 - Saturday - 15.00

**Comment by bahricanyesil** [comment]
## Info
The [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) that will be covered in this part of the use-case diagram are provided below:
### Viewing Notes
* 1.1.2.12.2.1. Users shall view their notes taken from the courses in the lecture notes section of their profile pages.
* 1.1.2.12.2.2. Users shall view the most recent time of edit for each lecture note.

**Comment by bahricanyesil** [comment]
## Info
The mockup sections for the related part are the following ones:
* Viewing Notes from the Profile Screen

![](https://user-images.githubusercontent.com/68481602/159769997-6ba3d001-e643-41f4-866a-514a10b30ce1.png)

* Viewing Notes from the Lecture Screen

![](https://user-images.githubusercontent.com/68481602/159770134-d3b455ca-2807-4e12-81a3-9da0e37ebf1a.png)

* Creating & Editing Notes

![](https://user-images.githubusercontent.com/68481602/159770159-f8fd4c7a-d05e-4520-9cec-7b7dccc533c0.png)

**Comment by bahricanyesil** [comment]
I have completed the corresponding part of the diagram. You can see it directly [here](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c&page=0_0#).

**Comment by bahricanyesil** [comment]
It is ready for review by @ahmet633.

**Comment by ezgy** [comment]
According to the project description:

> Learners will be able to create notes related to what they are learning. They will be able to
connect notes, annotate and **tag** them

I couldn't find tagging notes in the requirements, but since it is in the project description it should be added as an action in the use case diagram.

**Comment by bahricanyesil** [comment]
I will add it to the requirements and diagram. Thank you for pointing that out @ezgy.

**Comment by bahricanyesil** [comment]
> According to the project description:
> 
> > Learners will be able to create notes related to what they are learning. They will be able to
> > connect notes, annotate and **tag** them
> 
> I couldn't find tagging notes in the requirements, but since it is in the project description it should be added as an action in the use case diagram.

Here's the requirement I newly added:
1.1.3.2.4.5. Users shall connect, annotate and tag notes.

**Comment by bahricanyesil** [comment]
We have reviewed these parts in our meeting(03.04.2022) about merging use cases. There is nothing to add/update except the above one Ezgi mentioned.

**Comment by bahricanyesil** [comment]
I updated the use-case diagram with the newly added requirement. You can access the updated diagram with the same link.
I am also attaching the updated screenshot here.

<img width="644" alt="Screen Shot 2022-04-03 at 18 46 26" src="https://user-images.githubusercontent.com/60237280/161436172-6147513f-c021-450d-b4b2-f62e1ac95c3d.png">

**Comment by bahricanyesil** [comment]
Since this part of the diagram is both reviewed by all team members in our meeting(03.04.2022) about merging use cases and also by @ezgy, I'm closing the issue.
