### ISSUE TITLE
Frontend: My Learning Spaces Page

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#802]
### Issue Description

Our home page features a collection of signed in user's own learning spaces. Each user can browse through the learning spaces that they are participating in from the home page's related part. That part also features a view all button. 

The view all button needs to redirect the user where they can browse through their learning spaces independently. Because the main functionality of the home page is not browsing a user's own learning spaces, instead it is more of a dashboard.

Thus, I will be implementing the my learning spaces page of our web application. It can be accessed from the home page's related view all button.

### Step Details

Steps that will be performed:
- [x] Create a general layout for the my learning spaces page.
- [x] Add NavBar component
- [x] Add Footer component
- [x] Handle url redirection via App.js

### Final Actions

I will create a separate branch from our frontend development branch to continue with the implementation. After everything is done and every change is committed, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

22.12.2022 - Thursday - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

23.12.2022 - Friday - 23.59

**Comment by xltvy** [comment]
## Update

I have implemented the my learning spaces page. All the implementation can be tracked from #805 , merging it will close this issue.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your contributions! I have tested all the changes you have made and everything works very well!

Since related pull request #805 has now been merged, I will close this issue.
