### ISSUE TITLE
Frontend: Unit Tests for My Learning Spaces Page

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#806]
### Issue Description

Since the implementation of the my learning spaces page is done and ready, before completing its implementation and making it ready for the deployment, we need to test it via unit tests. 

Thus, I will be adding unit tests for the MyLearningSpacesPage component. The MyLearningSpacesPage component makes a GET request to the backend to retrieve a list of learning spaces and displays them in a series of LearningSpaceDetailBox components. It also includes a NavBar and Footer component. It is important to have unit tests in place to ensure that the component is working as expected and that any changes made to the component in the future do not break its functionality.

### Step Details

Steps that will be performed:
- [x] Test the general render of the page
- [x] Test the render of sub-components of the page
- [x] Test the rendering of the NavBar, Footer, and LearningSpaceDetailBox components
- [x] Test the correct display of the learning spaces and the user's username in the page header
- [x] Test the useEffect API handler

### Final Actions

I will create a separate branch from our frontend development branch to continue with the implementation. After everything is done and every change is committed, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

22.12.2022 - Thursday - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

23.12.2022 - Friday - 23.59

**Comment by xltvy** [comment]
## Update

I have implemented and performed the unit tests for the my learning spaces page. It has passed all the six unit tests I have implemented. The results can be seen below:
<img width="516" alt="Ekran Resmi 2022-12-22 22 44 43" src="https://user-images.githubusercontent.com/68481602/209215611-e1f841f1-90bc-4388-b68e-3aba53499a44.png">
<img width="491" alt="Ekran Resmi 2022-12-22 22 44 51" src="https://user-images.githubusercontent.com/68481602/209215621-24861937-0b07-4140-9d0e-2650f7360801.png">

Any implementation detail can be tracked from #807 , merging it will close this issue.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your contributions! I have run all the tests you wrote and everything works very well!

Since related pull request #807 has now been merged, I will close this issue.
