### ISSUE TITLE
Frontend: Popular Learning Spaces Page

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#808]
### Issue Description

Our home page features a collection of popular learning spaces. Each user can browse through the learning spaces that are displayed according to their popularity, which is defined by the number of participants of that learning space, from the home page's related part. That part also features a view all button.

The view all button needs to redirect the user where they can browse through popular learning spaces independently. Because the main functionality of the home page is not browsing popular learning spaces, instead it is more of a dashboard.

Thus, I will be implementing the popular spaces page of our web application. It can be accessed from the home page's related view all button.

### Step Details

Steps that will be performed:
- [x] Create a general layout for the my learning spaces page.
- [x] Add NavBar component
- [x] Add Footer component
- [x] Handle url redirection via App.js
- [x] Handle API call

### Final Actions

I will create a separate branch from our frontend development branch to continue with the implementation. After everything is done and every change is committed, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

22.12.2022 - Thursday - 23.59

### Reviewer

Koray Tekin

### Deadline for the Review

23.12.2022 - Friday - 23.59

**Comment by xltvy** [comment]
## Update

I have implemented the popular learning spaces page. Any implementation detail can be tracked from #817, merging it will close this issue.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your contributions! I have tested all the changes you have made and everything works very well!

Since related pull request #817 has now been merged, I will close this issue.
