### ISSUE TITLE
Frontend: Implementation of About Page

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#814]
### Issue Description

I will be implementing the about page of our web application as the following stage of our web application development, since we mentioned in our last frontend team meeting. The components that will be on the about page as well as its basic design have been discussed. The parts that we have been selected are listed below:

The main part including information about our application and the developers.
The side part making it easier for the application users to navigate between given information.

### Step Details

Steps that will be performed:
- [x] Create a generic about page design that adheres to our web application's aesthetic standards
- [x] Implement the main part including information about our application and the developers.
- [x] Implement the side part making it easier for the application users to navigate between given information.
- [x] Create the about page's in- and out-going navigation
- [x] Include navigation bar and footer to let user easily navigate

### Final Actions

To proceed with the implementation, I will make a separate branch from our frontend development branch. I will be making a pull request in accordance with the changes made when everything is finished and committed, and I will connect that pull request to this issue. The modifications will be active on our development branch after acceptance and merging, at which point this issue will be closed.

### Deadline of the Issue

23.12.2022 - Friday - 11.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

23.12.2022 - Friday - 23.59

**Comment by surmelienes1** [comment]
## Update

All the related work about this issue can easily be tracked from the pull request https://github.com/bounswe/bounswe2022group2/pull/815

You could see a screenshot from the about page below:

<img width="1728" alt="Screenshot 2022-12-23 at 11 26 44" src="https://user-images.githubusercontent.com/74325266/209300965-d2d1ed30-4c64-4866-b01d-52fbd3de3f53.png">

**Comment by xltvy** [comment]
Since #815 merged, closing this issue.
