### ISSUE TITLE
Frontend: Unit Tests for Popular Learning Spaces Page

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#819]
### Issue Description

The implementation of the popular learning spaces page is done, yet not completed. Before getting it ready for deployment, we need to perform unit tests on it. This issue is to write unit tests for the `PopularLearningSpacesPage` component in the `PopularLearningSpacesPage.js` file.

The `PopularLearningSpacesPage` component displays a list of the most popular learning spaces. It makes a GET request to the backend server to retrieve the list of learning spaces and displays them using the `LearningSpaceDetailBox` component. The page also includes a navigation bar and a footer.

Unit tests should cover the following scenarios:

The component correctly displays the list of learning spaces retrieved from the backend server.
The component correctly displays the navigation bar and footer.
The unit tests should be written using a testing library such as Jest and React Testing Library.

### Step Details

Steps that will be performed:
- [x] Test the general render of the page.
- [x] Test the snapshot of the page.
- [x] Test the render of sub-components of the page.
- [x] Test the Footer component's render
- [x] Test the NavBar component's render

### Final Actions

I will create a separate branch from our frontend development branch to continue with the implementation. After everything is done and every change is committed, I will be creating a pull request accordingly and link that pull request to this issue. Upon approval and merging, the changes will be live on our development branch and this issue will be closed.

### Deadline of the Issue

23.12.2022 - Friday - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

24.12.2022 - Saturday - 23.59

**Comment by xltvy** [comment]
## Update

I have implemented unit tests suite for the `PopularLearningSpacesPage` and the component has passed all the five tests. Below are the results:
<img width="512" alt="Ekran Resmi 2022-12-23 19 19 58" src="https://user-images.githubusercontent.com/68481602/209366919-69510094-f26e-49fd-946a-62843486af53.png">

**Comment by xltvy** [comment]
## Update

I have implemented the unit tests suite for `PopularLearningSpacesPage` component. Any implementation detail can be tracked from #839, merging it will close this issue.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @xltvy for your contributions! I have run all the tests you wrote and everything works very well!

Since related pull request #839 has now been merged, I will close this issue.
