### ISSUE TITLE
Software Design: Use Case Diagram - Events

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#82]
### Issue Description

* This issue is sub-issue of #69 .
* I will be working on **Events** part of the Use Case Diagram. 
* Corresponding requirements will be added under this issue in order to simplify the cross check and review process.
* Mock-up and scenarios will be considered during this work.
* Diagram can be observed through [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Step Details

Steps that will be performed:
- [x] Checking the requirements and adding corresponding parts of it.
- [x] Checking the scenarios.
- [x] Creating the corresponding diagram.

### Final Actions

After all work is done, I will provide the final materials. Diagram that I will be create will be combined with other related parts under the #69.

### Deadline of the Issue

02.04.2022 - Saturday - 14.00

### Reviewer

Ahmet Yiğit Özdoğan

### Deadline for the Review

02.04.2022 - Saturday - 15.00

**Comment by onurkomurcu** [comment]
Following requirements are implemented to Use Case Diagram within corresponding section.

* 1.1.2.7. Users shall have a "My Events" section on their profile pages.
* 1.1.2.8. Users who are qualified as "Lecturer" will see the events they have organized on their "My Events" section with the headline: "You are the organizer!".
* 1.1.2.9. Users who are qualified as "Learners" will see the events they are participating in on their "My Events" section with the headline: "You are participating!".
* 1.1.3.2.5.2. Created events shall include currently enrolled learners.
* 1.1.3.2.5.3. Created events are only specified for various courses, which means some courses may not have an event-creating ability.
* 1.1.3.2.5.4. Created events have a specific date, duration, and limit for the number of participants.
* 1.1.3.2.5.5. Lecturers can give a brief description of the topics of discussion for the event.
* 1.1.3.2.5.6. Lecturers are able to cancel events that they have created.
* 1.1.3.2.5.7. Created events will be visible on the course info page along with the date, duration, and the number of participants.
* 1.1.3.2.5.8. Enrolled students will be able to notify that they will be joining community events with a button click.
* 1.1.3.2.5.9. The number of students who will join the event will be visible to both lecturers and students.

**Comment by onurkomurcu** [comment]
Following work can be observed in [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c). 
![Ekran Resmi 2022-04-02 13 55 00](https://user-images.githubusercontent.com/92719802/161380040-dbd14a76-fc67-45ee-a1b0-9e0ad307d402.png)

**Comment by onurkomurcu** [comment]
I have finished my worked. It is ready to be review by @ahmet633. All suggestions and questions are welcomed.

**Comment by bahricanyesil** [comment]
Thank you for your work @onurkomurcu. I reviewed the part of the diagram you created.

Is there a way to edit the created event? If so, I think it will be better to add that action to the diagram.

**Comment by bahricanyesil** [comment]
We can talk about this via our communication channels if you want to make the required changes before our next meeting and close the issue before the deadlines.

**Comment by onurkomurcu** [comment]
According to our meeting 5.2, there is no need to provide editing feature to events. So, for now, this issue can be closed. If you have any further suggestion, you can reopen this issue.

**Comment by egemenatikk** [comment]
I added Join Events section to Event part of Use Case Diagram with an "includes" relation.
