### ISSUE TITLE
Revision of Registered Lecturer Scenario

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#83]
### Issue Description

We received some feedbacks about the [registered lecturer scenario](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Taşkıran) in the PS section. I will be revising them accordingly.

### Step Details

Here are the feedbacks and the points that should be revised:

- [x] Remove the goals that are not included in the scenario and mockup.
- [x] Edit the goals to be more concise and summarized.
- [x] Make all acceptance criteria requirements numbered instead of bulleted.

### Final Actions

After the revisions are completed, the results of the issue will be reviewed by @surmelienes1 to ensure that there is no missing point.

### Deadline of the Issue

02.04.2022 - Saturday - 15:00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

02.04.2022 - Saturday - 20:00

**Comment by bahricanyesil** [comment]
I have revised the mentioned steps in the description. All of the items are revised and corresponding wiki page is updated. You can see the updated scenario [here](https://github.com/bounswe/bounswe2022group2/wiki/Registered-Lecturer-Scenario,-Hasan-Taşkıran).

**Comment by bahricanyesil** [comment]
Since the required actions are performed, the issue is now ready for review of @surmelienes1.

**Comment by surmelienes1** [comment]
It looks very good and complete, great job! Thank you [Bahrican](https://github.com/bounswe/bounswe2022group2/wiki/Bahrican-Yesil) for your valuable contributions.

I will now close this issue since I don't see any changes to be further made. If you have additional questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
