### ISSUE TITLE
Software Design: Use Case Diagram - Annotations

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#84]
### Issue Description

* This issue is sub-issue of #69 .
* I will be working on **Annotations** part of the Use Case Diagram. 
* Corresponding requirements will be added under this issue in order to simplify the cross check and review process.
* Mock-up and scenarios will be considered during this work.
* Diagram can be observed through [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Step Details

Steps that will be performed:
- [x] Checking the requirements and adding corresponding parts of it.
- [x] Checking the scenarios.
- [x] Creating the corresponding diagram.

### Deadline of the Issue

02.04.2022 - Saturday - 14.00

### Reviewer

Ahmet Yiğit Özdoğan

### Deadline for the Review

02.04.2022 - Saturday - 15.00

**Comment by hasancan-code** [comment]
## INFO
The [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) that will be covered in this part of the use-case diagram are provided below:
### 1.1.2.12.3. Annotations
* 1.1.2.12.3.1. Users shall access the annotations they have added for course material from the annotations section of their profile pages.
* 1.1.2.12.3.2. Users shall be able to browse their annotations by category, by course, by history, and by upvotes they have received.
* 1.1.2.12.3.3. Users shall be able to see how many annotations they have and from how many categories, from how many courses and the total number of upvotes they have received.

### 1.2.8. 🗒️ Annotations
* 1.2.8.1. Users shall be able to create annotations.

* 1.2.8.3. Owner of the annotations shall be able to set annotations as public or private.
* 1.2.8.4. Created annotations shall be reachable from both profile page and relevant target resource(s).
* 1.2.8.8. Annotations with public visibility should be listed on that annotation's creator's profile page.

**Comment by hasancan-code** [comment]
I have completed the corresponding part. You can check from the [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c&page=0_0#)

There is a screenshot of the work.
![image](https://user-images.githubusercontent.com/74256913/161381685-b2ed4439-6a2e-493a-83b6-eca2d20a105a.png)

**Comment by bahricanyesil** [comment]
Thank you for your work @hasancan-code. I reviewed the part you did. Here are my review results:

1. We can merge public/private setting while editing an annotation as a single box with a text like "set privacy of the annotation"
2. You can write something for "create annotations" part. There "may" be the user imputs, contents and etc that will be entered while creating an annotation.

**Comment by hasancan-code** [comment]
Thanks for the review @bahricanyesil. I revised the work according to the review and I added extra parts to "edit annotation" block about editing an annotation and deleting it.  You can check from the [Lucidhart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?page=0_0&invitationId=inv_acc885f2-fa4a-491c-888a-b14b05e8aa09#). I will provide the screenshot of the work below for just in case.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/74256913/161595046-3e340046-ee94-4fa8-be2a-2a70905233ec.png">

**Comment by bahricanyesil** [comment]
Thank you for the changes @hasancan-code! I guess you can close the issue since we also went over the diagram as the whole team in our meeting on Saturday (02.04.2022).
