### ISSUE TITLE
Frontend: Make profile links unique and accessible through ls's

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#844]
### Issue Description

Make profiles accesible to other users through unique url's, so do this conversion and connect the usernames to the profile's via links from learning spaces

### Step Details

Steps that will be performed:
- [x] make unique url structure
- [x] update navbar to show current users profile
- [x] update LS component to link to the profiles

### Final Actions

Control the links and connections through other pages to the profile page

### Deadline of the Issue

25.12.2022 - Sunday - 12.59

### Reviewer

Koray Tekin

### Deadline for the Review

25.12.2022 - Sunday - 23.59

**Comment by gokayyildiz** [comment]
Navbar and Participants components are updated to link the users to their profile page

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! I have tested all the changes you have made and everything works very well!

Since related pull request #850 has now been merged, I will close this issue.
