### ISSUE TITLE
Software Design: Use Case Diagram - View Course Content

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#85]
### Issue Description

* This issue is sub-issue of #69 .
* I will be working on **View Course Content** part of the Use Case Diagram. 
* Corresponding requirements will be added under this issue in order to simplify the cross check and review process.
* Mock-up and scenarios will be considered during this work.
* Diagram can be observed through [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Step Details

Steps that I will be performed:
- [x] Checking the requirements and adding corresponding parts of it.
- [x] Checking the scenarios.
- [x] Creating the corresponding diagram.

### Final Actions

After all work is done, I will provide the final materials. Diagram that I will be create will be combined with other related parts under the #69.

### Deadline of the Issue

02.04.2022 - Saturday - 14.00

### Reviewer

Ahmet Yiğit Özdoğan

### Deadline for the Review

02.04.2022 - Saturday - 15.00

**Comment by onurkomurcu** [comment]
Following requirements need to be found in the use case diagram:
* 1.1.3.2.3.1. Users shall see the content within sections as lecturer intended.
* 1.1.3.2.3.2. Users shall navigate in lecture material.
* 1.1.3.2.3.3. Users shall see which parts of the lecture they completed.
* 1.1.3.2.3.4. Users shall know type of the poll they are participating in beforehand.
* 1.1.3.2.3.5. Users shall receive confirmation of their expertise on the topic upon completion of a lecture.
* 1.1.3.2.3.6. Users shall be able to rate lectures.
* 1.1.3.2.3.7. Users may need to complete some polls for unlocking some sections of the lecture.

**Comment by onurkomurcu** [comment]
The work I done for the **View Course Content** can be seen from following screenshot or from [Lucidchart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c) directly.
![Ekran Resmi 2022-04-02 14 54 41](https://user-images.githubusercontent.com/92719802/161381980-91a4e486-53ec-4e8a-b747-7c0211b73a0b.png)

**Comment by onurkomurcu** [comment]
This issue is ready to be reviewed by @ahmet633.

**Comment by bahricanyesil** [comment]
Thank you for your work @onurkomurcu. I guess we can merge two items related to course sections as "View completed and all course sections."

**Comment by onurkomurcu** [comment]
I will merge them as **"View completed and uncompleted sections"**. By this way, we don't repeat "completed sections" with "all course sections" term because it also comprise completed sections. Thank you for your participating @bahricanyesil .

**Comment by onurkomurcu** [comment]
According to our last meeting, there is no need to revise for this section of the use case. So, for now this issue will be closed.
