### ISSUE TITLE
Software Design: Class Diagram

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#86]
### Issue Description

As discussed in the extra meeting on Saturday, we will complete class diagrams on [Lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/edit?invitationId=inv_26b91b21-bb1b-47cd-96e4-a1a28fc9b0ce). Everyone has various tasks on the diagram. 
According to meeting notes on Discord channel, tasks are distributed like below:
Chat class - ~@ahmet633~ @mbatuhancelik #105  
Message class - @codingAku #93 
Event class - @egemenatikk 
Tag Class - @ezgy #98 
Note Class - @ezgy  #96 
App Info Class - @hasancan-code 
User Class - @bahricanyesil #88 
Course Class - @hasancan-code & @mbatuhancelik  #91 
Token Class - @bahricanyesil #89 
Enrolled Class - @surmelienes1 & @onurkomurcu #100 & #99 
Profile Class - @codingAku #93 
Participant Class - @egemenatikk 
Annotation Class - @xltvy - [Corresponding Issue](https://github.com/bounswe/bounswe2022group2/issues/87)
Search Class - @xltvy - [Corresponding Issue](https://github.com/bounswe/bounswe2022group2/issues/103)

### Final Actions

After classes are created connections between related classes will be finalized in another meeting on Monday.

### Responsible People

- [X] Bahrican Yesil
- [X] Egemen Atik
- [X] Altay Acar
- [X] Ezgi Aysel Batı
- [X] Muhammed Enes Sürmeli
- [X] Onur Kömürcü
- [X] Mehmet Batuhan Çelik
- [X] Hasan Can Erol
- [ ] Ahmet Yiğit Özdoğan
- [X] Ecenur Sezer

### Deadline of the Issue

4.04.2022 - Monday 23.59

### Deadline for the Review

5.04.2022 - Tuesday 10.00

### Final To-Dos

- [ ] Every responsible shared an info about the sections/parts s/he will perform.
- [X] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [X] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by bahricanyesil** [comment]
@codingAku I guess it will be better to enable access to the document with a public link instead of email verification. With the help of a public link, all team members, TA, and teachers can also access the document.

**Comment by codingAku** [comment]
@bahricanyesil  Can you check now if it's available to access, please?

**Comment by bahricanyesil** [comment]
> @bahricanyesil Can you check now if it's available to access, please?

Yes, it is. Thank you.

**Comment by bahricanyesil** [comment]
@codingAku, we as the team members also need "edit access". Can you provide that access too?

**Comment by egemenatikk** [comment]
I completed Event and Participants parts of the class diagram. Here are the related issues:

User: #95  
Token: #97

**Comment by xltvy** [comment]
I completed Annotation part of the class diagram. Here is the related issue:

* User: #87

**Comment by surmelienes1** [comment]
I completed the Enrolled Actions part of the class diagram. Here is the related issue:

* Enrolled Actions: #100

**Comment by ezgy** [comment]
I completed the Note and Tag classes of the diagram. Here are the related issues:
* Note: #96  
* Tag: #98

**Comment by codingAku** [comment]
I completed Profile and Message classes. Related issue:
* #93

**Comment by mbatuhancelik** [comment]
Since we cannot reach out to @ahmet633, I took action for creating class diagram under #105 as discussed in class diagrams meeting.

**Comment by codingAku** [comment]
Class diagrams are completed.
