### ISSUE TITLE
Software Design: Class Diagram - Annotation

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#87]
### Issue Description

As the next part of the software design process, we will provide a class diagram for our project moving from the use case diagram phase. Class diagram will be completed with a collective effort and I will be preparing the **annotation** sub-section of the diagram.
* This issue is a sub-issue of #86 .
* **Annotation** class will be formed, using this section of the use case diagram as basis.
<img width="560" alt="Ekran Resmi 2022-04-03 22 24 12" src="https://user-images.githubusercontent.com/68481602/161444571-8c1fb952-93ec-4932-8521-deb2c928eaef.png">

* The class diagram will be generated using the Lucichart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .

### Step Details

Steps that will be performed:
- [x] ID system
- [x] Upvote system
- [x] Ownership
- [x] Content

This is a list of features that the **Annotation** class has. This structure may be enhanced/enlarged and new base titles can be added in the future, as **Annotation** class may have more features.

### Final Actions

* After each part of the Annotation class is determined and combined into a diagram, it will be merged into the main class diagram provided in this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

04.04.2022 - Monday - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

05.04.2022 - Tuesday - 10.00

**Comment by xltvy** [comment]
## Info:
I have created the initial form of the **Annotation** class as part of the class diagram of our project.

Here is a screenshot taken directly from our class diagram, which can be viewed from this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#):

<img width="368" alt="Ekran Resmi 2022-04-04 22 49 53" src="https://user-images.githubusercontent.com/68481602/161621289-a9205cf0-7f86-4fdf-a217-61b28eb385d5.png">

This issue will be reviewed and if necessary edited/updated further.

**Comment by xltvy** [comment]
## Attributes

I defined the class attributes as follows:

|Attribute Name|Type|Description|
|:-----|:--------:|:------|
|annotation_id|int|ID of the annotation|
|owner_id|UID|ID of the user that created this annotation|
|course_id|int|ID of the course that this annotation belongs to|
|category_id|int|ID of the category that this annotation belongs to|
|chapter_number|int|number of the chapter that this annotation belongs to|
|page_number|int|number of the page that this annotation belongs to|
|pos_x|float|X coordinate of location of the annotation on a page|
|pos_y|float|Y coordinate of location of the annotation on a page|
|created_at|Date|The date this annotation is created|
|updated_at|Date|The date this annotation is updated latest|
|deleted_at|Date|The date this annotation is deleted|
|upvote|int|Number of upvotes this annotation received|
|content|string|Content of the annotation as a text|

**Comment by xltvy** [comment]
## Methods

I defined the class methods as follows:

|Method Name|Parameters|Return Type|
|:-----|:--------|:------:|
|createAnnotation|annotation_id: int, owner_id: UID, course_id: int, category_id: int, chapter_number: int, page_number: int, pos_x: float, pos_y: float, created_at: Date, content: string|void|
|editAnnotation|new_content: string, edit_date: Date|void|
|deleteAnnotation|-|void|
|getUserId|-|UID|
|getCategory|-|int|
|getCourse|-|int|
|getDate|-|Date|
|getUpvote|-|int|
|upvote|-|void|
|downvote|-|void|

**Comment by surmelienes1** [comment]
It looks very good and complete for now, great job! Thank you [Altay](https://github.com/bounswe/bounswe2022group2/wiki/Altay-Acar) for your valuable contributions. After we hold our meeting to review the class diagram as a whole, we can make an additional integrity check according to the rest of the work from other team members.

I will now close this issue since I don't see any changes to be further made. If you have additional questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
