### ISSUE TITLE
Software Design: Class Diagram - User

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#88]
### Issue Description

As the next part of the software design process, we will provide a class diagram for our project moving from the use case diagram phase. Class diagram will be completed with a collective effort and I will be preparing the **user** sub-section of the diagram.
* This issue is a sub-issue of #86 .
* **User** class will be formed, using the following sections of the use case diagram as basis.
Sign-Up
![Screen Shot 2022-04-04 at 12 07 07](https://user-images.githubusercontent.com/60237280/161511575-3a149e79-c847-45b5-b01f-18ac13a42be5.png)
Login
![Screen Shot 2022-04-04 at 13 03 15](https://user-images.githubusercontent.com/60237280/161521721-dde5d707-1a57-436c-899c-25f376c63ff1.png)

* The class diagram will be generated using the Lucichart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram
- [x] Define the attributes of the user class with name, type and description columns.
- [x] Define the methods of the user class withe name, parameters, return type and requires auth columns.
- [x] Check the possible inheritance, association, aggregation, composition relationships.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After each part of the User class is determined and combined into a diagram, it will be merged into the main class diagram provided in this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

04.04.2022 - Monday - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

05.04.2022 - Tuesday - 10.00

**Comment by bahricanyesil** [comment]
I defined the class attributes as follows:

|Attribute Name|Type|Description|
|:-----|:--------:|:------|
|user_id|UID|Id of the user|
|username|string|Unique username of the user|
|email|string|Unique email of the user|
|password|string|Hashed password of the user|
|is_email_confirmed|bool|Whether the user is completed the email verification step|
|is_active|bool|Whether the user deleted the account and anonymized|
|language_code|string|The code of the language user is selected (if not selected, locale language code)|
|device_token|string|Token of the device which is user is actively using (will be used while sending notifications)|
|created_at|Date|The date user signed up|
|updated_at|Date|The last date information under this class is updated|
|deleted_at|Date|The date user deleted the account|

**Comment by bahricanyesil** [comment]
I defined the class methods as follows:

|Method Name|Parameters|Return Type|
|:-----|:--------|:------|
|login|username: string, password: string|access_token: string, refresh_token: string, user: User|
|register|username: string, email: string, password: string, device_token: string, language_code: string|verification_token: string|
|verify_email|verification_code: string, verification_code: string|access_token: string, refresh_token: string, user: User|
|send_verification_code|email: string|verification_token: string|
|forgot_password|password: string|is_successful: bool|
|change_password|old_password: s trying, new_password: string|is_successful: bool|
|delete_user|-|is_successful: bool|
|get_user|user_id: string|user: User|

**Comment by bahricanyesil** [comment]
Possible relationships:

- Can have a composition relationship with Token class that will be created with issue #89 and also most of the other classes like Enrollment, Participance, Profile and so on. All other classes that have composition relationship with the users should be connected to the User class by the creator of those classes. 
- Can have an inheritance relationship with Admin and other similar classes.

**Comment by bahricanyesil** [comment]
I completed the user part of the class diagram. You can access it via our [class diagram project link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/edit?invitationId=inv_26b91b21-bb1b-47cd-96e4-a1a28fc9b0ce). Here's the screenshot of the corresponding part:

![Screen Shot 2022-04-04 at 14 27 21](https://user-images.githubusercontent.com/60237280/161534596-3ab4a526-a81e-4d11-ab42-58546e0106cf.png)

**Comment by bahricanyesil** [comment]
I will add methods for following actions:

- Hash password (private)
- Change notification preference
- Change username
- Check username existence

I will also add an attribute related to the notification preference of the user.

**Comment by bahricanyesil** [comment]
I added the methods and attributes I mentioned above to the diagram. You can view the updated diagram via the link above. Here's the screenshot of the updated version:

![Screen Shot 2022-04-04 at 15 41 14](https://user-images.githubusercontent.com/60237280/161545718-9051f582-cbfd-408d-8a0d-4c3c2830402a.png)

**Comment by bahricanyesil** [comment]
The user part of the class diagram is completed, the associated diagram link and ss are given above. Now, it is ready to be reviewed by @xltvy.

**Comment by xltvy** [comment]
Thank you for your very detailed and comprehensive work. I think it is nearly perfect. I think there are just a few things that can be missing. Here I listed them:
* I think we may need an attribute for admin users. For example a boolean, called **isAdmin** to distinguish an admin user with a regular user.
* I think it is more of a design choice but I came up with the question that if a User class needs lists of annotations, taken courses, notes etc. for access to a specific user's notes, annotations, taken courses etc. or not. If so, then we may add those lists to the attributes of the class.

**Comment by bahricanyesil** [comment]
> Thank you for your very detailed and comprehensive work. I think it is nearly perfect. I think there are just a few things that can be missing. Here I listed them:
> 
> * I think we may need an attribute for admin users. For example a boolean, called **isAdmin** to distinguish an admin user with a regular user.
> * I think it is more of a design choice but I came up with the question that if a User class needs lists of annotations, taken courses, notes etc. for access to a specific user's notes, annotations, taken courses etc. or not. If so, then we may add those lists to the attributes of the class.

Thank you for the review @xltvy. 

1- Will there be admins of the system? If you are indicating the admin of the courses, it should be under the "enrollment" class. If there will be admins of the system, you're right but can you indicate the corresponding requirement/use-case diagram if that's the case.
2- I think, we will not directly store them under the user class since it will be overwhelming while creating/updating/deleting synchronously from multiple tables. Instead, we will fetch a user's notes and etc. by scanning the notes table with the id of the user since each note should have a user_id attribute. So, we don't need additional attributes for those purposes, we will use the methods of those classes.

**Comment by xltvy** [comment]
Ok, both of them makes sense and I think now we have a separate **Lecture Admin** class. So, first one resolved by itself. For the second one, your solution also makes sense. I just have one question about it: Where do we store tables for notes, annotations etc?

**Comment by bahricanyesil** [comment]
> Ok, both of them makes sense and I think now we have a separate **Lecture Admin** class. So, first one resolved by itself. For the second one, your solution also makes sense. I just have one question about it: Where do we store tables for notes, annotations etc?

Thank you for your response. Yes, we have a separate class for it.

For the second one:
We have the 
* "Note" class issue [here](https://github.com/bounswe/bounswe2022group2/issues/96)
* "Annotation" class issue [here](https://github.com/bounswe/bounswe2022group2/issues/87)

I think there will be separate tables in the db design for the classes we created here (one-to-one relation).

**Comment by xltvy** [comment]
Ok, thank you. Closing the issue.
