### ISSUE TITLE
Software Design: Class Diagram - Token

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#89]
### Issue Description

As the next part of the software design process, we will provide a class diagram for our project moving from the use case diagram phase. Class diagram will be completed with a collective effort and I will be preparing the **token** sub-section of the diagram.
* This issue is a sub-issue of #86 .
* **Token** class will be formed, using the following sections of the use case diagram as basis.
Sign-Up
![Screen Shot 2022-04-04 at 12 07 07](https://user-images.githubusercontent.com/60237280/161511575-3a149e79-c847-45b5-b01f-18ac13a42be5.png)
Login
![Screen Shot 2022-04-04 at 13 03 15](https://user-images.githubusercontent.com/60237280/161521721-dde5d707-1a57-436c-899c-25f376c63ff1.png)

* The class diagram will be generated using the Lucichart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram
- [x] Define the attributes of the user class with name, type and description columns.
- [x] Define the methods of the user class withe name, parameters, return type and requires auth columns.
- [x] Check the possible inheritance, association, aggregation, composition relationships.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After each part of the Token class is determined and combined into a diagram, it will be merged into the main class diagram provided in this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

04.04.2022 - Monday - 23.59

### Reviewer

Hasan Can Erol

### Deadline for the Review

05.04.2022 - Tuesday - 10.00

**Comment by bahricanyesil** [comment]
## Info

I will benefit from my previous work in the issue #61. I will extend it, add/remove/update attributes and methods and so that it will become compatible with our current use-case diagram. I checked the use-case diagram and I will be making necessary updates.

**Comment by bahricanyesil** [comment]
## Attributes

I defined the class attributes as follows:

|Attribute Name|Type|Description|
|:-----|:--------:|:------|
|user_id|UID|Id of the user|
|refresh_token|string|The refresh token matched with user|
|expiration_date|Date|The date on which token will expired|
|created_at|Date|The date token is created|
|updated_at|Date|The last date token is updated|
|ip|string|The ip address where the token was created|

**Comment by bahricanyesil** [comment]
## Methods

I defined the class methods as follows:

|Method Name|Parameters|Return Type|Requires Auth|
|:-----|:--------|:------|:----:|
|logout|-|void|true|
|refreshToken|refresh_token: string|access_token: string, refresh_token: string|true|

**Comment by bahricanyesil** [comment]
I completed the token part of the class diagram and also built its composition relationship with the User class. You can access it via our [class diagram project link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/edit?invitationId=inv_26b91b21-bb1b-47cd-96e4-a1a28fc9b0ce). 
Here's the screenshot of the corresponding part:

![Screen Shot 2022-04-04 at 14 30 22](https://user-images.githubusercontent.com/60237280/161534816-6e68a218-a912-43cb-981b-5c9d6eb22e35.png)

**Comment by bahricanyesil** [comment]
The token part of the class diagram is completed, the associated diagram link and ss are given above. Now, it is ready to be reviewed by @hasancan-code.

**Comment by hasancan-code** [comment]
It seems good to me. Nice job @bahricanyesil. Now, the issue can be closed. If anyone who wants to comment about it or add something can reopen the issue.
