### ISSUE TITLE
Documenting the Research of Git History

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#9]
Everyone is contributed to this research. There are several cumulative information about git history. These information should be gathered and documented on the wiki page.

**Comment by onurkomurcu** [comment]
It is added to [Git Summary Page](https://github.com/bounswe/bounswe2022group2/wiki/Git-Summary).

**Comment by egemenatikk** [comment]
I have created an additional page for History of Git by using the text Onur prepared. Here is the link of that [page](https://github.com/bounswe/bounswe2022group2/wiki/Git-History) . You can review it and make necessary changes if you wish.
