### ISSUE TITLE
Frontend: Add links to the usernames in the Comments

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#903]
### Issue Description

We would like to add links to the usernames in the Comments section of our frontend application. Currently, when a user clicks on a username in a comment, nothing happens. We want to change this behavior so that when a user clicks on a username, they are redirected to that user's profile page.

This change will improve the user experience by making it easier for users to navigate to other user's profiles and view their content. It will also make our application feel more interactive and connected.

To implement this feature, we will need to modify the frontend code that displays the posts and add a link element around the username. We will also need to update the backend to handle requests to the user profile pages and serve the appropriate content.

### Step Details

Steps that will be performed:
- [ ] links added to comments

### Deadline of the Issue

26.12.2022 - Monday - 12.59

### Reviewer

None

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! I have tested all the changes you have made and everything works very well!

Since related pull request #904 has now been merged, I will close this issue.
