### ISSUE TITLE
Frontend: Text and Image Annotation backend connection

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#918]
### Issue Description

There is an issue with the connection between the frontend text annotation feature and the backend. The text annotation feature is not functioning properly, and it is unclear if the issue is with the frontend or the backend. We will resolve this.

### Step Details

Steps that will be performed:
- [x] connect get
- [x] connect post

### Deadline of the Issue

26.12.2022 - Tuesday - 02.59

### Reviewer

None

**Comment by xltvy** [comment]
## Update

We have implemented the backend connection for both of the text and image annotation with @gokayyildiz. Since the related pull request #922 is merged, closing this issue.
