### ISSUE TITLE
Software Design: Class Diagram - Message and Profile

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#93]
### Issue Description

As discussed in parent issue #86, I will be completing the message and profile classes on our class diagram on [Lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/edit?invitationId=inv_26b91b21-bb1b-47cd-96e4-a1a28fc9b0ce&page=0_0#).

### Step Details

Steps that will be performed:
- [x] Check use case diagram for required attributes and methods.
- [x] Create the template for the classes.
- [x] Construct diagrams.

### Deadline of the Issue

4.04.2022 - Monday 23.59

### Reviewer

Onur Kömürcü

### Deadline for the Review

5.04.2022 - Tuesday 10.00

**Comment by codingAku** [comment]
UPDATE: The use case diagram of ours has been checked and the following template has been created.
 
![Ekran görüntüsü 2022-04-04 210401](https://user-images.githubusercontent.com/64018144/161608914-40c5bb59-bcd8-465a-9d54-07cb188edc2f.jpg)

**Comment by codingAku** [comment]
UPDATE: Class diagrams for message and profile has been initialized on Lucidchart.
I have some pinpoints to complete after the general class diagram meeting.
1- Public and private attributes
2- connections with other classes that don't exist yet.
![diagrams](https://user-images.githubusercontent.com/64018144/161611753-09fc536e-80ee-4883-ae35-bab94c549eb3.jpg)

**Comment by onurkomurcu** [comment]
I have reviewed your work @codingAku . Thank you for your effort. There are few points that I want to mention.

In profile class:
* I think that in attributes, there should be "**rating**" as integer.
* There should be **isPrivate** as boolean in attributes.

In message class:
* There should be **getMessage()** method.

PS: I'm not quite sure about where should we use getter and setter methods and also connections. We can discuss these topics in the upcoming meeting with our teammates as you said. For now, my feedback looks like this.

**Comment by codingAku** [comment]
> I have reviewed your work @codingAku . Thank you for your effort. There are few points that I want to mention.
> 
> In profile class:
> 
> * I think that in attributes, there should be "**rating**" as integer.
> * There should be **isPrivate** as boolean in attributes.
> 
> In message class:
> 
> * There should be **getMessage()** method.
> 
> PS: I'm not quite sure about where should we use getter and setter methods and also connections. We can discuss these topics in the upcoming meeting with our teammates as you said. For now, my feedback looks like this.

Thank you for the review. getMessage() method along with privacy settings of attributes has been updated. Relations to profile class has been added. Overall, profile and message classes are completed.

**Comment by codingAku** [comment]
UPDATE: As discussed in our meeting, I will add displayedAchievements attribute along with add/remove methods to class diagram of Profile.

**Comment by codingAku** [comment]
![classlast](https://user-images.githubusercontent.com/64018144/163045304-0c3f86da-2a3e-4c07-b1e0-f8389d873aa7.jpg)
The last version of Class Diagram is like this.
