### ISSUE TITLE
Final Milestone: Individual Contributions Report for Gökay Yıldız

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#942]
### Issue Description

For the final milestone, each group member should write a report outlining their individual contributions to the project. This report should include information about the member, their specific responsibilities, any notable code contributions and management challenges they faced, any pull requests they submitted, and any unit tests they created. The member should complete their own section of the individual contributions report.

### Step Details

Steps that will be performed:
- [ ] Member information
- [ ] Responsibilities
- [ ]  Main Contributions
- [ ] PRs
- [ ] Unit Tests
- [ ] Additional Information

### Final Actions

After completing all of the necessary steps on a separate branch, a pull request (PR) will be opened. Once the PR is reviewed and merged, the issue will be closed as well.

### Deadline of the Issue

02.01.2023 - Monday - 11.59

### Reviewer

Altay Acar

### Deadline for the Review

02.01.2023 - Monday - 19.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @gokayyildiz for your valuable contributions! Since I have merged the changes you have made with the master branch to finalize our work on the milestone 3 report, I will now close this issue.
