### ISSUE TITLE
Software Design: Class Diagram - Participant

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#97]
### Issue Description

As the next part of the software design process, we will provide a class diagram for our project moving from the use case diagram phase. Class diagram will be completed with a collective effort and I will be preparing the **participant** sub-section of the diagram.
* This issue is a sub-issue of #86 .
* **Participant** class will be formed, using the following sections of the use case diagram as basis.

Event
![event](https://user-images.githubusercontent.com/100771925/161623821-d9aac6f5-4f3e-4f08-b40d-7fb75fc943c0.png)

* The class diagram will be generated using the Lucidchart app, and the diagram can be viewed [here](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .

### Step Details

Steps that will be performed:
- [x] Check the corresponding parts of the use-case diagram
- [x] Define the attributes of the participant class with name, type and description columns.
- [x] Define the methods of the participant class with name, parameters, return type.
- [x] Check the possible inheritance, association, aggregation, composition relationships.
- [x] Create the diagram in our project page in [Lucidchart](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#) .
- [x] Attach a final comment and screenshot of the diagram.

### Final Actions

* After each part of the Participant class is determined and combined into a diagram, it will be merged into the main class diagram provided in this [link](https://lucid.app/lucidchart/8688dac0-de02-48d2-bed7-f1ef8d62aba6/view?page=0_0#).
* After completion, this issue will be reviewed and evaluated by the team members upon closing the issue.

### Deadline of the Issue

04.04.2022 - Monday - 23.59

### Reviewer

Ecenur Sezer

### Deadline for the Review

05.04.2022 - Tuesday - 10.00

**Comment by bahricanyesil** [comment]
Thanks for your work @egemenatikk. I reviewed the work you did, here are my comments:

1. We should use one of the conventions for naming attributes and as I saw we generally used snake convention with underscores just as you did for the first two attributes. So, it will be better to convert "isParticipating" to "is_participating".
2. Please use "UID" (Unique Identifier) as data type for all id-related attributes.
3. For parameters, please follow the convention. I will give an example and please fix t he other methods accordingly. I guess we should write like "createParticipant(participant_id: UID, event_id: UID)" instead of the type you follow (first data type and then name).

**Comment by egemenatikk** [comment]
Thank you for your suggestions @bahricanyesil.

-I have convert fields which does not obey snake convention to the correct form.

-I have changed the variable type "int" to "UID" in all ID related fields and methods.

-I have changed the convention you suggested just after I added the screenshot. Sorry for inconvenience, I forgot to add the final state of the diagram.

**Comment by egemenatikk** [comment]
Here is the final state screenshot of Participant part of class diagram with all its fields, methods and corresponding relations:


![participant_class_final](https://user-images.githubusercontent.com/100771925/161959704-27b7e5b1-b29b-4a81-8032-af6fa2527390.png)

I think problem of this issue is solved, so I am closing it. It can be reopened in the future if further work is needed.

**Comment by egemenatikk** [comment]
I have added a constructor for Participant class. It already has a createParticipant() method but I thought it would be better if this class also has a constructor.
