### ISSUE TITLE
Software Design: Class Diagram - Tag

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#98]
### Issue Description

Since the use case diagram has been prepared, the design process will continue with the class diagram. In order to contribute to the class diagram collaboratively, the team has decided to separate classes by main operations in the use case diagram. This issue corresponds to the creation of Note class in the diagram.

* This issue is a sub-issue of https://github.com/bounswe/bounswe2022group2/issues/86 .
* Note that Tag class is a supporting class for Note and search feature. 
* In the use case diagram, implemented part corresponds to "add Tag" under notes, as can be seen on #96 .

In the requirements this class covers 
> 1.1.3.2.4.5. Users shall connect, annotate and tag notes.

### Step Details

Steps that will be performed:
- [x] review relevant parts in the use case diagram
- [x] review relevant requirements
- [x] define the attributes
- [x] define the methods/operations
- [x] define the relationships and multiplicities with regards to other classes

### Final Actions

Once a general template for how the class should be is defined, the proposal will be added to the diagram on lucidchart(link above). Upon reviews and the final discussion within the team, it will be finalized and added to the wiki.

### Deadline of the Issue

04.04.2022 - Monday - 23.59

### Reviewer

Egemen Atik

### Deadline for the Review

05.04.2022 - Tuesday - 10.00

**Comment by egemenatikk** [comment]
Thank you for your work @ezgy. I reviewed Tag class you created. I think it contains all the fields and methods necessary. I could not think any other field to add, maybe after class diagram review meeting we come up with something to add. 

One suggestion I can make is that maybe we can add a method called setTagText(). Other than that, it is all good.

**Comment by ezgy** [comment]
> Thank you for your work @ezgy. I reviewed Tag class you created. I think it contains all the fields and methods necessary. I could not think any other field to add, maybe after class diagram review meeting we come up with something to add.
> 
> One suggestion I can make is that maybe we can add a method called setTagText(). Other than that, it is all good.

thank you for your suggestion, I will add it right away

**Comment by egemenatikk** [comment]
I have converted field names to snake form as @bahricanyesil suggested me for my parts of class diagram. Here is the final screenshot of Tag part of class diagram with all its fields, methods and relations:


![tag_class_final](https://user-images.githubusercontent.com/100771925/161961327-8ebc12a2-ae66-496b-9f71-0b7e142e2d1e.png)

I think problem of this issue is solved, so I am closing it. It can be reopened in the future if further work is needed.
