### ISSUE TITLE
Final Milestone: Individual Contributions Report of Koray Tekin

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#981]
### Issue Description

For the final deliverable of this project, each team member needs to include a report detailing their contributions to the final milestone report. This report should outline the individual's role and responsibilities on the project, any notable code contributions they made, any challenges they faced in terms of project management, any pull requests they submitted, and any unit tests they created. I will be adding my own individual contributions report to the final milestone.

### Step Details

Steps that will be performed:
- [x] Member information
- [x] Responsibilities
- [x]  Main Contributions
- [x] PRs
- [x] Unit Tests
- [x] Additional Information

### Final Actions

After I prepare my individual contributions report, I will add it to our final milestone report by opening a pull request accordingly and relating it with this issue.

### Deadline of the Issue

02.01.2023 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

02.01.2023 - 23.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @Koraytkn for your valuable contributions! Since I have merged the changes you have made with the master branch to finalize our work on the milestone 3 report, I will now close this issue.
